src/posthog-persistence.js
@mariusandra These properties started appearing again. Not entirely sure how, might have just been because I already had some data 'persisted', but annoying enough that I think it's worth putting these few lines back?
=> Filter out reserved properties

CHANGELOG.md, package.json, src/autocapture.js, src/posthog-core.js, src/posthog-people.js, src/posthog-persistence.js
This adds supports for launching the new posthog toolbar.js when `toolbarVersion` starts with `toolbar` (and in the future `toolbar.v1` or so). Also adds `jsURL` for enabling HMR support.
I'd release 1.1.0 once this is in.
Also, I noticed that posthog-js is quite noisy. Printing error messages I get, yet some of these `console.log`s here are for sure leftover debug statements:
I'd remove them before pushing out 1.1.0. @timgl any opinion?
=> Posthog Toolbar

src/posthog-core.js
We noticed that if we don't set the user id in the `posthog.identify` call, then all the affected user ids get merged under the `None` distinct ID
This took a while to debug from our side. So this issue hopefully addresses 2 things. Ignores undefined user ids and warns the user via console.error
Some additional context here -> https://github.com/PostHog/posthog/issues/876
=> Adding an undefined check on new_distinct_id for identify events

demo.html, src/posthog-people.js
This will allow you to call `people.set()` at any time, even on anonymous users.
@mariusandra, I'm not sure whether this is going to cause race conditions in capture.py. I don't *think* so...
=> Allow properties on anonymous users

src/autocapture.js, tests/unit/autocapture.js, tests/unit/loader.js
This needs some tests 😅 ... but otherwise here's a bit of cleanup regarding storing the toolbar params in sessionStorage.
This was mainly done for the `delete editorParams.userIntent` part.
=> Clean up how editor params are stored

src/__tests__/autocapture.js, src/autocapture.js
This makes the editor load when the URL contains the string `__posthog={editorParams}` in addition to the existing `state={editorParams}`. The latter caused problems with google tag manager... or something.
=> Add `#__posthog={}` as an option for state params

src/__tests__/autocapture.js, src/__tests__/compression.js, src/__tests__/gdpr-utils.js, src/autocapture.js, src/gdpr-utils.js, src/lz-string.js, src/posthog-core.js
I implemented compression for the JS payloads. It's still sent as base64, just compressed with [lz-string](https://pieroxy.net/blog/pages/lz-string/index.html) before encoding.
Preliminary results are very promising! Here are the sizes of the base64 before and after compression:
These are events with batching enabled. The size difference is especially pronounced when I just clicked a lot on the same thing, generating multiple very similar events.
I'll post an issue soon for the python counterpart to this.
However... this is probably still a bit WIP since there's an open question: How should we solve the case that if you're using an older version of posthog, the newer snippet will stop working? Ideally we should do some "compression protocol negotiation", where the "/decide" endpoint also …
=> LZ-String compression

CHANGELOG.md, src/__tests__/autocapture.js, src/autocapture.js
It was stored in sessionStorage until now, leading to a situation where you had to authorize every tab you had open with the toolbar.
TODO for later:
- Better control of toolbar tokens (connect to personal API tokens?), so you can see what browsers/devices are currently logged in in the toolbar
- Log out for the session in the toolbar (currently it can just be closed, but you can't log out).
=> Store auth token in localStorage

src/posthog-core.js
Sets the ph_* cookie to secure if the used protocol is https. Can always be overriden in the config.
=> Set `secure_cookie` default from browser protocol

CHANGELOG.md, src/__tests__/autocapture.js, src/autocapture.js, src/module.d.ts, src/posthog-core.js, src/posthog-featureflags.js, src/posthog-persistence.js
- Fixes #57
- Adds `.reloadFeatureFlags()` to `posthog`. Calling that updates all feature flags for the current user. (Fixes #70)
- Pass a callback to get the new flags after they reload: `.reloadFeatureFlags(flags => console.log(flags))`
No tests since there are no tests for feature flags... and I don't have time to add any now before the day is over :).
=> Improve feature flags

CHANGELOG.md, src/__tests__/autocapture.js, src/autocapture.js
Resolves: https://github.com/PostHog/posthog/issues/1352
Personally I'm only 80% convinced of this. It makes sense in a demo setting ("my actions aren't showing up"), but on sites with low traffic, a few admins browsing around can massively skew the numbers on the heatmap in one direction or another.
That said, I understand the task and I'm fine with merging this in. However I'd be more confident if there was a "recommended path" to ignore my own actions without having to resort to manually and frequently clearing my person's data.
Could we document some commands that would allow admins to opt out of capturing? Theoretically it *should* be as easy as just calling `posthog.opt_out_capturing()` if you're an admin and that's that?
=> Capture actions if using toolbar

package.json, playground/flags/demo.html, src/__tests__/autocapture.js, src/autocapture-utils.js, src/autocapture.js
Previously we weren't capturing clicks within shadowroots. See playground/flags/demo.html for an example testcase.
=> Fix buttons in shadowroot not being captured (resolves PostHog/posthog#1469)

playground/flags/demo.html, playground/sentry.html, src/posthog-core.js
Integrate this with Sentry:
```js
Sentry.init({
dsn: 'https://example',
integrations: [
new posthog.SentryIntegration(posthog)
]
});
```
It'll send a `PostHog URL` tag to Sentry that allows you to instantly go to the correct person in PostHog: 
Also sends an `$exception` event to PostHog:
Annoyingly we can't get a clickable Sentry URL from just a Sentry Event ID
=> Sentry integration

src/__tests__/autocapture-utils.js, src/__tests__/autocapture.js, src/autocapture-utils.js, src/autocapture.js, src/posthog-core.js, src/posthog-sessionrecording.js
How it works:
- posthog.js hits /decide endpoint
- if `sessionRecording` is true from /decide:
- load rrweb script from posthog
- start recording
- emit events as $snapshot events to posthog
=> make session recording possible

package.json, src/__tests__/posthog-core.js, src/__tests__/posthog-sessionrecording.js, src/autocapture.js, src/posthog-core.js, src/posthog-persistence.js, src/posthog-sessionrecording.js
- Document missing api option
- Add disabling option, start recording before /decide endpoint
- Improve tests
- Use blacklisted const
- Use jest mocking over sinon, simplify given2 usage
- Extract method, add tests
- Minimize the amount of data being sent for $snapshot events
...
=> Improve session recording

src/__tests__/posthog-core.js, src/posthog-core.js
This was broken in commit 72ceba32d4954ab38fd34778201c6830bf0f9b91 by yours truly
...
=> Always send distinct_id to server to avoid 400 status

package.json, src/__tests__/extensions/sessionid.js, src/__tests__/extensions/sessionrecording.js, src/extensions/sessionid.js, src/extensions/sessionrecording.js, src/posthog-persistence.js
Semantics of session id:
- 30 minutes without an event = new session (same as main repo session calculations)
- Two tabs will share the same session id
- Incognito/not incognito/different browser will not share session_id
These may change long-term.
=> Send/create $session_id on $snapshot events

README.md, src/__tests__/autocapture.js, src/autocapture.js
We had a ton of `button......btn` in the elements_chain. Turns out posthog-js sends a bunch of empty classnames if you have spaces in your class attribute. This filters that out.
=> Remove empty class names

src/module.d.ts
- Fix `.reset` typing
- Add better typing for posthog.js
Now users can do `const posthog: Posthog = (window as any).posthog` for example. This did not work previously.
This allows us to use the types in our main repo.
=> Typescript: Add type for instance of posthog

src/__tests__/posthog-core.js, src/module.d.ts, src/posthog-core.js, src/posthog-people.js
- Delete a bunch of dead code around `.identify` and flushing person props
- Kill dead code
- Add user properties when calling posthog.identify()
I got sent down a deep rabbit hole when investigating what `people.set(props)` does. 
Namely it also calls capture $identify, just via a different endpoint and different payloads.
The effect of the two calls is the same, so there's likely room to perhaps kill/merge a lot of 
repeated logic.
Solves #102, related to https://github.com/PostHog/posthog/issues/1955
=> Add user properties updating to `.identify`

cypress/integration/capture.spec.js, cypress/integration/identify.spec.js, cypress/support/index.js, src/module.d.ts, src/posthog-core.js, src/posthog-people.js
Fixes issue #39
Relevant code in people was removed in commit
b6b39a9a7e20091f661a21968807b6f1b345c08c, we don't handle $delete events
in our capture backend.
...
=> Fix 'this.people.delete_user is undefined'

src/__tests__/extensions/sessionrecording.js, src/extensions/sessionrecording.js, src/posthog-core.js
This caused repeatable problem where layout got broken by session
recording as css got cut off.
This didn't happen when we had batching because we send untruncated data
when batching for some reason. This 'fixes' that as well.
=> Don't truncate strings for session recording

package.json, rollup.config.js, src/config.js, src/posthog-core.js, tsconfig.json
`npm version` now automatically bumps LIB_VERSION and it is exposed on window.posthog.
=> Update LIB_VERSION automatically, expose on window.posthog

src/module.d.ts, src/posthog-core.js
Killing this eventually will allow killing much unneeded cruft \o/ It also didn't really work with batching.
=> Deprecate calling posthog.capture with a callback

cypress/integration/session-recording.spec.js, src/__tests__/extensions/sessionrecording.js, src/__tests__/posthog-core.js, src/__tests__/request-queue.js, src/extensions/sessionrecording.js, src/posthog-core.js, src/request-queue.js
Session recording events are sent separately from rest of batches to make sure transport options are enforced and we now send events every 300ms when session recording is on (to avoid dropped events).
=> Batch session recording events

cypress/integration/capture.spec.js, cypress/support/commands.js, src/__tests__/extensions/sessionrecording.js, src/__tests__/posthog-core.js, src/extensions/sessionrecording.js, src/posthog-core.js
- Delete dead code
- Hook into $pageview events in rrweb
rrweb does not capture navigation on SPA-s (e.g. posthog.com/docs), with this
we will still show the correct events in the new design if events are properly
hooked up.
=> Session recording: capture $pageviews as custom rrweb events

.github/workflows/ssr-es-check.yml, package.json, rollup.config.js, src/config.js
Turns out dist/module.js was not bundled in es5, which would cause issues in IE11. [An user pointed this out in a comment under an old commit](https://github.com/PostHog/posthog-js/commit/f2742ede4c4c5837e64e351e198f50ce7c94f802).
This is an attempt towards fixing this + adding tests for the future.
Note: I know next to nothing about library bundling in node world, but the solution seems still less than ideal. @mariusandra do you know any libraries we could 'borrow' inspiration from on how to bundle things properly?
=> Bundle module.js in ES5

cypress/integration/capture.spec.js, package.json, src/__tests__/extensions/sessionrecording.js, src/extensions/sessionrecording.js, src/posthog-core.js
- Force session recording to use lz64 (as it would use base64 before /decide endpoint response)
- Send library version + compression as headers
- Add tests for payload sent to server
=> Force session recording to use lz64

src/__tests__/featureflags.js, src/__tests__/posthog-persistence.js, src/posthog-persistence.js, src/utils.js
Based on a conversation with a user, they were interested in knowing what last touch referrer led to a purchase. This wasn't possible, as we only set the referrer on the first page visit, but not on subsequent page visits within that session.
This correctly sets the $referrer and $referrer_domain in persistence so that it's always set to the last touch referrer.
In the interface this is how we explain this behaviour as well, but turns out we aren't doing this correctly: 
cc @jamesefhawkins as you know more about first/last touch than me. Does this sound right to you?
=> Referrer first and last touch

src/capture-metrics.js, src/posthog-core.js
Part of https://github.com/PostHog/posthog/issues/2560
Needed because we lack a feature: https://github.com/PostHog/posthog/issues/2584
=> Track in-flight requests from posthog-js

src/__tests__/capture-metrics.js, src/__tests__/extensions/sessionrecording.js, src/__tests__/posthog-core.js, src/capture-metrics.js, src/extensions/sessionrecording.js, src/posthog-core.js, src/request-queue.js
Both size and duration should help indicate whether issues are with full snapshots or not.
Based on reading up on HTTP status 0 which has been plaguing it, it can
happen both when browser cancels queries (timeouts) and when CORS hits.
We do set proper headers when we successfully handle requests, but I'm
thinking that failed/timed out requests likely get a different
treatment.
This change will only affect our own team.
I have yet to test this manually, so please don't merge - will do so tomorrow morning. It's still ready for a review though.
...
=> Capture information on failed/in-flight requests

src/extensions/sessionrecording.js
This is another experiment to see how it affects session recording
reliability.
This should significantly reduce payload sizes and thus reduce failure
rates. On the flip side it will make it harder view css if it changes so
it can't really become the default everywhere, I think.
Will roll this back as we do the next release.
...
=> Don't inline css for session recordings

src/__tests__/__snapshots__/send-request.test.js.snap, src/__tests__/send-request.test.js, src/extensions/sessionrecording.js, src/posthog-core.js, src/send-request.js
- Extract code to encode post body
- Copy xhr logic to a different file
- Experiment: Don't compress json sent to the server
lzstring has performance problems on the server-side, causing issues for
session recording: see https://github.com/PostHog/posthog/issues/2560
Note that this is not a backwards-compatible change, requires a change
on posthog side to support plain/text header as well.
We can't use application/json as content-type as that would trigger CORS
requests for every xhr request as that's considered a custom header.
Will test this out for if it does the trick for us (no other users will be affected).
...
=> Experiment: don't compress json sent to the server

cypress/support/index.js, src/__tests__/extensions/sessionrecording.js, src/extensions/sessionrecording.js
I'm planning on starting to cache recorder.js - but we need a cache busting mechanism. This is it.
=> Include library version in recorder.js request

src/__tests__/featureflags.js, src/posthog-featureflags.js
Our users are making use of posthog-js heavily in react contexts,
$feature_flag_called introduces gotchas if ever called in a react render
loop.
We have provided some tooling around this previously but it's a gotcha
for our customers. I propose getting rid of the gotcha all-together.
Now $feature_flag_called will be captured once per posthog.init (e.g.
pageview or session in a react context). Thoughts?
=> Proposal: Change semantics of $feature_flag_called to be once per pageview

src/extensions/sessionrecording.js, src/utils.js
=> Typeof fix for IE11 where Symbol is undefined

CHANGELOG.md, package.json, src/request-queue.js
I just could not get the `||=` working with `parcel` no matter what I tried. Went for the easy solution for now.
The released `1.8.2` already includes this change.
=> Fix parcel

src/module.d.ts
Update to posthog.Properties type to use `Record` type instead of `[key: string]`.
Another potential change you could make is changing the `Property` type to `unknown` instead of using `any`. However at quick glance I can't see whether this would affect the wider typings.
=> refactor: change properties to record type

src/posthog-core.js
adds `prefix` as the 4th parameter to sentry integration
use as such:
```
posthog.SentryIntegration(
posthog,
organization,
projectId,
prefix
),
```
results in the following sentry link: `https://<prefix>/<organization>/issues/?project=<projectId>&query=<eventid>`
`prefix` defaults to `https://sentry.io/organizations/`
=> add prefix argument to sentry integration

src/capture-metrics.js
Sentry error: https://sentry.io/organizations/posthog/issues/2198691106/?project=1899813&query=is%3Aunassigned+is%3Aunresolved
```
TypeError
Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
```
=> Solve a rare edge case where capture_metrics fails

src/__tests__/posthog-core.js, src/module.d.ts, src/posthog-core.js
Inspired by a user question on Slack.
Adds support for doing identify with `$set_once` instead of `$set`. 
Backwards compatible/non-breaking.
=> Support $set_once with identify

src/__tests__/posthog-core.js, src/module.d.ts, src/posthog-core.js, src/posthog-people.js
- Sets the limit of a string that can be sent in a property to 64KB (up from 255 bytes)
- Adds an option `properties_string_max_length` that can be changed to change or remove (`== null`) this limit.
=> Add properties_string_max_length = 65535

src/module.d.ts, src/posthog-core.js
Only thing worse than an absent docstring is a wrong one
=> Add posthog.debug() to types, remove bad docstring

src/module.d.ts
Adds typing for `SentryIntegration`. Bug first spotted on https://github.com/PostHog/posthog/pull/3613/
=> Add SentryIntegration TS

src/module.d.ts
Fixes the issue from https://github.com/PostHog/posthog/pull/3633. Introduced in #202.
=> Fix SentryIntegration optional param typing

src/module.d.ts
According to documents, code, and jsdoc comments, second parameter of `isFeatureEnabled` is optional. This PR fixes the typing to reflect that.
=> fix: incorrect typing for isFeatureEnabled

src/__tests__/utils.js, src/utils.js
Lately we are working on IE11 support and found this weird problem.
TL;DR
After applying babel polyfill for `Symbol`, if you try to create a `Symbol`, whatever it creates is written to the prototype chain, which leads to...
```javascript
var a = Symbol("__I_am_a_symbol__");
var b = {};
console.log(a in b); // true
console.log(a[b]); // undefined
```
As a result, it brakes the in-progress check in `deepCircularCopy`:
https://github.com/PostHog/posthog-js/blob/d939de99893b1f2c2d9287d7d516bdb021908430/src/utils.js#L306
...and causes error in
https://github.com/PostHog/posthog-js/blob/d939de99893b1f2c2d9287d7d516bdb021908430/src/posthog-core.js#L577
...because `data` is `undefined`.
This PR takes the edge case into consideration, and basically does not change the origin logic.
=> Fix in-progress check for utils/deepCircularCopy

src/module.d.ts
Add missing `disable_session_recording` property (documented at https://posthog.com/docs/libraries/js#config) to `posthog.Config` interface.
=> Add missing `disable_session_recording` property in Config interface

.github/workflows/testcafe.yml, README.md, cypress/integration/capture.spec.js, cypress/integration/session-recording.spec.js, src/__tests__/autocapture.js, src/__tests__/compression.js, src/__tests__/decide.js, src/__tests__/extensions/sessionrecording.js, src/__tests__/posthog-core.js, src/autocapture.js, src/decide.js, src/extensions/sessionrecording.js, src/module.d.ts, src/posthog-core.js, testcafe/e2e.spec.js, testcafe/helpers.js
This PR enables running session recording even if autocapture is disabled. This is motivated by a couple of requests from different users who wish to use session recording without autocapture.
- To enable this, we refactor the `/decide` endpoint logic out of the `autocapture` module.
=> Refactor /decide enpoint & allow recording without autocapture

CHANGELOG.md
- Adds what was missed due to the level 8 error that made us not use the bump labels
=> Changelog for 1.10.0

src/__tests__/request-queue.js, src/request-queue.js
Fixes #183 
What a rollercoaster! The `url` is just one of many possible values for the key in the request object, the other possible options being: `batchKey`, which, ofcourse, we set to `sessionRecording` for session recording! ( https://github.com/PostHog/posthog-js/blob/master/src/extensions/sessionrecording.js#L122 )
The annoying bit was figuring out that it was this specific part of the request queue that was mangling things up.
...
=> Fix sessionRecording bug

cypress/integration/capture.spec.js, src/__tests__/autocapture.js, src/__tests__/extensions/sessionrecording.js, src/autocapture.js, src/extensions/sessionrecording.js, src/posthog-core.js
=> Reconcile Server and Client side configurations for session recording and autocapture

react/yarn.lock, src/__tests__/posthog-core.js, src/__tests__/retry-queue.js, src/base-request-queue.js, src/posthog-core.js, src/request-queue.js, src/retry-queue.js, src/send-request.js
Here's a first pass at a retry queue.
There are a few open questions:
- Do we want any config options for this? Polling interval, ability to disable?
- Are there certain status codes we don't want to retry? I've made it so that it doesn't retry 401s, 403s, and 404s, but that's an arbitrary choice to serve more as an example here - don't feel strongly about it.
- I saw that the request queue would stop polling after 4 empty runs, but it didn't reset on a non-empty run in between - do we want to keep this behavior? Given that we're looking for idling here I went ahead and made it so that we need 4 **consecutive** empty runs to stop polling.
EDIT:
So here's some context:
Given exponential backoff, I thought having intervals set for each request would become a bit messy with timers all over …
=> Retry Queue

src/posthog-core.js
The `set_config`-function is directly accessing the `localStorage` instead of using the `localStore` this gives issues when PostHog client is used in restricted environments such as `iframe`-elements which can't access `localStorage` were the current code will throw `AccessDeniedError` which causing other issues.
=> fix: avoid directly accessing localStorage

src/send-request.js
Fixes https://github.com/PostHog/posthog-js/issues/240
`data` was being overridden in the callback and retries were all sending `undefined` payloads
Let's get this in before the release
=> Fix overridden request retry data

src/utils.js
Start capturing the actual viewport size by sending `window.innerHeight` and `window.innerWidth` as props.
Closes https://github.com/PostHog/posthog-js/issues/245#issue-919890687
=> Capture viewport size

src/posthog-persistence.js
https://github.com/PostHog/posthog/pull/4832 addresses #249 for the future. This addresses it "retroactively".
I spent a bit of time looking into converting the base64 token to base36 but it's not super straightforward as [`BigInt` isn't supported in some browsers we target](https://caniuse.com/?search=bigint). And ultimately, we don't actually need it. Replacing the 3 chars that may appear in b64 strings is quite enough.
=> Fix invalid cookie

src/module.d.ts, src/posthog-core.js
We have deprecation warnings from over a year ago, and the "youngest" deprecation happened 9 months ago. Given how messy this codebase already is, it should be fair to remove these now.
=> Remove deprecated methods and options

playground/flags/demo.html, src/__tests__/extensions/sessionrecording.js, src/extensions/sessionrecording.js, src/module.d.ts, src/posthog-core.js
Partly addresses #220 and closes #214. 
Makes `set_config` update session recording changes appropriately, and also introduces `toggleSessionRecording`, which allows one to turn session recording on and off mid-session. This is the setup necessary for sampling sessions with feature flags (now possible), as well as allow us to provide this an an option in the PostHog UI (still to be built).
=> Allow session recording reload

package.json, yarn.lock
=> Add `rrweb-snapshot` to dev deps

package.json, react/yarn.lock
Resolves #252 by putting deps containing necessary types in prod `dependencies`. This should not increase bundle size served to users of our users, since nothing but types is actually imported.
=> Fix deps containing types not being installed

src/__tests__/extensions/toolbar.js, src/extensions/toolbar.js
Currently, if a user disables the toolbar, we'll still load it in some cases. 
Needs https://github.com/PostHog/posthog/pull/5526 to work but safe to merge either way
=> Do not load toolbar when disabled

src/__tests__/decide.js, src/__tests__/featureflags.js, src/module.d.ts, src/posthog-core.js, src/posthog-featureflags.js, src/posthog-persistence.js
- Fix a bug now that we have variants in flags.
- Deprecate client-side overrides for feature flags (move from storing overrides on `person` to `user` model)
- Move a bit of feature flag logic from `persistence.js` to `featureflags.js`
=> Deprecate client-side feature flag overrides

src/utils.js
This adds "gclid" in addition to "utm_*" as a parameter that's captured from the URL and stored as a property on the user. 
We need this to track conversion from google ad clicks.
=> Add gclid to campaign params

src/__tests__/featureflags.js, src/module.d.ts, src/posthog-featureflags.js
Resolves https://github.com/PostHog/posthog-js/pull/271#issuecomment-915993730
TODO: add types
The only difference from before is that the `override(flags)` method now also supports the `flags = {flag: 'variant'}` syntax in addition to `['flag1', 'flag2']`. This also means that the `$override_feature_flags` event property will be passed as an object, instead of an array.
=> Restore feature flag client-side override method

src/__tests__/posthog-persistence.js, src/posthog-persistence.js
Now that we have multivariate feature flags, we have to store the selected variant in the event's properties to be able to filter for and break down by active variants.
How should that look like?
This is what we had before:
```js
event.properties = {
$active_feature_flags: ['beta-feature', 'alpha-feature-2', 'multivariate-flag'],
}
```
The obvious choice would be to store them in an object in the properties, such as:
```js
event.properties = {
$active_feature_flags: ['beta-feature', 'alpha-feature-2', 'multivariate-flag'],
$enabled_feature_flags: {
'beta-feature': true,
'alpha-feature-2': true,
'multivariate-flag': 'variant-1',
}
}
```
... but we can't filter for nested properties. Hence it should be one of those options:
```js
event.properties = {
// keeping for backwards compatibility …
```
=> Split feature flags into `$feature/*` properties

src/posthog-featureflags.js
Fixes the incorrect call to the `override`-function of the persistence object
which expects to receive an `object` instead of `name`, value`-combination.
=> fix: override feature flags not persisted

src/__tests__/autocapture.js, src/autocapture.js, src/posthog-core.js
Previously the toolbar would load only when autocapture was enabled. While most of what you can do on the toolbar is currently related to just autocapture, it won't be so for long. Plus this caused confusion with a customer who passed `autocapture: false` since the toolbar just wouldn't open.
=> Do not load toobar only if autocapture enabled

src/posthog-persistence.js
Since https://github.com/PostHog/plugin-server/pull/214 we set UTM tags as `initial_utm_...` on the person, so you can get real first touch. It makes sense to now change posthog-js to send utm_ properties as last touch, so you can filter on both depending on what you need.
=> Change UTM tags from first touch to last touch

src/__tests__/posthog-core.js, src/posthog-core.js
When developing on localhost - the [docs](https://posthog.com/docs/integrate/client/js) suggest to skip `posthog.init()` entirely.  However, when you do - any calls to posthog.capture throw.  More details here https://github.com/PostHog/posthog-js/issues/281
Since `init_as_module` seems to purposefully skips library initialization (and therefore not set `__loaded` or `_captureMetrics` or several other critical members of the PostHogLib class).  Calling instance methods (like capture) on an uninitialized library causes it to throw.
Simply checking `posthog.__loaded` can allow any of these methods to noop safely.
There were several other instance methods that would likely throw if used (I just have no encountered them in my app so far).  At the very least, identify likely does as well.
=> Do not crash when calling capture() after skipping init(), fixes #281

README.md, src/__tests__/capture-metrics.js, src/__tests__/retry-queue.js, src/capture-metrics.js, src/compression.js, src/posthog-core.js
https://github.com/PostHog/posthog/issues/4816 shows we intermittently receive unexpected values in place of gzipped content
this logging catches unexpected source or zipped data and logs it back to posthog
...
=> Speculative logging for PostHog/posthog#4816

src/__tests__/autocapture-utils.js, src/__tests__/autocapture.js, src/autocapture-utils.js, src/autocapture.js, src/posthog-featureflags.js
This change filters out attributes like `_ngcontent-dpm-c448` or `_ngcontent-c1` in autocapture. These attributes are auto generated by Angular and change on each build, so with them included, there isn't consistency on the event chains between builds, and as a result, our heatmap feature breaks.
Related issue: https://github.com/PostHog/posthog/issues/6135
=> Filter out _ngcontent attributes in autocapture

cypress/integration/capture.spec.js, src/module.d.ts, src/posthog-core.js
This will increase the chance that we capture the initial pageview event if a user navigates away quickly.
Also in the spirit of reducing bundle size I removed the `capture_pageview` function. It was undocumented and likely not used.
=> Send initial pageview immediately

package.json, src/__tests__/__snapshots__/send-request.js.snap, src/__tests__/send-request.js, src/send-request.js, yarn.lock
[Property based testing](https://medium.com/criteo-engineering/introduction-to-property-based-testing-f5236229d237) is a mechanism of sending many different combinations of arguments into some software and asserting on the general result of that. 
Often when property based testing libraries find possible failures. They search for simpler examples of the failure to make them easy to understand. E.g. A library will try to identify not that failures are caused by "very long strings" but instead that they're caused by "strings longer than 6400 characters"
Imagine someone has implemented an algorithm which should always generate a number below 100
```
const fancyAlgorithm = (n) => n > 7 ? 99 : 101
```
It is easy to see in this simple example that the implementation doesn't meet the spec. But …
=> Reduce code paths that could encode post data as the string undefined

package.json, yarn.lock
rrweb 1.0.6 has a few fixes. Notably: https://github.com/rrweb-io/rrweb/pull/696
This change ensures elements in incremental updates that have `ph-no-capture` as a classname will be replaced by a black box. Before, these elements were just removed if they were added to the dom after the first load.
Should resolve: https://github.com/PostHog/posthog/issues/2258
=> Update to rrweb 1.0.6

src/__tests__/autocapture-utils.js, src/__tests__/autocapture.js, src/autocapture-utils.js, src/autocapture.js
In [this PR](https://github.com/PostHog/posthog-js/pull/298), we added a filter for the angular style attribute `_ngcontent*`. These lead to a lot of noise in the element chain (and a potentially broken heat map) because they update on each build.
Turns out angular also uses a `_nghost*` attribute for "elements that would be a shadow DOM host in native encapsulation", and this was another source of noise. This PR filters out all attributes that match the `_nghost*` pattern too.
=> Filter out _nghost attributes from autocapture

src/extensions/toolbar.js, src/module.d.ts, src/posthog-core.js
The instrumentation we have for the toolbar causes issues for self-hosted users due to CSP policies. They should be able to disable this.
The best solution would be a setting in the UI for project settings, but moving fast here to help out a user.
=> allow disabling toolbar tracking for self-hosted users

src/__tests__/posthog-core.js, src/posthog-core.js
Only reload feature flags if user identity actually changes.
Note the comment on user properties.
See also https://github.com/PostHog/posthog-js/issues/339
=> Avoid needless /decide calls

cypress/integration/capture.spec.js, cypress/support/commands.js, cypress/support/compression.js, package.json, src/__tests__/compression.js, src/__tests__/decide.js, src/__tests__/posthog-core.js, src/decide.js, src/module.d.ts, src/posthog-core.js, src/posthog-featureflags.js, yarn.lock
This PR adds support for groups in feature flags in posthog-js.
In theory it could have been a ~3 line change, but this would result in a _lot_ of extra and racy /decide calls.
To have it working sensibly, I also need to cut down on /decide requests:
- we wait until `.loaded()` has been called before calling decide for the first time (to make sure we have all the parameters)
- We batch `.reloadFeatureFlags` calls to only happen once
The batching logic is tested in cypress tests to verify intended behavior.
=> Feature flags groups support & /decide refactor

src/__tests__/extensions/sessionrecording.js, src/__tests__/posthog-core.js, src/__tests__/sessionid.js, src/extensions/sessionrecording.js, src/module.d.ts, src/posthog-core.js, src/sessionid.js
Adds a function `posthog.sessionManager.resetSessionId()` that allows a user to manually reset the `sessionId`. This allows users to split sessions and recordings when they want instead of having to wait for the 30 min timeout.
Been requested a few times, and most recently here: https://posthogusers.slack.com/archives/C01FKPGG5U6/p1640015446465500
=> Add resetSessionId function

cypress/integration/capture.spec.js, src/__tests__/posthog-core.js, src/posthog-core.js
* Changes the alpha/beta performance feature to work for synthetic `$pageview` events
* moves to using a `$performance` key instead of `performance`
* moves unit tests from the `_loaded` describe block to the `capture()` describe block
Follows on from #347
=> Allow APM performance on all $pageview events

src/__tests__/utils.js, src/utils.js
Adds a (static) allow list to allow some properties to be skipped when truncating string properties during event capture
See #354
=> Add an allow list to skip truncating strings when capturing events

src/__tests__/decide.js, src/decide.js
Don't override feature flags when /decide errors, just use the ones still in persistence.
=> Fix featureflags not working when /decide is down

src/__tests__/featureflags.js, src/decide.js, src/posthog-core.js, src/posthog-featureflags.js
Right now we immediately return onFeatureFlags callbacks, even if flags haven't loaded.
@mariusandra given you changed this behaviour
=> Only hit onFeatureFlags callback after decide

src/__tests__/capture-metrics.js, src/__tests__/send-request.js, src/capture-metrics.js, src/posthog-core.js, src/send-request.js
In the postmortem from the 1/21 outage, a concern was raised that we could have been ddos'ing ourselves with the  `$capture_failed_request` event.
While this concern seems pretty unlikely (because only the posthog app has this feature enabled), it looks like the event is from an old session recordings investigation, and I don't think anyone uses it, so this PR removes it.
(also the count of failed capture requests is still available in the `$capture_metrics` event via the status code properties)
=> Remove capture failed request

src/__tests__/compression.js, src/__tests__/decide.js, src/__tests__/featureflags.js, src/decide.js, src/posthog-featureflags.js
Fixes a bug where the callback on `posthog.onFeatureFlags` was not being called.
Looks like this is a new bug, but I'm pretty sure before this bug, we weren't calling `receivedFeatureFlags` from the normal decide response. As a result, we would pretty much always call `posthog.onFeatureFlags` before the decide response using the cached values. After the decide response, the feature flag updated, but `posthog.onFeatureFlags` wasn't called with the updated values until the next refresh. 
Might explain some of the funny behavior around FFs that we've been seeing.
=> Fix for posthog.onFeatureFlags not being called

src/__tests__/extensions/sessionrecording.js, src/extensions/sessionrecording.js, src/posthog-persistence.js
Fixes an issue where if a user has session recording disabled client side when the decide response happened, the disabled state was stored in local storage. It was then impossible to re-enable it client side (because the cached value and the re-enabled value both had to be true). This meant our recommended way of turning on/off recording via feature flags to enable/disable recordings for a subset of users was broken.
The fix was to only cache the server side response in local storage and still respect the client side config during run-time.
In fixing this, I also tried to merge the paths for the two ways that recordings can be started (via the `decide` response and via `startRecordingIfEnabled`)
=> Fix for enabling a disabled session recording

src/__tests__/apm.js, src/apm.js
When investigating [this customer request to use web performance monitoring](https://posthogusers.slack.com/archives/C01GLBKHKQT/p1645608150705189) I saw that even though the spec has a duration property on PerformanceNavigationTiming. We don't always have it available to report page load
This calculates page load if duration isn't present 
...
=> fix(web performance): calculate duration when it isn't present on navigation timing

src/__tests__/posthog-core.js, src/posthog-core.js, src/utils.js
We were adding fields like `$token` and `$window_id` to properties input by users. This isn't great, and led to unexpected errors for users
```
var eventData = {foo: "bar"};
posthog.capture('event_test', eventData);
console.log(eventData); // this has $token and stuff
```
ref: https://posthogusers.slack.com/archives/C01GLBKHKQT/p1647013231963579?thread_ts=1646957568.583359&cid=C01GLBKHKQT
...
=> fix(properties): dont modify input properties

cypress/integration/capture.spec.js, src/__tests__/send-request.js, src/posthog-core.js, src/send-request.js
Reverts PostHog/posthog-js#351
This is breaking the `/decide` request because it adds a second `v=...` query param, so the request looks like `http://localhost:8000/decide/?v=2&ip=1&_=1647974321278&v=1.19.1`
=> revert: "feat: send library version outside of compressed body as a debug signal"

cypress/integration/capture.spec.js, src/__tests__/send-request.js, src/posthog-core.js, src/send-request.js
reverts #375 which reverted #351
----
We add the library version to event properties. This is really useful when debugging problems.
When decompression of the request body fails we get an error report in Sentry. But we can't add the library version to the Sentry report because it is inside the compressed content.
This change adds the lib version to an HTTP query parameter so that it would always be available in Sentry. We could (optionally) follow up by having the backend add that library version as a tag to Sentry so we get richer behaviour in the Sentry UI
----
This originally added parameter `v` clashed with an existing parameter on the decide calls.
All of the network calls on the tests are mocked, so the tests on decide didn't catch this. And other tests on other areas might not …
=> feat: send library version outside of compressed body as a debug signal

src/__tests__/posthog-core.js, src/apm.js
The web performance page sometimes shows resource loads after a large gap. In one case after a greater than 40 minute gap.
It is likely this is someone returning to a page after a large gap and navigating within the SPA.
The web performance code (incorrectly) assumes that the browser performance resource entries are always fresh and relevant. 
This change clears resource timings after reading them to avoid this
- [-] TypeScript definitions (module.d.ts) updated and in sync with library exports (if applicable)
=> fix(web-performance): clear resource timings after reading

src/__tests__/gdpr-utils.js, src/gdpr-utils.js, src/posthog-core.js
- Config can be undefined during the optout check which [errors](https://posthogusers.slack.com/archives/C01GLBKHKQT/p1649076377124529) out `TypeError: Cannot read properties of undefined`
- this adds a check on the config object
...
=> fix(config): Handle config undefined

src/__tests__/extensions/sessionrecording.js, src/extensions/sessionrecording.js, src/module.d.ts, src/posthog-core.js
Adds the configuration for inlining the stylesheets in recordings. By default this is on, but turning it off is really useful for customers who:
* Have large stylesheets (to keep the size of the recordings down)
* Are hitting some bugs in Chrome's MutationObserver's css serialization
=> feat(recordings): add inline stylesheet option

src/__tests__/extensions/sessionrecording-utils.js, src/extensions/sessionrecording-utils.js, src/extensions/sessionrecording.js
We used to throw an exception if the user logged `console.log(undefined)` when the console log feature is enabled. We were expecting the payload object from rr-web to always be a string, but in this one case, it's not.
This PR handles this case, but ideally we would get this fixed upstream. Logged an issue here: https://github.com/rrweb-io/rrweb/issues/877
=> fix(console-logs): handle undefined and null log

package.json, yarn.lock
RR-web fixed [this issue](https://github.com/rrweb-io/rrweb/issues/790) which has been causing big issues for us (creating giant recordings and crashing browsers)
Updating to get the fix.
=> chore(dep): update rrweb to 1.1.3

src/__tests__/posthog-core.js, src/module.d.ts, src/posthog-core.js
This is useful for cross-domain tracking of anonymous users.
=> feat: Allow overriding device id generation

package.json, src/__tests__/decide.js, src/__tests__/gdpr-utils.js, src/__tests__/posthog-core.js, src/__tests__/posthog-people.js, src/__tests__/setup.js
Noticed that running the test suite has gotten really noisy due to excessive amount of console.errors. This cleans up these tests and ensures we always keep a clean console.
=> refactor(tests): error on console.error/warn

src/__tests__/featureflags.js, src/__tests__/posthog-core.js, src/posthog-core.js, src/posthog-featureflags.js, testcafe/helpers.js
Goes in after https://github.com/PostHog/posthog/pull/10196 - client side support for persistent feature flags
...
=> feat(feature-flags): Enable experience continuity

package.json, src/module.d.ts, yarn.lock
Update sentry function "setupOnce" declaration.
...
=> chore(deps): Update @sentry/types for 7.2.0

src/__tests__/posthog-persistence.js, src/posthog-persistence.js
closes https://github.com/PostHog/posthog-js/issues/419
Looks like there's a bunch of logic around referrer compared to the url handling, so just did the small update to remove setting initial_ref* values (see the issue for more details on why).
=> fix: dont set initial referrer

src/storage.js
We weren't setting subdomain tracking if you used localstorage+cookie as a storage type
=> fix(storage): Fix cross subdomain cookies for localpluscookie

src/__tests__/posthog-core.js, src/posthog-core.js
Ensures we reset the session_id and window_id when the user calls `posthog.reset()`
Before, the issue was that we would clear the values from localStorage, but they still existed in memory.
=> fix(session-id): reset session_id on reset() call

.babelrc, .github/workflows/testcafe.yml, README.md, package.json, rollup.config.js, yarn.lock
In progress. Only thing missing is minification of dist/array.js which I couldn't figure out with rollup
- Use rollup for array.js
- Set a specific module name for define to fix https://github.com/PostHog/posthog-js/issues/433
=> fix: Use rollup and fix define module issues

src/__tests__/compression.js, src/__tests__/decide.js, src/__tests__/posthog-core.js, src/decide.ts, src/posthog-core.ts, src/posthog-featureflags.ts, src/types.ts
Allows for initialising the library with a distinctID, and/or feature flags as well. This id is treated as an anonymous ID, unless you explicitly say that it's not.
This allows for immediate flag availability on load, and makes possible to do things like: redirect pages based on feature flags (which wouldn't have been possible earlier, since the flags take some time to load)
@mariusandra , @Twixes  , have a look here for how I expect this to be used: https://github.com/PostHog/posthog/pull/11704 -> just a PoC, to help review this PR, if you want interface changes, etc. etc.
...
---
Tested by running locally with the PoC PR, see everything works as expected.
=> feat(feature-flags): Enable bootstrapping the library

playground/session-recordings/index.html, playground/session-recordings/server.js, src/__tests__/sessionid.js, src/sessionid.ts
Whenever a user duplicates a tab (right click duplicate tab, new windows, window.open(), cmd + click refresh icon, etc.) the session storage from the original tab (where we store the recording's windowId) is duplicated into the new tab. Today it is impossible to differentiate tabs created in this way, and users are running into issues where parts of the recording are lost or malformed. 
Example: https://posthogusers.slack.com/archives/C01GLBKHKQT/p1662734141817939
It's tricky to differentiate a tab duplicate from a tab reload. In the first case, we want to use a new window id to generate a fresh set of snapshots, whereas in the second we want to persist the same window id.
In order to differentiate the two, this PR exposes a new key `do_not_refresh_window_id` in sessionStorage only on the …
=> fix(recordings): unique window id on duplication

src/__tests__/extensions/sessionrecording.js, src/extensions/sessionrecording.ts, src/posthog-core.ts, src/posthog-persistence.ts, src/types.ts
Allows for enabling/disabling console logs from the server.
If the client side setting is set, that's used. Otherwise, it falls back to the server side setting.
=> feat(recordings): server side console log setting

src/__tests__/decide.js, src/decide.ts, src/types.ts
When the `/decide` endpoints contains code in the format:
```js
{
inject: [{ 
id: 9,
source: 'export function inject({ config, posthog }) { console.log("hello"); }', 
config: { key: 'value' } ,
}]
}
```
then posthog-js will execute it.
This is needed to get https://github.com/PostHog/posthog/pull/12003 working.
What do we send and when is still up for debate in that linked issue, though getting this in will greatly help local dev and testing for apps at the hackathon here in Rome.
=> feat(apps): inject javascript from decide

src/__tests__/decide.js, src/decide.ts, src/posthog-core.ts, src/types.ts
Must explicitly set `opt_in_web_app_injection` to true in order to get injected web apps working.
=> feat(apps): add opt_in_web_app_injection

src/__tests__/decide.js, src/decide.ts, src/types.ts
Seeing `window.eval` in the posthog-js codebase triggers all sorts of warnings. Let's avoid it.
=> feat(apps): load web apps from external scripts, no eval

src/decide.ts
This one `web_js` didn't get renamed.
=> fix(apps): grab the correct global var

src/utils.ts
Adds `$language` as per https://github.com/PostHog/posthog/pull/11722#discussion_r994771992.
- This is available in all browsers~~, except IE where `navigator.language` is undefined~~ including IE (though the value is  not as reliable there)
=> feat(capture): Track `navigator.language` as `$language`

src/__tests__/autocapture.js, src/__tests__/compression.js, src/__tests__/decide.js, src/__tests__/extensions/toolbar.js, src/extensions/cloud.ts, src/extensions/toolbar.ts, src/posthog-core.ts, src/types.ts
Implements
```ts
window.posthog.loadToolbar({ temporaryToken: 'key' })
```
With the aim to
1. provide an alternative to the `#__posthog={state}` url hash method to load the toolbar
2. provide users a way to capture the hash themselves in their single page app, and pass it on to posthog
Other params to `temporaryToken`, if provided, are passed on to the toolbar as well. Ideally they are not needed.
This PR also renames some old `Editor` identifiers into `Toolbar`, to better reflect our product. In a backwards compatible way 🤞.
There will be a follow up PR to the main repo with the some other improvements.
=> feat(toolbar): posthog.loadToolbar({ temporaryToken: 'key' })

src/extensions/sentry-integration.ts, src/posthog-core.ts, src/types.ts
This new `ui_host` option allows setups with reverse-proxied PostHog Cloud to still have a good Sentry experience. Customer issue: ZEN-980.
=> feat(sentry-integration): Add `ui_host` option for reverse-proxying

src/__tests__/utils.js, src/utils.ts
I encountered an issue when sending an object from our state management store, which freezes objects in development, to `posthog.capture`. When the input value is copied before it's sent a property is added to keep track of recursive objects. For frozen objects this cause a TypeError with the message that the object is not extensible. Since the copy function is interrupted the special property is also not removed from the input value.
This fixes the issue by using an array to store the values that have been seen before instead of a special property. I added it inside the function so that the values don't leak and created a new function that has access to it.
Fixes #393
=> fix: support copying non-extensible objects

package.json, yarn.lock
We want to upgrade Sentry in https://github.com/PostHog/posthog/pull/13061 but that requires that the types here are updated first.
=> chore: update sentry types

src/posthog-core.ts
Turns on `$rageclick` by default. This was a feature that was turned off in most prod instances by default back when session recordings was in beta.
@corywatilo https://squeak.cloud/question/347
=> feat(rageclicks): turn on rageclicks by default

cypress/e2e/capture.cy.js, package.json, src/__tests__/autocapture.js, src/__tests__/posthog-core.js, src/autocapture-utils.ts, src/autocapture.ts, src/posthog-core.ts, src/types.ts
add the ability to configure autocapture events with an allowlist of regex urls and/or an allow list of events
as requested in: https://github.com/PostHog/product-internal/pull/382
e.g. 
```
autocapture: {
event_allowlist: ['click'],
url_allowlist: ['*/docs/*],
element_allowlist: ['button']
css_selector_allowlist: ['[track-this="yes"]']
}
```
TODOs:
- Keeping page views as separate for now
=> feat: event_allowlist and url_allowlist for autocapture

src/__tests__/page-view-id.js, src/page-view-id.ts, src/posthog-core.ts
In order to level-up web performance we want to store data differently and be able to load all performance data for a session or all performance data for a pageview
But we have no (fast) consistent way to associate an event and its pageview
This 
* adds an in-memory pageview id manager which ensure it always returns a GUID
* rotates that GUID on pageview
* attaches the GUID to the pageview and all subsequent
Tested by running locally and seeing pageview IDs rotate (nb the screenshot runs from newest at the top to oldest at the bottom)
=> feat: page view ids

src/utils.ts
Adds some new excludes of common user-agents from spiders/crawlers. I also added `bot.htm` and `bot.php` as lots of sites crawlers to have them at the end (or even `bot.html` which is encompassed by `bot.htm`).
...
=> fix(ua): Add additional user-agents to ignore list

package.json, playground/session-recordings/index.html, playground/session-recordings/server.js, src/__tests__/posthog-persistence.js, src/posthog-persistence.ts, yarn.lock
Hopefully should help https://github.com/PostHog/posthog/issues/13073
Some Consent Management Platforms (CMP) like Osano use a MutationObserver to watch for any changes to a cookie. In response they often change something about their UI. This causes infinite loops where Session Recordings records a mutation, updates a cookie, which triggers the CMP to modify the UI, which triggers a DOM mutation, which we record... etc.
This changes the "register" calls which are the main offender here to first check if any properties have actually changes before persisting to a cookie.
Tested with the playground html against Osano and it seemed to fix the issue.
=> fix: Reduce cookie modifications to stop infinite loops with CMP tools

.github/workflows/cd.yml
- Uses pnpm in the cd workflow responsible for updating the posthog-js version in the main repo. This workflow is [currently broken](https://github.com/PostHog/posthog-js/actions/runs/3707920840/jobs/6284956492).
~~- [ ] Tests for new code (see [advice on the tests we use](https://github.com/PostHog/posthog-js#tiers-of-testing))~~
~~- [ ] Accounted for the impact of any changes across different browsers~~
=> fix(cd): use pnpm to install posthog-js version in main repo

src/__tests__/posthog-core.js, src/posthog-core.ts, src/types.ts
Some users want to capture pageviews but not pageleave.
=> fix(options): Add capture_pageleave option

src/extensions/web-performance.ts
In https://github.com/PostHog/posthog/pull/13511 we added a `Server-Timing` header to PostHog responses.
This lets us capture those server timings as `$performance_events`. They can then be surfaced as additional information alongside Navigation and Resource events.
Here you can see the timings appearing alongside other events. 
It looks to be "good enough for rock and roll"™️ to rely on timestamp to correlate these for now
In future we should probably add a correlation ID to the parent and children events so we can be more concrete
=> feat: capture server timings

src/page-view-id.ts, src/posthog-core.ts
Page view ids were only allocated when capture_performance was enabled on the client. But they are needed also when capture_performance is enabled via decide.
So, now they are.
=> fix: page view ids didn't work with server side config

README.md, src/autocapture-utils.ts, src/extensions/toolbar.ts
Restricts toolbar loading only to the body
Removes out of date (thanks to pnpm) local dev instructions.
Fixes https://github.com/PostHog/posthog/issues/13477
---
Ran locally, see the toolbar load in body, works without issues.
...
=> fix(toolbar): Load toolbar only in body for turbolink

src/extensions/toolbar.ts
In #464 (probably) we started serving `toolbar.js` from `app-static-prod` cdn. That CDN ignores queryparams and caches by filename for 24 hours.
When we released https://github.com/PostHog/posthog/pull/13620 this meant that the toolbar was effectively broken as the API had changed but the served JS had not.
This has two changes:
* first, don't use the `jsURL` for the toolbar.js
* second, only change the query param once every 30 seconds to reduce load on django
sends 304 on query param repeat visit
=> fix: use django cache for toolbar js

src/__tests__/autocapture.js, src/__tests__/extensions/rageclick.js, src/autocapture.ts, src/extensions/rageclick.ts
A customer asked if they could look at rageclicks by element. But we don't capture information about the rageclicked elements
Adds elements to rageclicks by injecting the autocapture capture method into the RageClick class instead of using the generic capture method
=> feat: capture clicked elements on rageclicks

src/extensions/sentry-integration.ts
The URL from before was no longer supported. I'll try and add a catch for the old URL but we should also update it to the right one.
=> fix: Sentry URL for recording

package.json
Reverts PostHog/posthog-js#504
See #505 which suggests this might be causing their problem
=> revert: "chore: move types dependency from dependencies to devdependencies"

src/__tests__/featureflags.js, src/posthog-core.ts, src/posthog-featureflags.ts, src/types.ts
- v3 decide endpoint returns _all_ feature flags. Make sure flags that are returned on the callback function are only truthy
=> chore(feature-flag): only return truthy values for onFeatureFlag

src/__tests__/posthog-persistence.js, src/posthog-persistence.ts
In #524 I misunderstood how persistence works and all of our tests are in the same page load so didn't see the issue.
On a call with a customer we had some overlapping issues but also saw that when there is a page load between reset and identify we're not holding the correct state. So checking for it is never going to work.
This would be obscured/fixed by #530 which defaults to anonymous unless identified. But I want to get this fix in separately.
=> fix: correctly persist user state across page loads

package.json, src/extensions/sentry-integration.ts
We have had multiple compilation issues with people using Sentry due to different types conflicting with the exact package we have.
Given we only use a small subset of the functionality, we can remove the typings from the code and allow them to be lose, only using them when developing.
This isn't perfect as we don't know which versions end up breaking things but feels much better than the constant back and forth of updating the packages everywhere.
Example of this problem here: https://github.com/PostHog/posthog/actions/runs/4232636013/jobs/7352610629
=> fix: Removed Sentry types from compiled types

src/retry-queue.ts, src/storage.ts, src/utils.ts
Hey folks, thank you for all your hard work on PostHog, it makes my life much easier in my projects! 🥰 Thank you for taking the time to help me with this contribution!
PostHog currently [does advertise](https://posthog.com/docs/integrate/browser-extension) that it can help people to build browser extensions. This is certainly true and works for two out of three "parts" of a [browser extension](https://medium.com/@jonnykalambay/anatomy-of-a-chrome-extension-54b9dd019825) -- content script and popup script.
Things break down unfortunately if someone tried to use it in the last part -- the background script. No docs state otherwise, so I know I'm in the unsupported land. But I hope the support can be extended to background scripts as they are an essential part of the more complex extensions. …
=> fix: more leniency for envs with 'window' undefined

package.json
#541 auto version bump failed because it was a fork. This is a no-op change to bump the version.
See #548 where the formatter had too much fun with the changelog
=> chore: no-op change to allow version bump

src/__tests__/extensions/sessionrecording.js, src/__tests__/posthog-core.js, src/extensions/sessionrecording.ts, src/loader-recorder-v2.ts, src/loader-recorder.ts, src/posthog-core.ts, src/posthog-persistence.ts
This should be merged in before https://github.com/PostHog/posthog/pull/14333
https://user-images.githubusercontent.com/13460330/220994940-2267d598-ee46-4042-8f8d-ebfb9c94178d.mov
=> feat(rrweb): implement rrweb2 dynamic loading on decide

.github/workflows/bundled-size.yaml
Adds an action to report bundled size onto PRs
=> chore: try the compressed-size-action GH action

src/extensions/web-performance.ts
fixes: #550 
In safari we see
```
[Error] TypeError: undefined is not an object (evaluating 'o4[Symbol.iterator]')
_createForOfIteratorHelper (chunk-D2WWLDOM.js:44466)
_capturePerformanceEvent (chunk-D2WWLDOM.js:47391)
(anonymous function) (chunk-D2WWLDOM.js:47323)
forEach
(anonymous function) (chunk-D2WWLDOM.js:47322)
```
That maps to the code in capturing web performance that enumerates performance event `serverTiming`. Appears that other browsers are tolerant of `for x of undefined` where Safari isn't.
=> fix: safari iteration error on web performance server timing

src/__tests__/autocapture.js, src/autocapture.ts
When instrumenting the notification button I wanted to know how many unread notifications were visible that (maybe) caused someone to click on the buton.
But to do that I would have had to add a custom event. 
---
Now you can add a data attribute in the format `data-ph-augment-autocapture-property-name` 
So for `<div data-ph-augment-autocapture-property-name="234"></div>` the autocapture event includes  in its properties {property-name: 234}
=> feat: augment autocapture using data attributes

src/__tests__/extensions/sessionrecording.js, src/extensions/sessionrecording.ts, src/types.ts
Exposes the rrweb option to record canvas elements. False by default.
=> feat: allow record canvas

src/utils.ts
Adds the string "hubspot" to user agents that aren't allowed.
Might fix bot spam for some users.
=> fix(bots): add "hubspot" and "crawler" to blocked user agents

README.md, package.json, src/__tests__/autocapture-utils.js, src/autocapture-utils.ts, src/autocapture.ts
Fixes https://github.com/PostHog/posthog/issues/14387
If an anchor or button element had its text nested inside a `<span>` (eg `<button href="#"><span>Some Text</span></button>` then autocapture would not assign that text to the button when the button click was captured. So if in the example there, someone clicked on the button element but not directly on the span (because padding or something) then it would capture the button click, but someone's action for `autocapture text contains Some Text` would _not_ get triggered.
With this change we now iterate through any children inside `a` and `button` elements, looking for `span`s, pull the text out of those spans, and assign them to the button text property.
❓ I'm not sure how impactful this change will be... I believe that this would be the …
=> fix: spans inside buttons

src/__tests__/extensions/sessionrecording.js, src/extensions/sessionrecording.ts, src/types.ts
We added the option for recording canvas but we can't support it yet - [see this issue for more context](https://github.com/PostHog/posthog/issues/14555)
=> chore: Revert canvas recording option

react/src/context/PostHogProvider.tsx
Removes warning of duplicate posthog import, as this occurs normally when using react strict mode
=> fix: remove warning of duplicate nextjs import

src/extensions/sessionrecording.ts, src/loader-recorder-v2.ts, src/loader-recorder.ts
We had some different ways of loading recorder.js one of which led to a race condition that loaded it before it was available. This fixes it.
Also wraps the capture hook in a try catch to avoid any major crashes.
=> fix: Race condition error with loading rrweb

src/extensions/sessionrecording.ts
We have a call for doing a full snapshot but with rrweb2 this throws an error if called without an active recording.
=> fix: Only call capture snapshot if recording

src/__tests__/autocapture-utils.js, src/autocapture-utils.ts
We have no idea why we're getting errors when augmenting `a` and `button` elements with text from children. So we're gonna try just returning an empty string for the nested span text to see if that stops the errors, which will help us identify the source of the problem.
...
=> fix: debug return empty string on getNestedSpanText

src/__tests__/autocapture-utils.js, src/autocapture-utils.ts
Simply returning an empty string from `getNestedSpanText()` stopped the sentry errors. The next most suspicious thing is the recursion, and also a couple missing `?` checks. I've reinstated most of the `getNestedSpanText` function but left out the recursion, so it'll only go one level deep. I've also added some `?` to make sure we're not failing unexpectedly in some places. 
...
=> fix: reinstate getNestedSpanText, but with no recursion

src/__tests__/autocapture-utils.js, src/autocapture-utils.ts
#576 restarted the sentry errors, so it's not the recursion that is the problem but something else with the function. Next suspect is the concatenation function? Maybe if it throws it somehow ejects the element? (I know this doesn't make sense because if it throws it should throw completely but none of this makes sense so 🤷‍♀️ )
...
=> fix: debug nested span text (part 2)

react/src/context/PostHogProvider.tsx
Adds the types for the PostHog provider `options` parameter
Also adds `posthog` to the useEffect as otherwise vscode was complaining
Fixes the issue mentioned in https://github.com/PostHog/posthog.com/pull/5489
> options also as not typed currently (type: any). Is it possible to add typesafety to this parameter?
Ran this locally with the playground and checked that I could see the type signature
=> chore: added types for PostHog provider `options`

src/extensions/sessionrecording.ts
Not sure why this is happening but it seems sometimes the `emit` from rrweb triggers our logic to decide we should do a fullsnapshot which struggles because rrweb isn't "ready". I couldn't reproduce locally but given this is an optimisation of sorts, I decided to just wrap it and log it rather than erroring out and breaking the recording
[Related Sentry error](https://posthog.sentry.io/issues/4005222646/?project=1899813&referrer=slack)
=> fix: Catch fullsnapshot error

src/__tests__/autocapture-utils.js, src/autocapture-utils.ts
Still [receiving errors](https://posthog.sentry.io/issues/?project=4504038670008320&project=6423401&project=1899813&project=4503944059682816&project=6331159&query=is:unresolved+el_text&statsPeriod=14d) on getNestedSpanText and I'm fully out of ideas. If we just try/catch it will it preserve the element instead of ejecting it?
...
=> fix: try/catch the bit that fails in getNestedSpanText so we don't just eject the element

src/autocapture-utils.ts, src/autocapture.ts
I'm waiting for another build to finish and my brain was chewing at this...
I thought I'd try making it more like `getSafeText` and remove as many moving parts as I could think of
It's very much a "poke it with a stick and see what happens change"
=> fix: fewer moving parts more like safe text

README.md
It looks like testcafe doesn't need the posthog dev server running now,
so I've updated the docs for this. It uses app.posthog.com by default.
...
=> docs(testcafe): update docs removing posthog server requirements

.github/workflows/stale.yaml
Almost all PRs currently open in this repo are over 2 weeks old. In effect, they're braindead. For instance #496 was created almost four months ago, reviewed by a few people, even approved – and then abandoned until a couple weeks ago another customer pointed out the issue that #496 was supposed to solve.
It's not anyone's fault, we just need to be more _disciplined_ about the pull request process on an organizational level.
So this adds tracking of stale issues and PRs, same as already present in https://github.com/PostHog/posthog, which should prevent things from falling through the cracks (or at least make the falling very explicit).
=> ci: Point out and close stale issues/PRs

react/src/hooks/useActiveFeatureFlags.ts
Closes: #596
I'm pretty sure this is what we want. This `flag` param has no effect on the returned array and causes type errors in clients.
...
=> fix: Remove flag param from useActiveFeatureFlags

.github/workflows/typescript.yml, src/__tests__/posthog-core.js, src/posthog-core.ts, src/posthog-persistence.ts, src/types.ts, src/utils.ts
* Adds support for `custom_utm_params` so that people can specify which params they care about in addition to the standard ones
Related docs change https://github.com/PostHog/posthog.com/pull/5703
=> feat: Custom campaign param support

playground/nextjs/pages/_app.tsx, src/extensions/web-performance.ts, src/utils.ts
Localhost is a noisy environment for perf events due to the nature of web dev frameworks. So we turn it off!
=> fix: Don't enable web perf by default for localhost

src/__tests__/featureflags.js, src/__tests__/posthog-core.js, src/__tests__/posthog-people.js, src/gdpr-utils.ts, src/posthog-core.ts, src/posthog-featureflags.ts, src/posthog-people.ts, src/posthog-persistence.ts
When you want properties to be reflected immediately for feature flags, you can now use these functions to override server properties & not wait for ingestion to resolve flags.
Docs here: https://github.com/PostHog/posthog.com/pull/5827
...
=> feat(flags): Allow adding person and group property overrides for flags

src/__tests__/extensions/sessionrecording.js, src/extensions/sessionrecording.ts, src/types.ts
PostHog currently supports blocking elements in session recording by using the `ph-no-capture` CSS class. For most cases this is fine, however in some cases it makes more sense to mask the text (eg. `******`) instead of just rendering blank elements in the recording.
This is particularly useful for applications that display financial data. It can be helpful to see the magnitude of the figure but not the exact value of the figure.
This change simply forwards the rrweb text masking options through as an option for users and sets the default text masking class to `ph-mask`.
=> Expose rrweb options to mask text in session recording

src/__tests__/autocapture-utils.js, src/__tests__/extensions/sessionrecording.js, src/__tests__/extensions/toolbar.js, src/__tests__/utils.js, src/autocapture-utils.ts, src/decide.ts, src/extensions/sessionrecording.ts, src/extensions/toolbar.ts, src/utils.ts
Found an issue where in some browsers (Brave in this case) the script can get loaded faster than the body of the page which leads to a condition where we try to append a script to a body that doesn't exist.
* Fixes this by checking for body and then wrapping with a dom load callback otherwise
* Moves the `loadScript` to utils as it was always confusing to see errors for this coming from "autocapture-utils"
* Changes decide siteapps to use the standardised `loadScript` helper
Hard to write tests for this as JSdom is limited here and it is a very weird behaviour
=> fix: Script loading before DOM is ready

src/__tests__/extensions/sessionrecording.js, src/extensions/sessionrecording.ts
Closes https://github.com/PostHog/posthog-js/issues/625
We have some really overly long recordings full of useless data, largely due to the fact that we don't check for idle timeouts properly. This PR adds an idle timer which means:
* After N minutes we will stop capturing the recorded data
* A physical interaction is required to come out of idle time (closing a tab doesn't count)
* This should ensure the session reset timer works as expected and that we don't capture a tonne of mutations that happen in the background when the user is not interacting with the page
=> feat: Added idle timer to recordings

package.json, src/__tests__/extensions/web-performance.test.ts, src/extensions/web-performance.ts, src/types.ts, yarn.lock
Closes https://github.com/PostHog/posthog/issues/15393
Adds a new `maskNetworkRequestFn` to allow implementers to customize the sent event or ignore it all together.
Built in such a way that we can extend this with request headers / body once we support it.
=> feat: Allow custom masking of network events

src/__tests__/utils.js, src/utils.ts
Added new regexs for matching with the OS versions from the user agent. Currently implemented the version details for the following OSes:
- Windows
- Mac
- IOS
- Android
If needed, I can add for the other OSes too.
fixes https://github.com/PostHog/posthog/issues/6268
=> feat: Added OS version to the OS details

src/__tests__/posthog-core.js, src/posthog-core.ts, src/types.ts
We were handling $set but not $set_once. This fixes that.
Fixes #615
...
=> fix(identify): actually send $set_once on identify calls

cypress/e2e/capture.cy.js, src/__tests__/decide.js, src/decide.ts
Ensures stored properties, if any, are sent for all decide requests, not just on feature flag reload
...
=> fix(decide): Make sure all stored properties are sent on first decide request

package.json, src/__tests__/extensions/toolbar.js, src/extensions/toolbar.ts, src/types.ts
Remove API and JS urls, and instead pass the server just the configured API url.
=> fix: Remove API and JS urls

.github/workflows/lint.yml, package.json
I don't think we had this before. Assuming you have husky installed or
skip pre-commit hooks, this should never be failing.
...
=> ci: add prettier and eslint linting stage

functional_tests/identify.test.ts, package.json, yarn.lock
This is a test around something that we'll likely remove (in https://github.com/PostHog/posthog-js/pull/584), but wanted to
make sure I understood it before removing it.
...
=> chore: add test for $identify events count optimization

README.md
This repo's README has become quite outdated, with references to `yarn`, the Slack community, and regular beta versions. Updating it to better reflect reality, with a focus on documenting the release process accurately.
=> docs: Update README around releasing and development

src/extensions/sessionrecording.ts
We were accounting for "idle time" whilst the page is loaded but on a reload it can happen that the initial non-interactive events get tracked against the old session ID which is not what we want
=> fix: Session timeout overridden on reload

src/__tests__/posthog-core.js, src/extensions/sentry-integration.ts, src/posthog-core.ts
We have a use case for this ourselves where we built a [custom code for getting the replay url](https://github.com/PostHog/posthog/blob/master/frontend/src/lib/components/Support/supportLogic.ts#L14) but this is something people often want themselves so now we offer it.
* Adds a simple getter method for the session_id as well as for the replay URL
=> feat: Add get_session_id and get_session_replay_url functions

package.json, playground/nextjs/pages/_app.tsx, playground/nextjs/pages/iframe.tsx, playground/nextjs/pages/index.tsx, src/__tests__/extensions/sessionrecording.js, src/extensions/sessionrecording.ts, src/types.ts
Enables support for cross origin iframe recording as an opt in
* Required v2 recorder
* Need to create a doc explaining the security implications of this
=> feat: Added support for cross origin iframe recording

react/src/components/PostHogFeature.tsx
First pass:
* removes the double-div
* makes sure that all tracking doesn't trigger a re-render
* Passes props through so that they can modify the div if desired
* @neilkakkar  Haven't actually tested this live yet but I think it works
=> suggestion: Improvements to react flag autocapture

.gitignore, cypress/e2e/capture.cy.js, playground/cypress-full/index.html, src/__tests__/extensions/exceptions/error-conversion.test.ts, src/__tests__/extensions/exceptions/exception-observer.test.ts, src/__tests__/extensions/web-performance.test.ts, src/decide.ts, src/extensions/exceptions/error-conversion.ts, src/extensions/exceptions/exception-autocapture.ts, src/extensions/exceptions/stack-trace.ts, src/extensions/exceptions/type-checking.ts, src/extensions/sentry-integration.ts, src/posthog-core.ts, src/types.ts
adds
* autocapture for exceptions
* autocapture for unhandled promise rejection
* manual exception capture
=> feat: Exception Autocapture

.github/workflows/cd.yml
The main repo uses pnpm 8, so when the `cd.yml` workflow created a PR to upgrade the posthog-js version it was failing
=> chore: correct pnpm version

src/__tests__/extensions/web-performance.test.ts, src/extensions/web-performance.ts
see https://caniuse.com/mdn-api_performanceobserver
and private slack thread https://posthog.slack.com/archives/C0522G09STW/p1685541615179339
performance observer is not always available (e.g. Safari <= 11) and even when it is `supportedEntryTypes` is not always available (e.g. Safari <= 12)
So, let's check it is available before trying to use it
=> fix: performance observer is not always available

src/__tests__/extensions/sessionrecording.js, src/extensions/sessionrecording.ts
It's been /s/ for _years_ let's make it official
=> feat: default endpoint for session recordings is /s/

src/__tests__/extensions/exceptions/error-conversion.test.ts, src/extensions/exceptions/error-conversion.ts
Detecting error types picked generic error before it would pick dom exception/error
Now it checks if it is a dom error first
=> fix: dom exception priority

src/__tests__/retry-queue.js, src/retry-queue.ts
When retrying against posthog we used an (effectively) fixed amount of milliseconds backoff which could cause a [thundering herd problem](https://en.wikipedia.org/wiki/Thundering_herd_problem)
This introduces a random jitter between +/- 50% of the backoff value
See: https://github.com/PostHog/incidents-analysis/pull/33
=> feat: backoff with jitter

.eslintrc.js
You can apply overrides to eslint config based on file patterns
That's great for us because we want to have browser compatibility checks on the code we ship in the SDK but not in the tests. 
This change turns off the browser compatibility tests for anything in ./src/__tests__ folder
tested by seeing linting didn't apply in that directory but did outside of it
=> chore: no compatability testing for test files

src/__tests__/extensions/exceptions/exception-observer.test.ts, src/extensions/exceptions/exception-autocapture.ts, src/types.ts
The first thing I needed to do on testing exception capture was configure errors I wanted to ignore.
This allows decide to return an array of strings that will be tested against exceptions. It drops autocaptured or manually captured exceptions so that someone can configure exceptions to drop without a code change.
backend PR inbound
=> feat: allow decide response to configure errors to drop by pattern

src/__tests__/posthog-core.js, src/__tests__/sessionid.js, src/posthog-core.ts, src/sessionid.ts, src/types.ts
Some people want to have a reduced session timeout. Currently it is hardcoded to 30 mins of idleness (i.e. no events or interactive recording events). This PR allows it to be configured to as low as 1 minute whilst keeping the 30 minute max. 
I think the 30 minute max is necessary as it there are some assumptions around processing that we don't want to break here.
=> feat: Made session timeout configurable

playground/nextjs/pages/iframe.tsx, playground/nextjs/pages/index.tsx, react/src/components/PostHogFeature.tsx, react/src/context/PostHogContext.ts, react/src/context/PostHogProvider.tsx, react/src/hooks/useActiveFeatureFlags.ts, react/src/hooks/useFeatureFlagEnabled.ts, react/src/hooks/useFeatureFlagPayload.ts, react/src/hooks/useFeatureFlagVariantKey.ts, react/src/hooks/usePostHog.ts
PostHogProvider was originally configured with a useEffect to setup the client. This meant the first load would be undefined when it doesn't need to be.
Swapped it to useMemo instead.
=> fix: PosthogProvider doesn't need to have the client be optional

.github/workflows/cd.yml
See https://github.com/PostHog/posthog/pull/16173. This PR removes the pnpm version param from pnpm/action-setup, as it should use the [packageManager field in package.json](https://github.com/pnpm/action-setup#version).
=> fix(cd): use package manager field

src/__tests__/posthog-core.js, src/posthog-core.ts
A friend asked me a question about how $pageview worked which made me realise that capturing page title could be useful when analysing page views.
=> feat: capture page title with pageview

src/__tests__/test-uuid.js, src/utils.ts
In https://github.com/PostHog/posthog/pull/16430 I added a call to the posthog library when api.ts makes a fetch call. In that PR the runs of the visual regression tests would only finish after timing out. 
Visiting storybook manually e.g. https://61260360a8e859003a7c138b-myokuqhoaz.chromatic.com/?path=/story/exporter-exporter--insight would freeze the browser.
`PostHog-js` UUID generation includes a busy loop that tries to measure the number of ticks in a millisecond. The busy loop depends on `new Date()` being a value that changes. But in some tests that won't be true. 
This shifts to using `window.performance.now` this is a high-resolution clock so safe to use for the time-based entropy needed for this UUID generation. And since we read it once, if someone does mock values in their …
=> fix: UUIDs should not take literally forever to generate

cypress/e2e/capture.cy.js, cypress/e2e/identify.cy.js, cypress/support/e2e.js, src/__tests__/extensions/sessionrecording.js, src/__tests__/page-view-id.js, src/__tests__/posthog-core.js, src/__tests__/segment.ts, src/__tests__/sessionid.js, src/__tests__/test-uuid.js, src/page-view-id.ts, src/posthog-core.ts, src/sessionid.ts, src/types.ts, src/utils.ts
The OG UUID generation code in posthog-js is really slow (in comparison to the newer uuid v7 code)
This adds a flag to let us switch to using the UUID v7 everywhere. And still be able to switch back without a deploy cycle.
This is only to allow us to test in prod ourselves before affecting other customers
=> feat: allow moving to UUID v7 by config in posthog-js

src/__tests__/test-uuid.js
These tests are slow but have given us the signal we need about UUID generation speed
=> chore: remove some slow tests that have served their purpose

src/__tests__/posthog-core.identify.js, src/posthog-core.ts
Noticed flags are reloaded 2x on identify calls, because we call reloadFeatureFlags anyway when identity changes.
...
=> fix(flags): Make sure flags are reloaded only once on identify calls

src/posthog-core.ts
see community slack thread https://posthogusers.slack.com/archives/CTLTM70RM/p1689788353368449
`this` is undefined when logging errors during `handle_unload`
We could be extra defensive about logging the errors, but since this is when the page is being shut down are we really going to see the console? 
Send beacon is beset effort, let's allow it to silently fail
=> fix: defensive about unload logging

playground/nextjs/package.json, playground/nextjs/pages/animations.tsx, playground/nextjs/pages/index.tsx, playground/nextjs/yarn.lock, src/__tests__/extensions/sessionrecording.js, src/extensions/sessionrecording-utils.ts, src/extensions/sessionrecording.ts
Certain elements can create constant and heavy mutations in the browser leading to issues in ingestion (and playback) as we try to manage them. Lottie animations are a perfect storm for this.
* Adds a new MutationRateLimiter that watches incoming mutations and throttles them, with special support for SVGs to group all child changes under the svg node
* Implementation wise, the rate limit bucket "refills" each second allowing things like animations to still make a few changes over time
|Actual|Recording|
|----|----|
| ![2023-07-24 16 27 54](https://github.com/PostHog/posthog-js/assets/2536520/6f2698ce-4457-4124-b080-887de6519eed)  | ![2023-07-24 16 28 10](https://github.com/PostHog/posthog-js/assets/2536520/8b02232c-666f-456c-a6d9-d9f630c788c7) |
=> fix: Recording throttling for SVG-like things

src/extensions/sessionrecording.ts
Fixes an issue where emit is called before the recording has started (via the mutation rate limiter)
=> fix: Check for mutation rate limiter

playground/nextjs/pages/index.tsx, playground/nextjs/pages/media.tsx, playground/nextjs/yarn.lock
Add examples of media playback to the Next.js playground
=> chore: add media examples to playground

.github/workflows/testcafe.yml, .testcaferc.js, package.json, scripts/run-testcafe-with-retries.mjs, yarn.lock
Attempting to fix https://github.com/PostHog/posthog-js/issues/778
* Add BROWSERSTACK_FORCE_PROXY and BROWSERSTACK_USE_AUTOMATE which fixed the specific problem around the cloud safari connecting to the test page
* Use a cache to speed up yarn install
* Add a script which will rerun testcafe tests up to 3 times
=> fix: Mitigate testcafe flakiness

src/__tests__/page-view.ts, src/page-view.ts
Follow up from https://github.com/PostHog/posthog-js/pull/773, looks like I did need this
=> feat: Add pathname to prev page events

src/__tests__/autocapture.js, src/autocapture.ts
Element properties might accidentally capture hundreds of kilobytes of data as their values.
Limits each property to 1kb.
Internal context: https://posthog.slack.com/archives/C05N3FJ1P43/p1692976658788549?thread_ts=1692955596.324029&cid=C05N3FJ1P43
=> fix(autocapture): element properties tracked up to 1k bytes

functional_tests/feature-flags.test.ts, src/__tests__/compression.js, src/__tests__/decide.js, src/__tests__/posthog-core.js, src/__tests__/posthog-core.loaded.js, src/decide.ts, src/posthog-core.ts
Fixes https://github.com/PostHog/posthog-js/issues/790
...
=> fix(flags): Re-enable reload only when request finishes

src/rate-limiter.ts
The lint rules have changed since opening #765 so it merged successfully but linting failed and it couldn't be published
Fix the code that fails the linter
=> chore: obey @typescript-eslint/no-unused-vars

README.md, functional_tests/feature-flags.test.ts, src/__tests__/compression.js, src/__tests__/decide.js, src/__tests__/posthog-core.js, src/__tests__/posthog-core.loaded.js, src/decide.ts, src/posthog-core.ts, src/posthog-featureflags.ts
My previous PR delayed reloading to the end of the decide request: https://github.com/PostHog/posthog-js/pull/791 , and for some reason I copied the wrong queue deletion behaviour instead of fixing it right in that PR 🤦 .
If `posthog.identify()` was called while we were requesting flags, we should queue this up and not drop it, as otherwise flags will stick around for the anon user rather than the identified one.
Fixes this behaviour, ~~and removes the now-unused `resetRequestQueue` function~~
...
=> fix(flags): Enqueue follow up requests without dropping

src/extensions/toolbar.ts
Since moving to CloudFront we've been caching toolbar.js and toolbar.css for 24 hours.
The CDN has been updated to vary by allow-listed query-params.
This corrects the comment, and moves toolbar.js to a 5 minute rotating cache
=> fix: toolbar cache busting

src/__tests__/autocapture.js, src/autocapture.ts, src/types.ts
We have seen instances where an element attribute is used to store complex data which can break autocapture parsing.
While it's better to fix those instances, let's also provide our users with an escape hatch,
* Adds a denylist to autocapture config
* Skips capturing element attributes based on that deny list
=> feat: add an attribute denylist for autocapture

src/__tests__/autocapture.js
These tests were useful to me for writing the documentation for the feature.
See https://github.com/PostHog/posthog.com/pull/6755
=> chore: add tests on impact of empty autocapture config

src/send-request.ts
We are killing requests after 10 seconds, causing retries. However, timeouts everywhere else in the system are 60 seconds. If the capture endpoint is slow, we just end up ddos'ing ourselves more
=> fix: Increase timeout to 60 seconds

playground/nextjs/pages/index.tsx, src/__tests__/autocapture.js, src/autocapture.ts
Send the root $el_text as its own property, needed by web analytics.
Add new assertions to existing tests.
Also ran it locally and could confirm that I was seeing it working.
To pre-empt comments that I should be doing this in the plugin-server, that's probably right but this is much faster to implement, and there'd be no problem making that change later on as it would be completely compatible, so I'd rather just move fast and do it here.
=> feat(web-analytics): Add root $el_text

src/extensions/sessionrecording.ts
- Meta events generated by rrweb have a `href` attribute that is now masked by `maskNetworkRequestFn`
- Virtual `$pageview` events have a `href` attribute that is now masked by `maskNetworkRequestFn`
Right now, properties on events can be filtered using `sanitize_properties` to redact any sensitive information in URLs, and `maskNetworkRequestFn` does the same for captured network events. But rrweb has a Meta event that leaks the full page URL, and there is also a mechanism that translates `$pageview` events into rrweb custom events, that captures `window.location.href` directly. I passed these through `maskNetworkRequestFn` to redact sensitive information as necessary. Without this patch, neither of these values can be sanitized by the currently available options.
To be honest, I don't …
=> feat: Mask page URLs in session recordings

src/__tests__/autocapture.js, src/__tests__/compression.js, src/__tests__/decide.js, src/__tests__/extensions/exceptions/exception-observer.test.ts, src/__tests__/extensions/sessionrecording.js, src/__tests__/extensions/toolbar.js, src/__tests__/extensions/web-performance.test.ts, src/__tests__/featureflags.js, src/__tests__/gdpr-utils.js, src/__tests__/posthog-core.js, src/__tests__/posthog-core.loaded.js, src/__tests__/surveys.js, src/autocapture.ts, src/config.ts, src/decide.ts, src/extensions/exceptions/exception-autocapture.ts, src/extensions/sessionrecording.ts, src/extensions/toolbar.ts, src/extensions/web-performance.ts, src/gdpr-utils.ts, src/posthog-core.ts, src/posthog-featureflags.ts, src/posthog-surveys.ts, src/types.ts
Removes a legacy param asked about [here](https://posthog.com/questions/post-hog-config-test-param)
We have a special accessor for the config that doesn't actually do anything whilst also making it really hard to infer types.
This PR gets rid of it and simply accesses the config object.
The "given" concept in tests is a real headache we should move away from... Tried to fix tests without getting too lost in refactoring for now
=> fix: Remove complex get_config

src/__tests__/surveys.js, src/posthog-surveys.ts
[sentry error link](https://posthog.sentry.io/issues/4504159510/?alert_rule_id=14548021&alert_type=issue&notification_uuid=55f52d61-d28f-44f9-8999-5ebae0d73ab1&project=1899813&referrer=slack)
problem: Filtering on undefined surveys causes an error
=> fix(surveys): Handle filtering on undefined

src/__tests__/posthog-core.js, src/posthog-core.ts
@simfish85 [brought to my attention](https://posthog.slack.com/archives/C02E3BKC78F/p1696361572769039) that every `posthog.people.set()` call fires an event, and I realized this can't quite be optimized away just by using the `$set` property in `posthog.capture()`'d events. That's because in the latter case, stored person properties don't get updated, potentially messing up feature flags.
This PR adds the handling around stored person props that `posthog-people` had to `posthog-core`. Let me know if this makes sense, I've not been involved in posthog-js lately.
=> fix(capture): Always update stored person props from $set

README.md, src/__tests__/surveys.js, src/__tests__/utils.js, src/posthog-surveys-types.ts, src/posthog-surveys.ts, src/utils.ts
Copy of https://github.com/PostHog/posthog-js/pull/805  to run cypress tests
...
=> feat: allow regex patterns and wildcards in survey url

src/extensions/surveys.ts
Single choice surveys could not be submitted bug
Regular `querySelector` here returns element instead of a list of elements so we should not check `.length` on it
=> fix(surveys): multiple choice survey submit button bug

src/extensions/surveys.ts
Open text input value was using the on change value instead of the full textbox value, which meant when you typed and then went backspace, it would disable the submit button.
=> fix(surveys): open text value bug

src/extensions/surveys.ts, src/posthog-surveys-types.ts
Adds support for optional survey questions. To go in with https://github.com/PostHog/posthog/pull/17830
https://github.com/PostHog/posthog-js/assets/25164963/6cdf4425-309a-4379-813f-bb125dcd29d4
=> feat(surveys): Optional survey questions

src/storage.ts
Fixes #786.
Changed `DOMAIN_MATCH_REGEX` variable from `[a-z0-9][a-z0-9-]+\.[a-z.]{2,6}$` to `[a-z0-9][a-z0-9-]+\.[a-z]{2,}$`.
It accepts any domain with a TLD length of at least 2 characters, and extracts the domain name only. 
(I'm not sure why there were a `.` in the final section of previous regex, as it also fails on cases such as `me.you.co` as well, where whole string matches with the previous pattern. The new pattern should work fine and extract the domain name.)
...
=> fix: Cross-subdomain tracking is not working for long TLDs

.eslintrc.js, src/extensions/surveys.ts, src/retry-queue.ts, src/storage.ts
Not too happy with the data model here, but will wait to generalise it till we get more examples of ratings we want to support. See https://github.com/PostHog/posthog/pull/18011 for demo. 
This change does imply that existing NPS surveys will get the 0 added to them.
Also fixes some unrelated eslintrc issues. `filter` on a dictionary wasn't working correctly.
...
=> chore: Make ratings start at 0

src/__tests__/utils.js, src/utils.ts
Looks like https://github.com/PostHog/posthog-js/pull/788 broke this - removed the case insensitivity
toLowerCase is supported on IE11 https://caniuse.com/?search=tolowercase
=> fix: Fix bot user agent detection

src/__tests__/extensions/surveys.js, src/extensions/surveys.ts
There was a bug in multiple question surveys where if you had 2 or more multiple choice type questions in the mix, you would be unable to select the input properly because the input IDs in the element were exactly the same
This PR adds a `questionIndex` identifier to the question elements so that it's more unique. It's really only needed for multiple choice type questions but doesn't hurt to have for the others too.
https://github.com/PostHog/posthog-js/assets/25164963/a189cc40-57c7-4c6b-886f-041da1a9a7b3
=> fix(surveys): fix multiple choice input unique ID bug

src/__tests__/utils.js, src/posthog-core.ts, src/utils.ts
resolves https://github.com/PostHog/posthog-js/security/code-scanning/3
We checked for an herokuapp.com domain without caring about the position of the match within the hostname.
So, we would have treated `appname.herokuapp.com` and `appname.herokuapp.com.intercepting-domain.io` as the same.
Well, not any more!
=> fix: heroku subdomain check

src/__tests__/utils.js, src/utils.ts
follow-up to #842 codeql is still unhappy (see https://github.com/PostHog/posthog-js/security/code-scanning/3)
looks like the indexOf check was what is still triggering the alert. given the change we made we can check direct equality instead. Of course I only realised this once I'd merged the previous PR
=> fix: really fix subdomain check to satisfy codeql

src/__tests__/extensions/sessionrecording.ts, src/extensions/sessionrecording.ts
We don't configure regular checkouts on recordings. That is a common perf improvement for "long recordings"
Let's try auto checkout every 30 minutes.
Tested by setting a lower value and seeing full snapshots at expected interval (and checking I could play back the recordings)
=> fix: full snapshot every 10 minutes

src/retry-queue.ts
Add `Browser is offline` to logs when the browser is offline.
We're seeing frequent "Failed to fetch feature flags" errors with one of our users and want to rule out connection issues as the cause.
Slack thread: https://posthog.slack.com/archives/C0522G09STW/p1698051029628329
=> chore: log browser offline status

.github/workflows/library-ci.yml, src/extensions/replay/sessionrecording.ts
follow-up to https://github.com/PostHog/posthog-js/pull/843
that PR introduced new linting and didn't actually fix all of the errors
we were running `yarn eslint` as the CI step, this would run successfully with zero output regardless of whether the `src` folder was lint-able
Well, not any more!
=> fix: eslint does not fail build

src/extensions/toolbar.ts, src/utils.ts
Seems like a lot of web frameworks get in the way of us pulling the state from the location hash. Hacky fix for this is to try and get this info the moment the page loads, rather than after the sdk is initialised.
* Adds that
* Also adds support for base64 decoding the state data which allows us to eventually swap to b64 encoding which is even less likely to get messed up by web frameworks.
=> feat: Toolbar loading from state faster

src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/sessionrecording.ts
follow-up to https://github.com/PostHog/posthog-js/pull/847
After that change, for example, when returning from a long period of inactivity we take two full snapshots. One because we have our own idle check, and one because rrweb only checks if time has passed on emit.
So, we need a more clever solution to have a checkout every X minutes _while active_
=> fix: checkout every X minutes

src/__tests__/compression.js, src/__tests__/decide.js, src/__tests__/posthog-core.js, src/decide.ts, src/posthog-core.ts, src/types.ts
- Handle a new `analytics.endpoint` field in the decide response to allow us to slowly move posthog-js traffic to the new intake endpoint
- Move the compression configuration code to posthog-core.ts too for separation of concerns
=> feat: allow backend to specify a custom analytics endpoint

src/__tests__/extensions/surveys.js, src/extensions/surveys.ts
implements option 3 from: https://github.com/PostHog/posthog/issues/17863
and fixes https://github.com/PostHog/posthog/issues/17652
~~Still need to test perf impact of the setInterval 👀 ~~ - processing takes about 2-3ms per run, and minimal CPU resources, so ok to run on a regular interval. I doubled the interval anyway to keep the check at 1/1000th of the cycle (3s cycle, 3ms per run)
Still need to add a few tests here
...
=> feat(surveys): Make selector targeting work, add user props

src/__tests__/extensions/surveys.js, src/extensions/surveys.ts
small change to update the user survey properties naming
=> fix(surveys): clearer user property names

src/loader-module.ts, src/posthog-surveys-types.ts
Publish survey types alongside other types in the module. @xrdt noticed this wasn't working, which isn't great for API based surveys.
...
Confirmed this issue doesn't come back: https://github.com/PostHog/posthog-js/issues/698
Tested that `import { Survey } from "posthog-js"` works
=> fix(surveys): Publish types in module

src/__tests__/utils.js, src/__tests__/utils/event-utils.test.ts, src/utils/event-utils.ts
I think there are bugs - or at least missing conditions - in our browser detection.
But we don't include the raw data in events so I can't check
Let's include the raw data...
=> fix: include raw user agent in event properties

src/__tests__/utils/event-utils.test.ts, src/utils/event-utils.ts
The _info code takes up a reasonable amount of our bundle (c 3%)
Before we can change it I want to know we can change it safely... 
Let's add tests (and along the way fix a couple of little bugs)
=> fix: add tests for browser and browser version detection

src/__tests__/session-props.test.ts, src/session-props.ts
While updating taxonomy.tsx I realised that I could have done a better job with naming, and it's better to fix this now before anyone is using it.
=> feat(web-analytics): Tweak session prop names

src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/sessionrecording.ts
Maybe the change from starting with null session id was too excitable...
With the session id starting as null we're less likely to pick up a previous session as continuing incorrectly and are more consistent taking a full snapshot when the session starts.
Tested by 
* clearing storage and logging in -> seeing a recording that shows both the pre and post login activity
* and by picking up an old logged in session in Firefox and seeing that the new activity is in its own session
=> fix: session id should start null

src/__tests__/extensions/surveys.js, src/extensions/surveys.ts
Fixes:
1. Whitelabel was not applying to all questions for multiple question surveys
2. Surveys with multiple questions that were of the single choice type was not working because the radio inputs were not grouped per question
3. Auto text color wasn't working for thank you box
=> fix(surveys): whitelabel, input radio grouping, and auto text color bugs

playground/nextjs/package.json, playground/nextjs/yarn.lock
Bump this dependency. It's just the playground project but it was making noise with dependabot, and the automatic PR didn't remove @next/font which is no longer needed.
=> chore: Bump playground next yarn version

src/__tests__/extensions/surveys.js, src/extensions/surveys.ts
Missed a few places to send the property
...
=> fix(surveys): Send responded property with every type of survey

cypress/e2e/session-recording.cy.js
I want to get to a place where the session id bug fixed in #878 would be impossible to merge.
Our session recording integration tests currently check that  
* when you type in a box 
* PostHog sends two things to capture
They don't even have to be $snapshot events let alone correct $snapshot events 🙈 
----
This changes the integration tests to look at what was captured and make some assertions on the content.
It wouldn't protect us from that specific bug we can build on this much more easily
=> fix: meaningful recordings integration tests

src/__tests__/extensions/surveys.js, src/extensions/surveys.ts
Rating type question with emoji displays were bugging out because we were only accounting for the scales for 10 and 5
=> fix(surveys): fix emoji rating scale bug

src/extensions/replay/config.ts
Extend the header sanitization to use a longer deny list 
see: https://posthog.slack.com/archives/C03PB072FMJ/p1699954288200509?thread_ts=1699894781.926149&cid=C03PB072FMJ
=> fix: extend header denylist

src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/sessionrecording.ts
Trying to intuit my way to understanding what is happening with the session buffering.
Logically we can (when there is a minimum duration set):
* have a buffer with data and a session id assigned
* and then the session id changes
* we would then compare the buffer's data timestamp
* with the new session start timestamp
* which would give us a negative duration
* this would never meet the minimum test
* and we would never flush that buffer
Let's make sure that doesn't happen
=> fix: a little session buffering logic

src/extensions/surveys.ts, src/posthog-surveys-types.ts
Prioritize question button text field in favor of appearance's submit button 
https://github.com/PostHog/posthog/pull/18623
=> fix(surveys): prioritize question button text field and thank you countdown is not automatic

src/constants.ts, src/extensions/replay/sessionrecording.ts
Copy how console log config is stored and read so that we have the correct access to payload capture config
=> fix: merge server permissions for payload capture

.eslintrc.js, .github/workflows/library-ci.yml, cypress/e2e/capture.cy.js, cypress/e2e/session-recording.cy.js, cypress/support/commands.js, cypress/support/compression.js, cypress/support/e2e.js, package.json, yarn.lock
We were on an old version of Cypress
Well, not any more!
=> chore(ci): update Cypress

src/__tests__/utils.test.ts, src/posthog-core.ts, src/utils/blocked-uas.ts, src/utils/index.ts
Move the list of blocked UAs to their own file. This allows us to send github links to the file when saying "these are the bots we block" without the line of the file changing or us needing to pin to a specific revision
=> chore: Move blocked UAs to own file

src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/sessionrecording.ts
Sends a custom rrweb event when a session becomes idle and returns from idle
Probably only useful for debugging
=> feat: send idle markers in session

src/__tests__/decide.js, src/__tests__/featureflags.js, src/decide.ts, src/posthog-featureflags.ts
Noticed thanks to a bug report that advanced_disable_feature_flags setting was emptying flags. The test didn't catch this because it was returning extra flags using a mocked decide response when it shouldn't :/ 
...
=> fix(flags): Make sure we don't override flags when decide is disabled

src/types.ts
Someone asked what this did and it seems it's basically an old property replaced by `disable_persistence`
=> chore: Add deprecation notice for disable_cookie

src/extensions/replay/sessionrecording.ts
https://posthog.sentry.io/issues/4662102372/?project=1899813&query=is%3Aunresolved+please+add+custom+event+after+start+recording+PostHog-Recording-URL%3A%22https%3A%2F%2Fapp.posthog.com%2Freplay%2F018c1241-c72e-7c77-855b-e0bd29823f63%3Ft%3D756%22&referrer=issue-stream&statsPeriod=24h&stream_index=0
We see an error where setting a custom event on the session on return from idle is failing because the rrweb recording isn't ready to accept events.
Immediately after that we try to take a full snapshot and swallow any errors
But the full snapshot is relatively important.
Let's make those activities one activity and add a simple retry.
=> fix: safer custom event on return from idle

src/posthog-core.ts, src/utils/index.ts
Came across enough cases of this in support that I figured it was worth making this not possible. We document all over the place "distinct_id" and many people for sure just copy and paste...
=> feat: Show warning if identifying with "distinct_id"

src/__tests__/autocapture-utils.test.ts, src/autocapture-utils.ts, src/autocapture.ts
related to https://github.com/PostHog/posthog/issues/19068
The site in question has `\r\n` style new lines and runs of whitespace in the className on the element that is not being captured correctly.
Switching how we split classes out of elements can quickly support these unexpected class strings.
=> fix: handle newlines in classnames

src/__tests__/posthog-core.js, src/posthog-core.ts
A user had issues loading the recorder.js and this was down to a trailing slash in the api_host.
We always expect it to be without the trailing slash so this change ensures that.
=> fix: Sanitize given api_host urls to not have a trailing slash

src/utils/index.ts
redirect users to the supportModal when implementation errors occur
=> chore: redirect users to the supportModal when implementation errors occur

src/__tests__/posthog-persistence.test.ts, src/posthog-core.ts, src/posthog-persistence.ts, src/storage.ts
Pulled out of https://github.com/PostHog/posthog-js/pull/906 to make only the change to the default storage
=> feat: Swap to localstorage+cookie as default

src/extensions/replay/sessionrecording.ts, src/utils/index.ts
The plugin gathering was incorrect.
It was moved into session recording when deleting the web performance observer in #902. Previously it was correct to return early, now it meant that we couldn't start recording on localhost
🤦 🫠
=> fix: incorrect localhost handling

CHANGELOG.md
release 1.93.7 and 1.93.8 did not succeed because a file did not have the correct formatting, so the changelog was incorrect
this brings the changelog into sync with NPM releases
=> chore: corrects the changelog

src/__tests__/storage.test.ts, src/storage.ts
We use setting cookies to discover the first non-public domain so that we can identify what domain to set a cookie on.
E.g. ww.example.com.au and foo.example.com.au are both on example.com.au. This is because the length of the public part is variable and the list of public domains is very long.
However Firefox prints a warning when it can't set a cookie because of an invalid domain (maybe it only started recently 🤷). This doesn't help anyone. But it does prompt users to ask us why there are so many warnings logged.
You can't change (sub-)domain without a full page refresh. So, it's safe to store that value in memory.
This should mean that someone only sees at most four logs per page refresh
=> fix: cache subdomain discovery

src/__tests__/autocapture.test.ts, src/autocapture.ts
Default join character in JS (it turns out 🤦) is the comma. 
So, [in the change to handle newlines in class strings](https://github.com/PostHog/posthog-js/pull/925/files#diff-f2912c4edd0d573f1786f0face818249e3c6965630c7118ea572bc36b6e283afR113) the split string was accidentally joined with a comma instead of a space.
Frustratingly easy bug to introduce but at least now has an assertion to protect us in future
I checked old events in the explorer (pre 1.94.0) to see what format the elements string is presented in. So I think this now formats correctly
=> fix: class string separator

src/extensions/surveys/surveys-utils.ts
This debug code made it in during a previous PR, and is breaking all live surveys
...
=> fix: Remove debug code from survey-utils

playground/nuxtjs/plugins/posthog.client.js
This is a DX improvement when developing - we can avoid loading the entire barrel file at `#app` by using the new granular imports merged in https://github.com/nuxt/nuxt/pull/23951.
=> fix: import nuxt composables from #imports

src/extensions/surveys/surveys-utils.ts
https://github.com/PostHog/posthog/pull/19320
Link is now optional for link type surveys
=> feat(surveys): make link survey link optional

src/types.ts
RRWeb is proposing a relatively complicated payload/headers capture config. 
We only want to expose a subset of that for launch
=> feat: simplify payload config compared to rrweb proposal

src/utils/event-utils.ts
Add gad_source to campaign params, to keep in sync with https://github.com/PostHog/posthog/pull/19085
=> feat(web-analytics): Add gad_source to campaign params

src/posthog-persistence.ts
Noticed whilst working on some other bits that there was a property that is never used (the user_state is always loaded via props) and that the if else stuff confused me
=> chore: Tidying and removing of old value

src/__tests__/posthog-core.js, src/posthog-core.ts, src/types.ts, src/utils/blocked-uas.ts
We at Cambly would love to capture bot traffic through PostHog. Currently bot traffic is automatically filtered out and there is no way to disable the filter. https://github.com/PostHog/posthog-js/blob/958fec4df19246513264d69d52d5e36a5cf6ed52/src/posthog-core.ts#L869
* Add `opt_out_useragent_filter` config option to allow clients to opt out of user agent filtering (e.g. bots)
* Add `$browser_type` to every capture event to be able to differentiate between bots and regular browsers. Based on [User Agent Populator](https://posthog.com/docs/cdp/user-agent-populator)
=> feat: add opt_out_useragent_filter and $browser_type

src/posthog-core.ts
follow up to #949 
occurred to me to add a comment, but wanted to add that in a PR not from a fork so I can see the testcafe tests pass
this PR will bump minor - despite being only a comment - since #949 can't bump the version as it came from a fork
=> fix: add a comment explaining browser type prop

cypress/e2e/session-recording.cy.js, src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/sessionrecording.ts
Useful when debugging session recordings. let's capture the options used to init rrweb at the start of a session
=> feat: capture session options in a custom event

src/__tests__/extensions/replay/sessionrecording.test.ts
I closed #945 because it wasn't the solution I was after
But, I did have to simplify the tests slightly to make life easier in that PR.
Let's keep that simplification
=> fix: simplify test setup

src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/sessionrecording.ts
We've a bug where the full snapshot is missing at the start of some recordings. 
I think this fixes it - certainly resetting sessions locally I couldn't get it to trigger any more.
=> fix: set the session id as soon as it changes

src/posthog-core.ts
We don't want us.posthog.com to be used for any tracking. The plan is to
1. Push this PR
2. Automatically redirect array.js from us to cloudfront
3. return 301 for any of these endpoints on us (which will break anyone calling those endpoints for the frontend, if they're not on the latest version of posthog-js once this is in)
=> fix: Don't allow us.posthog.com to be used

src/posthog-core.ts, src/types.ts
Remove the setting and replace it with a negated one to disable it, also remove the `__` prefix.
=> feat: Enable scroll stats by default

src/extensions/replay/sessionrecording.ts, src/sessionid.ts
A customer expected to see information about session recording when `posthog.debug(true)`. That makes sense, let's add some.
=> chore: add debug logging for session id/recording

package.json, patches/rrweb@2.0.0-alpha.11.patch, pnpm-lock.yaml
stacked on top of #970 
once we've moved to pnpm
we can use pnpm patch
we have had customer reports of `processMutations` freezing their site
https://github.com/rrweb-io/rrweb/pull/1321 is an improvement to that flow, but unreleased so far
let's patch it in and see if it helps, since it processes the DOM far fewer times it should help in any cases where the DOM is complex enough that the constant rescan is expensive
=> feat: pnpm patch rrweb

.github/workflows/bundled-size.yaml
the bundle size checker autodetects the build tool but couldn't cope with yarn on master and pnpm on a branch
now that master is on pnpm we can turn it back on
=> chore: re-enable bundle checker now master and branches both use pnpm

src/loader-recorder-v2.ts
should resolve https://github.com/PostHog/posthog/issues/20053
streamed responses were blocked by our cloning
let's
* try to return early if the response is probably not going to let us read it
* record the reason for that _as_ the body
* add a timeout to reading the body so we don't block indefinitely if the early return misses something
=> fix: safer body processing

.github/workflows/cd.yml, .github/workflows/library-ci.yml, CHANGELOG.md, README.md, src/posthog-core.ts
3 missed attempts at `gco main` made me realise this is an easy repo to swap over. Pretty sure it isn't linked anywhere else via github in a breaking way and its low enough impact to just find out if so.
=> chore: Swap to main

src/loader-recorder-v2.ts
An early contender for funniest bug of the year 
let's not throw in this case - it's expected to happen at least sometimes - let's set that as the body so we can at least see something / display it nicely when in playback
=> fix: no throwing when reading the body

src/__tests__/send-request.test.ts, src/__tests__/surveys.test.ts, src/send-request.ts, src/session-props.ts, src/utils/event-utils.ts, src/utils/globals.ts, src/utils/request-utils.ts
We moved to fetch to support WebWorkers (🥳 ) but still looked for it on window which doesn't exist in web worker (💩)... 
This PR uses `globalThis` instead (falling back to window) and exports optional values for fetch as well as location that is also partially supported in a web worker.
Ideally we would have proper web worker tests but...
=> feat: Fetch without window

src/loader-recorder-v2.ts
When this was incorrectly throwing we saw this cause errors when I wouldn't have expected it to.
Let's allow more time to clone and read the body
=> fix: less eager timeout

src/__tests__/extensions/replay/config.test.ts, src/extensions/replay/config.ts
I would rather miss collecting some bodies than accidentally send un-processable payloads...
if there is no content-length header then we do not capture the body
=> fix: very defensive body redaction

src/autocapture-utils.ts, src/extensions/surveys.tsx, src/extensions/surveys/surveys-utils.ts, src/rate-limiter.ts, tsconfig.json
Fixes #994
`baseUrl` is currently [set to `./src` in `tsconfig.json`](https://github.com/PostHog/posthog-js/blob/54c8a97616cfc9f5cf692cad5eec4251f11be6f3/tsconfig.json#L3), which allows absolute imports of files within the package.
In v1.104.0, this resulted in the compiled `dist/module.d.ts` file [including an import from a spurious `"types"` package](https://app.renovatebot.com/package-diff?name=posthog-js&from=1.103.2&to=1.104.0#d2h-020126) instead of bundling the imported type (possibly because the imports weren't consistent - sometimes absolute and sometimes relative, leading to them being treated as different?).
This PR removes the `baseUrl` setting and replaces the absolute imports that relied on it with relative ones.
=> fix: Remove `baseUrl` from TypeScript compiler options

.github/workflows/cd.yml
we create the changelog in a separate workflow to creating a release
which leaves the changelog quite rich and the release quite bare
the action we use to create the release supports adding a body
so we can read the most recent entry from the changelog - with some arcane ChatGPT created awk command - and output that to release
defaulting to pointing to the changelog if that fails
see #992
=> chore: add changelog value to release

functional_tests/identify.test.ts, src/__tests__/identify.test.ts, src/posthog-core.ts
i was ill and missed a review on #993 ... rather than comment on a merged pr, i'll propose this here, which we can accept or not as if it was part of the review 😊
we log something as an error, but we also fix the thing immediately.
instead let's log it as a warning - since there's no action needed _really_ - and tell them we've fixed it
----
Fascinatingly... we don't run the functional tests locally... I haven't fixed them, and they still pass even though they're now wrong
=> chore: nit pick log message

.github/workflows/library-ci.yml, functional_tests/feature-flags.test.ts, functional_tests/identify.test.ts, package.json, src/__tests__/helpers/posthog-instance.ts, src/__tests__/identify.test.ts
i've been meaning to make time to add a test instance factory so we can improve the typing of the tests
we do lots of 
```
{
/* snip */
} as unknown as PostHog
```
in test setup
it turns out we have functional tests that we don't run locally, that already have an instance factory.
It also felt wrong to import into `src/__tests__`  from `./function_tests` so this sets us up for using the factory in more tests and reverses that relationship
=> chore: move posthog test instance helper

src/__tests__/autocapture-utils.test.ts, src/autocapture-utils.ts, src/types.ts
A customer set the autocapture config to have a `css_selector_allowlist` of `['[id]']` so that only clicks on elements with IDs are captured.
However we only consider literally the click target so with the tree
```
<button id="any-value">
<svg class="my-icon"/>
</button>
```
if the browser detected the click as coming from the svg then we wouldn't capture the event...
it makes more sense to capture the event if _any_ element in the tree matches the allow list
=> fix: autocapture allowlist should consider the tree

.github/workflows/cd.yml
follow up to: #1002 
mac and GH Actions disagree on what variables are safe to use with AWK.
Fun!
going to YOLO this since it's a CI only change to a workflow that doesn't run right now :/
=> fix: mac and github actions don't agree on usable awk variables

cypress/e2e/session-recording.cy.ts, src/extensions/replay/sessionrecording.ts
let's capture posthog config at the start of recording
that way we'll have posthog config, session recording config, and decide response in network payloads when we're debugging
=> feat: save posthog config at start of session recording

.github/workflows/cd.yml
Writing the last changelog section to the release turned out to be tricky
* [The action we use is archived](https://github.com/actions/create-release)
* The value we want to write contains bash special characters
* GitHub Actions was very allergic to passing those special characters between steps in a way the action could use
But the GH CLI is pretty cool, so we can create a release using that in the same step that reads the changelog value.
you can see that working in a fork e.g. here https://github.com/pauldambra/posthog-js-fork-for-changelog-cd/releases/tag/v1.0.055as5 from https://github.com/pauldambra/posthog-js-fork-for-changelog-cd/blob/0c8250caaab776124ae5aeee107449e021ec78ac/.github/workflows/cd.yml
=> chore: really really write changelog to release

src/__tests__/utils.test.ts
see #1010
adds a test case to check if a specific ahrefs useragent is considered a bot
=> chore: add test case for ahrefs bot

src/utils/index.ts
We no longer send $performance_raw - which was from an early version of the APM hackathon stuff
So, we can save a little bit of bundle by not accounting for it when truncating in capture
=> chore: no need to account for performance raw

src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/sessionrecording.ts
We want to use custom events more... and we're using one to record when a session goes idle - which we immediately drop because the session is idle 🤦 
Lets allow custom events into the buffer while idle
=> fix: allow custom events when idle

.github/workflows/cd.yml
I updated the release mechanism for #992 
I missed a `v` from the tag which mean the first page of `tags` in the GitHub API didn't include that tag which broke the version checker banner in replay 🤯 
(see https://github.com/PostHog/posthog/pull/20263)
=> fix: for want of a v the war was lost

src/__tests__/utils/request-router.test.ts, src/decide.ts, src/extensions/replay/sessionrecording.ts, src/posthog-core.ts, src/posthog-featureflags.ts, src/utils/request-router.ts
Simplifies request router to just use `-api` or `-assets`
=> feat: Simplify to just -api and -assets

.github/workflows/cd.yml, .github/workflows/label-version-bump.yml, .github/workflows/new-pr.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
=> ci: Use GITHUB_OUTPUT envvar instead of set-output command

cypress/e2e/surveys.cy.ts, src/extensions/surveys/surveys-utils.tsx
Quick updates to improve accessibility with increased font sizes and more subtle grayscale button 
addresses a majority of https://github.com/PostHog/posthog/issues/20346
before:
after:
- [x ] Tests for new code (see [advice on the tests we use](https://github.com/PostHog/posthog-js#tiers-of-testing))
=> fix(surveys): survey popover improvements

package.json, playground/nextjs/package.json, playground/nextjs/pages/_app.tsx, playground/nextjs/pages/iframe.tsx, playground/nextjs/pages/index.tsx, playground/nextjs/pages/long.tsx, playground/nextjs/pages/longmain.tsx, playground/nextjs/pnpm-lock.yaml, playground/nextjs/postcss.config.js, playground/nextjs/src/CookieBanner.tsx, playground/nextjs/styles/globals.css, playground/nextjs/tailwind.config.js, pnpm-lock.yaml, react/pnpm-lock.yaml, src/__tests__/posthog-persistence.test.ts, src/posthog-core.ts, src/posthog-persistence.ts, src/storage.ts
Fixes https://github.com/PostHog/posthog-js/issues/1024
* Also adds tailwind to the next playground
Allows doing something like this:
```ts
// Cookieless tracking with swap to cookie-full tracking when enabled
let cookieOptIn = () => localStorage.getItem("cookie-opt-in") === "true"
posthog.init(KEY, { persistence: cookieOptIn() ? "localStorage+cookie" : "memory" }
function optInToCookies() {
localStorage.setItem("cookie-opt-in", "true")
posthog.update_config({ persistence: "localStorage+cookie" })
}
```
=> feat: Allow changing persistence

cypress/e2e/surveys.cy.ts, rollup.config.js, src/__tests__/extensions/surveys.test.ts, src/extensions/surveys-widget.ts, src/extensions/surveys.tsx, src/loader-surveys-preview.ts, src/loader-surveys.ts
1. Adds support for feedback widget previews
2. Fixes a major issue when loading survey preview methods for https://github.com/PostHog/posthog/pull/20321 where `generateSurveys` from the modules file was overriding the `generateSurveys` that we want from the iife file, causing `callSurveys` to not show surveys normally. So we have to either split them up into separate loader files or find a way to distinguish moment in time which script is calling `loader-surveys` 🤔
=> fix(surveys): Render feedback preview

src/decide.ts
Site apps should be loaded from the api not the CDN
=> fix: Path for site apps

src/__tests__/featureflags.js, src/__tests__/posthog-core.js, src/__tests__/surveys.test.ts, src/__tests__/utils/request-router.test.ts, src/posthog-core.ts, src/types.ts, src/utils/request-router.ts
We have this behind a preview flag. Once we are confident this PR makes it the default to use the new `i.posthog.com` endpoints.
=> feat: Rollout new ingestion endpoints

src/extensions/toolbar.ts
Fixes https://github.com/PostHog/posthog-js/issues/1041
We pass in the ingestion api url to the toolbar loader but this isn't quite right. We load the toolbar from the assets endpoint but authorisation etc. has to go via the actual app url.
=> fix: Loading the toolbar via JS

src/__tests__/posthog-core.js, src/posthog-core.ts
While investigating a support ticket I discovered that we have a mechanism to let someone override the timestamp when capturing events. That feels open to confusion
Let's add properties when that happens so we know it did
=> feat: reecord when timestamp is overriden by caller

src/__tests__/posthog-core.js
Some tests cared about a literal time, which meant if you were not in GMT they might fail
=> fix: timezones are fun

playground/copy-autocapture/demo.html, playground/selection-autocapture/demo.html
Added to the demo for copy autocapture to show it does not capture passwords or things marked ph-no-capture
=> chore: add some privacy examples to the copy autocapture demo

src/__tests__/extensions/replay/config.test.ts, src/extensions/replay/config.ts
We had a typo in the code that ignored ingestion paths so we were recording `i/v0/e/` 
well, not any more
=> fix: posthog path to ignore

src/__tests__/autocapture.test.ts, src/__tests__/decide.js, src/__tests__/featureflags.js, src/__tests__/surveys.test.ts, src/posthog-core.ts, src/posthog-featureflags.ts, src/types.ts
We might have supported this along time ago but it is currently doing nothing at all 😅 
The idea was to use script callbacks but from what I can see there is literally nowhere in the code that we support this so it is just a bunch of extra confusing code.
=> chore: Removed jsc callbacks

src/__tests__/utils/request-router.test.ts, src/utils/request-router.ts
Over time we will start moving people to new ingestion domains - we want to ensure this is correctly handled as even now someone might accidentally pick the wrong thing.
=> feat: Ensure ingestion domains follow the same logic.

src/utils/event-utils.ts
Add more ad/campaign ids, see https://github.com/PostHog/posthog/pull/20760 for where I've added this to the pipeline
Add
* gclcsrc
* dclid
* twclid
* li_fat_id
* mc_cid
* igshid
* ttclid
- ~~Tests for new code (see [advice on the tests we use](https://github.com/PostHog/posthog-js#tiers-of-testing))~~
=> feat: Add more ad/campaign ids

src/__tests__/decide.js, src/__tests__/featureflags.js, src/decide.ts, src/posthog-featureflags.ts, src/types.ts
Fire callbacks with error param so we don't block clients waiting for flags to load.
Noticed this isn't present on the first Decide response, will add it there too.
...
=> fix(flags): Fire callback when decide errors out

src/posthog-core.ts, src/types.ts
Some refactoring whilst improving the logic had one side effect - the compression is now a derived value but it is saved in the first event. This means that when the queue is filled, the compression from the first event is used instead of the last one.
To generally make this better I figured it makes sense to be explicit - have a "best-available" option which will select compression as the request is made based on what decide says (with base64 still as the default)
=> fix: Choice of capture compression

src/utils/event-utils.ts, src/utils/user-agent-utils.ts
Browser detection used a value in assignable window `assignableWindow.opera` for Opera browser detection
We don't ever set it
I installed opera on my mac and it doesn't set `window.opera`
Let's remove it
=> chore: remove unused path

src/__tests__/extensions/replay/config.test.ts, src/autocapture-utils.ts, src/extensions/replay/config.ts, src/extensions/replay/sessionrecording.ts
Just like with headers we should be conservative in what we capture in payloads
If the body of the request (or response) contains any of the following we don't capture it
'password',
'secret',
'passwd',
'api_key',
'apikey',
'auth',
'credentials',
'mysql_pwd',
'privatekey',
'private_key',
'tokenconst',
If it matches SSN or CC regex we don't capture it
You can add to this but not replace it
=> feat: scrub payloads with forbidden words

src/__tests__/request.test.ts, src/request.ts, src/utils/globals.ts
I was suspicious that sendBeacon was broken (it isn't) but either way it behaved slightly different to before and needed tests.
Validated it worked in the playground app locally.
=> fix: Send beacon request encoding

src/extensions/surveys/surveys-utils.tsx
Not sure why the opacity was there in the first place, any ideas?
Before
After
(white bg)
(default/blank bg)
=> fix(surveys): fix description background style

src/loader-recorder-v2.ts
When processing network requests in the replay network plugin it was possible  to emit a request that was 
```
{
"isInitial": true,
"requests: ": []
}
```
that is silly, so let's not do that
=> fix: no empty requests

package.json
Forgot to bump patch in https://github.com/PostHog/posthog-js/pull/1070
For some reason, bumping via `npm version patch && git push --tags` didn't work 🤔
=> fix(posthog-js): manually bump patch

src/extensions/replay/sessionrecording.ts
We want to keep adding to the information we can provide to help people understand user behavior.
The browser will tell us as it is hidden or becomes visible.
We can send a custom event when that happens to display in the player inspector
=> feat: report browser visibility state in replay

cypress/support/compression.ts, functional_tests/mock-server.ts, src/__tests__/request.test.ts, src/posthog-core.ts, src/request.ts
* Fixed compression not respecting the `disable_compression` option
* Fixed uncompressed data - it now sends as application/json which works for both old and new capture.
=> fix: Disabled compression and application json

patches/rrweb@2.0.0-alpha.11.patch, pnpm-lock.yaml
ran `pnpm patch rrweb@2.0.0-alpha.11`
then added the fix from https://github.com/rrweb-io/rrweb/pull/1422
then ran `pnpm patch-commit the-location-the-patch-created-for-me`
verified I can still record locally with it
=> fix: patch rrweb zero width canvas bug

src/extensions/replay/sessionrecording.ts, src/request-queue.ts, src/request.ts
Seeing these errors locally
```
src/extensions/replay/sessionrecording.ts:644:9 - error TS2322: Type 'Timeout' is not assignable to type 'number'.
644         this._fullSnapshotTimer = setInterval(() => {
~~~~~~~~~~~~~~~~~~~~~~~
src/request-queue.ts:50:9 - error TS2322: Type 'Timeout' is not assignable to type 'number'.
50         this.flushTimeout = setTimeout(() => {
~~~~~~~~~~~~~~~~~
src/request.ts:159:13 - error TS2322: Type 'Timeout' is not assignable to type 'number'.
159             timeout: setTimeout(() => controller.abort(), options.timeout),
~~~~~~~
Found 3 errors.
```
Don't know why this only happens in my environment but TS suggests the return type should be `NodeJS.Timeout`. Depending on the environment posthog-js is running in we can support the global functions return …
=> fix: return typing of global functions

src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/sessionrecording.ts, src/types.ts
see https://github.com/PostHog/product-internal/pull/571
We rely on rrweb meta events for some href capture, but in a single page app we can't be guaranteed meta event when there is a client side navigation, so we send a $pageview custom rrweb event 
however, if someone is not capturing $pageview events then we won't get those URLs
this adds a fallback so that when page view capture is disabled we still track URL in replay
if someone really wants to use replay but not capture any URLS want to they could provide a URL masking function and  always set the masked result to undefined
this needs changes in ingestion, which is anyway, it turns out, ignoring custom pageview events
----
We four cases
| case | |
|-|-|
|you have capture pageview enabled and event ingestion is working for you | …
=> feat: track recording URL without pageview capture

cypress/e2e/capture.cy.ts, cypress/e2e/opting-out.cy.ts, cypress/e2e/session-recording.cy.ts, cypress/e2e/surveys.cy.ts, cypress/support/e2e.ts, cypress/support/setup.ts
lifting these changes out of #1083 
it was really hard to debug failing cypress tests because we had lots of log warnings and errors around our request interceptors missing requests or not returning expected responses...
well, not any more
=> chore: remove cypress log noise

src/__tests__/loader.test.ts, src/posthog-core.ts
Related to https://github.com/PostHog/posthog-js/issues/1090
We don't return posthog if the SDK is already initialised or if the token is missing. This appears to be a regression
=> fix: Return this if already loaded

src/__tests__/posthog-core.js, src/posthog-core.ts, src/types.ts
We've seen the reasonable typo of `Id` for `ID` when people use distinct id bootstrapping with this SDK
see https://twitter.com/illyism/status/1771586772067123490
Because we accept `Partial<PostHogConfig>` into init Typescript doesn't check for _additional_ keys 
With some typescript magic we can change that behavior without breaking the ability to only pass partial config
=> fix: posthog init should reject invalid config in TypeScript

src/__tests__/extensions/toolbar.test.ts, src/extensions/toolbar.ts
Noticed you can't re-open the toolbar programatically after closing it.
* Changed the logic to check for existing localstorage key. If it exists then exit, otherwise re-open the toolbar.
* Also cleaned up some code around loading the script
=> fix: Reloading toolbar after closing

src/__tests__/decide.js, src/__tests__/featureflags.js, src/decide.ts, src/posthog-featureflags.ts
Don't compress decide requests when disable_compression is set.
Seems we missed this in the request refactor, as previously when this config option was set, decide would disable compression as well. Had a user request about this.
...
added unit tests, ran locally with posthog and see everything works as expected
=> fix(decide): Respect disable_compression for flags

src/posthog-core.ts
Add a query string to help with debugging the first visit to a site.
We already have the local storage version of this, but the query string method allows testing the order of operations when first visiting a site in a private browser tab, where local storage doesn't exist
=> feat: Add __posthog_debug query string

src/__tests__/utils.test.ts, src/utils/blocked-uas.ts
closes #1112 
blocks bytespider user agent
=> fix: block bytespider bot

src/__tests__/posthog-core.js, src/__tests__/posthog-persistence.test.ts, src/posthog-core.ts, src/posthog-persistence.ts
Send `$is_identified property` as a boolean, based on whether `identify` has been called
=> feat: measure identified events

src/extensions/sentry-integration.ts
For #1060 
We register a sentry event processor and only process events with level error
`captureMessage` events pass through the same processor and can have multiple levels. 
We also don't want to change existing behaviour since this could be a high event volume change for people
So this change allows people to opt-in by setting an allowlist of severity levels to capture
You could set `'*'` to process any sentry message
Or `['error', 'info']` to process default calls to `captureException` and `captureMessage`
----
I did consider changing the emitted event so that `captureMessage` did not emit `$exception` but instead `event.message` as the event but it seems neater that the sentry integration always emits the same event type
----
message from `captureMessage` enhanced with PostHog URLs
=> feat: capture more sentry levels

package.json, playground/nextjs/README.md, playground/nextjs/package.json, src/__tests__/identify.test.ts, src/__tests__/posthog-core.js, src/__tests__/posthog-persistence.test.ts, src/posthog-core.ts, src/posthog-persistence.ts
Fix a big that was introduced in https://github.com/PostHog/posthog-js/pull/1114 where $is_identified can be false even when the user is identified.
Instead of letting the session_persistance take priority over the regular persistance, return true if either persistance know the user is identified.
Also added a test to cover this case, and some scripts + docs to make it simpler to use the nextjs playground as a place to test posthog-js changes.
=> fix: Fix $is_identified

cypress/e2e/opting-out.cy.ts, cypress/e2e/session-recording.cy.ts, cypress/support/assertions.ts, src/__tests__/extensions/replay/sessionrecording.test.ts, src/constants.ts, src/extensions/replay/sessionrecording.ts, src/posthog-core.ts
Closes https://github.com/PostHog/posthog-js/issues/1065
allows calling `startSessionRecording` with an override config 
passing `{sampling: true}` overrides sampling decision by setting the current session as sampled so that recording will start regardless of the sample rate
also adds ability to poll for events to fix the opt out cypress tests
---
while testing this i noticed that the sample rate is only stored in memory, and its presence is verified before applying sampling logic, so if a session was sampled and then the page reloaded, we'd not check that whether the session had been sampled on reload, and might re-make the decision (and so not sample the session)
so I switched to storing the sample rate in memory and added a cypress test to verify that the sampling decision survives a …
=> feat: allow override sampling

README.md, playground/nextjs/pages/_app.tsx, src/__tests__/posthog-core.js, src/posthog-core.ts, src/utils/request-router.ts
* Change the default
* Fix so that ui_host removes the `.i.` part
=> fix: Default api host to us.i.posthog.com

package.json, patches/rrweb@2.0.0-alpha.12.patch, pnpm-lock.yaml, src/extensions/replay/sessionrecording.ts
- Upgrade `rrweb` to v2.0.0-alpha.12
- Reapply relevant patches
- https://github.com/PostHog/posthog-js/pull/971 - no longer needed (merged in new version)
- https://github.com/PostHog/posthog-js/pull/1075 - skipped (replaced by more recent patch changes)
- https://github.com/PostHog/posthog-js/pull/1082 - reapplied
Might do a few quick tests locally to see if everything still generally works
=> chore: upgrade rrweb to 2.0.0-alpha.12

.github/workflows/cd.yml
Copy/paste the job to update the main repo.
posthog.com uses the snippet, but still uses the npm version for type info
=> chore: Add workflow to update the posthog.com repo with new posthog-js versions

playground/nextjs/package.json, playground/nextjs/pages/_app.tsx, playground/nextjs/pnpm-lock.yaml, src/__tests__/personProcessing.test.ts, src/constants.ts, src/posthog-core.ts, src/storage.ts
Calling any of the following functions will activate person processing if set to `identified_only`, and fail if set to `never`:
* indentify
* alias
* setPersonProperties
* setPersonPropertiesForFlags
* group
* setGroupPropertiesForFlags
=> feat: Person processing 2 - handle group and setPersonProperties

patches/rrweb@2.0.0-alpha.12.patch, pnpm-lock.yaml
Patch for https://github.com/rrweb-io/rrweb/pull/1445 until the next version of rrweb is released
=> fix: missing parentNode protection

.eslintrc.js, .github/workflows/library-ci.yml, cypress/e2e/session-recording.cy.ts, package.json, pnpm-lock.yaml
We have this linter in posthog but not posthog-js and it is very useful
=> chore: no only tests are allowed

src/__tests__/page-view.test.ts, src/page-view.ts, src/posthog-core.ts, src/scroll-manager.ts
Part of heatmaps work - wanted to separate the scroll calculations from pageviews so they could be used elsewhere more easily.
=> chore: Pageview refactor

cypress/e2e/session-recording.cy.ts, src/extensions/replay/sessionrecording.ts
Addresses https://posthog.com/questions/session-recordings-not-being-resumed-after-calling-posthog-restart
Because we rely on the `decide` response to know whether session recording is enabled, we assume a falsey value when the persistent storage is cleared as part of the `reset` call.
This change sets up a listener `onSessionId` rotation that will re-establish the keys returned by the decide response. We need to re-register all keys otherwise things like the minimum session duration would not be available for the new session.
The sampling decision for the new session is handled separately in the `_samplingSessionListener`
=> fix: continue recording after reset

patches/rrweb@2.0.0-alpha.12.patch, pnpm-lock.yaml
The worker used to process canvas mutations on a background thread is referenced from the `_virtual` directory
Since https://github.com/rrweb-io/rrweb/pull/1309 was included in `rrweb@2.0.0-alpha.12` the contents of the outputted `_virtual` directory has changed. This is what I think is causing canvas mutations not to be captured.
While we wait for https://github.com/rrweb-io/rrweb/pull/1448 (or an alternative) to be merged and released we need to patch the worker output from rollout. I chose to revert to the contents of `rrweb@2.0.0-alpha.11`
|Before|After|
|----|----|
| <img width="678" alt="Screenshot 2024-04-12 at 10 47 38" src="https://github.com/PostHog/posthog-js/assets/6685876/1e10aafd-785a-48b7-a7b1-b7df1cb7af47"> | <img width="695" alt="Screenshot 2024-04-12 at 10 43 54" …
=> chore: patch to fix broken worker

src/autocapture.ts
When autocapturing events on sensitive elements (`input` (except `type="button"` etc.), `textarea` etc.), PostHog currently only allows the capture of the following attributes: `name`, `id`, `class`.
For autocapture events when e.g. a text `input` is edited,  it can be difficult to identify from the event which input has been edited, if it does not have an identifying `name` attribute.
With this change, the `aria-label` attribute is also captured.
=> fix: Allow capturing `aria-label` attribute on sensitive elements

src/posthog-core.ts, src/utils/simple-event-emitter.ts
replaces capture hook with a copy of the event emitter from posthog-js-lite
=> feat: readonly event emitter

src/__tests__/personProcessing.test.ts, src/__tests__/posthog-core.js, src/__tests__/posthog-core.test.ts, src/posthog-core.ts, src/types.ts
Rename process_person config option to person_profiles
Add a more standardized way of handling renames and deprecations of config options
=> feat: Rename process_person config option to person_profiles

README.md
Following the instructions in the docs can get us in a weird state, so I changed them.
See internal thread https://posthog.slack.com/archives/C02GS3N743W/p1713272909176839?thread_ts=1713272170.819489&cid=C02GS3N743W
=> chore: update docs on versioning

src/__tests__/personProcessing.test.ts, src/__tests__/posthog-core.js, src/posthog-core.ts, src/types.ts
Rename $process_person to $process_person_profile
=> feat: Rename $process_person to $process_person_profile

cypress/e2e/capture.cy.ts, playground/nextjs/README.md, playground/nextjs/package.json, playground/nextjs/pages/_app.tsx, playground/nextjs/pages/index.tsx, playground/nextjs/src/CookieBanner.tsx, playground/nextjs/src/posthog.ts, src/__tests__/autocapture.test.ts, src/__tests__/decide.js, src/__tests__/extensions/replay/sessionrecording.test.ts, src/__tests__/helpers/script-utils.ts, src/__tests__/posthog-core.js, src/__tests__/surveys.test.ts, src/autocapture.ts, src/decide.ts, src/extensions/replay/sessionrecording.ts, src/extensions/toolbar.ts, src/posthog-core.ts, src/posthog-surveys.ts
We enabled/ disable recordings due to config changes but not autocapture or surveys
* Refactors the code so that each class is responsible for its own intialisation
* Uses the nextjs example for consent driven dev
=> fix: Reacting to config changes

src/__tests__/autocapture.test.ts
context in https://posthog.slack.com/archives/C044P04L92T/p1712324149123769
a customer reported some call-to-action buttons aren't capturing text correctly. 
the buttons have multiple children and I wanted to check we do handle that correctly, we do, but may as well keep the test to protect the behavoiur
=> chore: add a test

src/__tests__/heatmaps.test.ts, src/heatmaps.ts
We track interactions of the toolbar which can be pretty confusing, especially when you are first setting up and testing with it.
* Check for if the element clicked is or is in the toolbar
* If so ignore it
=> fix: Don't track heatmaps of toolbar

src/heatmaps.ts
Small error in last PR - didn't use the const value leading to a duplicate string
=> chore: Fix duplicate string

src/__tests__/heatmaps.test.ts, src/constants.ts, src/heatmaps.ts, src/posthog-core.ts, src/types.ts
Client side component of https://github.com/PostHog/posthog/pull/21807
* Adds support for turning heatmaps on via server side setting
=> feat: Remotely enable heatmaps via decide

playground/nextjs/src/posthog.ts, src/__tests__/heatmaps.test.ts, src/heatmaps.ts, src/types.ts
Makes the heatmap config value a standard option
=> feat: Move heatmaps out of preview

src/extensions/surveys.tsx
In https://github.com/PostHog/posthog/pull/20321, surveys are rendered using `preact-render-to-string`. This method renders plain HTML, stripping any event listeners. Because of this, some interactions were not working (I had missed this in the initial review - my bad).
- Switch to `Preact.render` for rendering previews
- Some minor adjustments to render the Thank you message
This needs a much bigger cleanup, but annoying to do with the current slow iteration cycle - want to set up a better environment first. But this will get us over the line with https://github.com/PostHog/posthog/pull/20321 
This change should be merged together with https://github.com/PostHog/posthog/pull/20321
https://github.com/PostHog/posthog-js/assets/22996112/d640f9e8-6b8c-4d9d-885f-3f459080d671
=> fix(surveys): use correct render method

src/heatmaps.ts
I wasn't sure if I was missing heatmap data because my local plugin server hadn't caught up or I hadn't started it...
Adds logging to help the future traveller
=> chore: logging on start

src/__tests__/posthog-core.js, src/__tests__/posthog-core.test.ts, src/__tests__/rate-limiter.test.ts, src/posthog-core.ts, src/rate-limiter.ts
If the client rate limits, we send a subsequent event for ingestion warnings but that doesn't help much if you are trying to debug whats going on.
We could save the ingestion warning event but that would be added to the users event total.
_or_ we could add some info about the current rate limit to all events so that it is possible to filter for events where the rate limit was about to kick in.
=> feat: Add rate limit info to events

deprecation.json, package.json, pnpm-lock.yaml, scripts/deprecate-old-versions.mjs
Add a script to deprecate old versions. We can deprecate versions before a certain semver and that are older than a certain number of days!
Very intentionally does not deprecate the current version 🙃 
Runs in `dry-run` mode by default.
I think maybe only @timgl can run this... doesn't look like you can automate as it requires 2fa
n/a
=> chore: Add script to deprecate old versions

src/__tests__/posthog-core.js, src/config.ts, src/posthog-core.ts, src/types.ts
Currently if you disable capture_pageview, there's no way to enable sending pageleave events automatically when the page closes.
Some people would like to do this! e.g. in nextjs you need to manually send pageview events, as this is done in a framework-specific way, but you might still want to send pageleave event when the page closes, and this is not framework-specific so could be done automatically.
To keep backwards compatibility, this is off by default. The new default value for capture_pageleave is `'if_capture_pageview'`.
The only users who would see a difference in behaviour are people who explicitly set:
```
capture_pageview: false
capture_pageleave: true
```
=> feat: Allow sending automatic pageleave with manual pageview

src/extensions/toolbar.ts
Modifying state may break on applications that use it, like Next.js.
Reuses the current history state when calling `replaceState` that removes hash from the URL.
Next.js apps rely on the state object. Calling `replaceState("", ...)` throws making the toolbar unusable.
...
=> fix: don't modify history state when loading toolbar

src/extensions/toolbar.ts, src/posthog-core.ts, src/request.ts, src/utils/index.ts
Possibly fixes https://github.com/PostHog/posthog-js/issues/1079
* Generate the list of available request transports
* Try to use the one requested, falling back to whatever is available
=> feat: Refactor request to make sure we only use available transports

src/posthog-core.ts
Noticed whilst looking at a different PR - I think the request queue _should_ be sending a retriable request but instead is only sending a one off request...
* Fixes it
=> fix: Retriable queued requests

src/__tests__/utils/request-router.test.ts, src/utils/request-router.ts
Convert app.posthog.com to us.posthog.com for ui_host as well
=> fix: Update ui_host if using old app one

src/extensions/surveys.tsx
This PR makes a fix to followup on #1177 where we discovered a bug that we weren't shuffling questions correctly. 
The bug was in the survey rendering where we would repeatedly shuffle questions, causing us to sometimes lose questions when the component re-renders.  This is now fixed by using the `useMemo` react hook to shuffle the questions for a given Survey only once.
=> fix(survey): Fix issue with shuffling questions on every render

src/__tests__/surveys.test.ts, src/extensions/surveys.tsx, src/extensions/surveys/surveys-utils.tsx, src/posthog-surveys-types.ts
The posthog webapp uses the question index as it appears in the survey definition to correlate responses to their questions. 
https://github.com/PostHog/posthog/blob/23a982c0844bfe0dd393e1e5d5d897a983cc7240/frontend/src/scenes/surveys/surveyLogic.tsx#L89
When the questions are shuffled, we end up with values being mis-interpreted by the webapp.
To alleviate this, we will now save the original questionIndex as it appears in the definition and use that if its available when advancing between questions.
...
=> fix(survey): Retain question index if questions are shuffled

src/retry-queue.ts
Fixes a bug in retry-queue which discarded the count of retries, which caused it to retry in a tight-loop forever.
See this post for more details: https://posthog.com/questions/posthog-retries-s-snapshot-request-indefinitely
=> fix: Pass `retriesPerformedSoFar` to keep count of retries

src/__tests__/retry-queue.test.ts, src/retry-queue.ts
Adds a test to cover https://github.com/PostHog/posthog-js/pull/1201
=> fix: Add missing retry info and test

.github/workflows/cd.yml, .github/workflows/library-ci.yml
Auto approvals for JS PRs to PostHog. Tested with hard coded action here https://github.com/PostHog/posthog/pull/22469
=> fix: Add auto approver for JS prs

patches/rrweb@2.0.0-alpha.13.patch, pnpm-lock.yaml
The problem with patches... we don't have typing.
I referenced the wrong variable in [this PR](https://github.com/PostHog/posthog-js/pull/1208) which is causing an issue in production
=> fix: reference canvas not client

src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/sessionrecording.ts
Things used to start undefined, and they do so much less now
As an effect of that, we start session recording with an absent session and window id
This makes [a persistent buffer](https://github.com/PostHog/posthog-js/issues/1099) hard to make since we have no reproducible key
We always have a session manager when we start now, so we can always start with an id
This is mostly tricky in tests, because we have a mock rrweb and then fake around the behavior of snapshots on initialisation
=> fix: do not start recording buffer without id

src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/sessionrecording.ts
* stacked on top of: https://github.com/PostHog/posthog-js/pull/1215
* towards: https://github.com/PostHog/posthog-js/issues/1099
if someone has persistence set to memory only then we don't want to use local storage for replay
as a step towards a persistent queue for replay this moves buffering into an explicit in-memory buffer
clarifying the interface so that we can then add a persistent storage buffer
=> feat: add an explicit in-memory buffer

playground/vite-surveys/src/list.tsx, src/__tests__/extensions/surveys.test.ts, src/__tests__/surveys.test.ts, src/extensions/surveys.tsx, src/extensions/surveys/components/BottomSection.tsx, src/extensions/surveys/components/ConfirmationMessage.tsx, src/extensions/surveys/components/QuestionHeader.tsx, src/extensions/surveys/components/QuestionTypes.tsx, src/extensions/surveys/surveys-utils.tsx, src/posthog-surveys-types.ts
_Needs to go in with https://github.com/PostHog/posthog/pull/22617_
- Remove any previously attached `<style>` tags - previously, a new tag was attached on any re-render, bloating the HTML and leading to some CSS issues
- Simplify local state for displaying/hiding the popup and showing questions vs confirmation
- Make sure the popup stays in place when left/center/right properties are changed
- Clean up SurveyContext: remove some unused fields of the state + add relevant fields
- Render `<ConfirmationMessage />` in a single code path and outside `<Questions />`
- Simplify the factory method for returning a survey question for rendering (`questionTypeMap` -> `getQuestionComponent`)
- Rename `previewQuestionIndex` to `previewPageIndex`, since the indexing also applies to the confirmation …
=> chore(surveys): refactor survey popup (vol. 1)

src/extensions/replay/sessionrecording.ts
stop the full snapshot timer when idle
it gets restarted on return
=> fix: no full snapshot while idle

src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/sessionrecording.ts
session replay buffer can contain a lot of data
so, when the browser goes idle
we should proactively flush it
=> fix: flush on idle

package.json, pnpm-lock.yaml, src/extensions/sentry-integration.ts, src/posthog-core.ts
Adds support for the new v8 integration format ([see issue](https://posthog.com/questions/sentry-v8-class-based-integrations-deprecated))
We now have two methods, with the lower case one being the function based and upper case being classed based. I'll have a follow up PR for updated docs
=> feat: Updated v8 sentry integration

src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/sessionrecording.ts
This stops estimation of size of an rrweb event containing an object with a circular reference from exploding
It doesn't edit the actual emitted data in case that's necessary for playback 
see https://posthog.com/questions/uncaught-error
=> fix: circular refs shouldn't explode capture

src/__tests__/personProcessing.test.ts, src/__tests__/posthog-core.js, src/constants.ts, src/posthog-core.ts, src/posthog-persistence.ts, src/utils/event-utils.ts
Some context: when the person profiles mode is set to identified_only, we want to be able to eventually create the user with the real initial props. We do this by storing them in persistence.
The old way of doing this was to store the props themselves, for a limited subset of props. The problem with this is that we derive a lot of props from the same data, with quite a bit of overlap, and there's some size pressure to keep it small as this data is stored in the cookie which can store a max of 4kB. This meant that we didn't store everything that could be useful.
This PR changes this, and now stores just the initial URL and initial referrer, and derives everything else from those later. This means that we now send everything we sent before, plus additionally we send: 
* initial_host
* …
=> feat(personless-events): set_once more initial properties accurately when a person is created

src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/sessionrecording.ts
(particularly in the mobile wireframe work) we're learning that rrweb playback is very intolerant of missing data
we drop events when idle since we don't want to extend active time
but we sometimes get unexpected playback artefacts
let's try being more permissive when idle
=> fix: less strict idle event dropping

src/__tests__/surveys.test.ts, src/posthog-surveys-types.ts, src/posthog-surveys.ts
Part of completing [Post/posthog/#22281](https://github.com/PostHog/posthog/issues/22281)
1. Added 3 new types to posthog-surveys-types.ts ('not_regex', 'not_exact', 'not_icontains')
2. Updates surveyUrlValidationMap to handle new types
3. New tests for exclusion conditions
related to [THIS PR](https://github.com/PostHog/posthog/pull/22653)
...
I keep running into issues trying to get all the pieces for local development to play nice together. I haven't been able to see this in action for myself. No big changes here but I'd still like to try and break things if I can. I wanted to get feedback while I troubleshoot my issues.
=> feat: allow not operators in survey url targeting

src/__tests__/extensions/replay/rrweb-plugins/patch.test.ts, src/extensions/replay/rrweb-plugins/patch.ts, src/loader-recorder.ts
While investigating a customer issue (See: https://posthog.slack.com/archives/C074A08LP1B/p1718291948667569) I saw the patch function being called more than once for each wrapped thing
This is unexpected - but I guess clearly possible 🙈 
So, if `initNetworkObserver` is requested and it is already init'd, do nothing, the original caller is responsible
(we don't catch this in patch since we might want to patch things twice. e.g. trace header additionally wraps patch)
=> fix: only wrap once when patching

src/__tests__/sessionid.ts, src/__tests__/test-uuid.test.ts, src/sessionid.ts, src/types.ts, src/uuidv7.ts
See https://posthog.slack.com/archives/C05LJK1N3CP/p1718670024960049?thread_ts=1718248453.056799&cid=C05LJK1N3CP for motivation
* Add an option to bootstrap the session id
* Added a function to convert a v7 uuid to a timestamp
=> feat: Allow bootstrapping session id

src/__tests__/consent.test.ts, src/posthog-core.ts
[Ticket](https://posthoghelp.zendesk.com/agent/tickets/14282)
The consent changes I made removed the ability to ignore the opt in event which wasn't intended.
Adds an option to skip using the existing properties. This is slightly breaking but pretty certain it wasn't used this way before anyways
=> fix: Allow no capture of $opt_in event

src/__tests__/surveys.test.ts, src/extensions/surveys.tsx, src/posthog-core.ts, src/posthog-surveys-types.ts, src/posthog-surveys.ts
Naming this branching type `confirmation_message` is confusing because not every survey ends with a confirmation message.
`posthog` changes to follow.
=> fix(surveys branching): rename confirmation_message -> end

playground/nextjs/pages/index.tsx, src/__tests__/autocapture.test.ts, src/autocapture.ts
This PR creates a new property, which is the href when an external link is clicked. External is defined as a different host, and the intention here is for people to measure things like which landing pages lead to which external link clicks.
(I was basically nerd-sniped into adding this by some customer feedback)
We already capture this, but it's very buried inside the $element array, and not always at the same place (not always $elements.0.attr_href), so its hard to add to the sessions MV.
Tested this manually by adding an external link to the nextjs playground, and confirming that I could see the event and property.
=> feat(web-analytics): Add property for autocapture link click

src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/sessionrecording.ts
There have been a bunch of preparatory changes for buffer changes, and a bunch of bug fixes recently in the recording file
But things seem less stable than when we started
This unwinds those changes
And only keeps that we make sure not to schedule full snapshots while we're idle
=> fix: unwind recent changes things seem less stable

.github/workflows/bundled-size.yaml, .github/workflows/cd.yml, .github/workflows/label-version-bump.yml, .github/workflows/library-ci.yml, .github/workflows/react.yml, .github/workflows/ssr-es-check.yml, .github/workflows/testcafe.yml, src/extensions/sentry-integration.ts
we were using 2
it gives warnings about node 16 when running
latest is 4
lets use 4
=> chore: update pnpm action setup worfklow version

patches/rrweb@2.0.0-alpha.13.patch, pnpm-lock.yaml
Use includes to check substring. `contains` is throwing a weird error as reported in https://github.com/PostHog/posthog-js/pull/1272#issuecomment-2191304203
|Before|After|
|----|----|
| ![Screenshot 2024-06-26 at 11 20 36](https://github.com/PostHog/posthog-js/assets/6685876/462a4cce-ab74-4b0b-b89a-491ee5302d49) | ![Screenshot 2024-06-26 at 11 20 42](https://github.com/PostHog/posthog-js/assets/6685876/43401df4-3731-4bd4-bcf3-c066bee75ca5) |
|Before|After|
|----|----|
| ![Screenshot 2024-06-26 at 11 20 16](https://github.com/PostHog/posthog-js/assets/6685876/ccf2438e-82d5-4463-a545-88ed01f48299) | ![Screenshot 2024-06-26 at 11 21 09](https://github.com/PostHog/posthog-js/assets/6685876/0bfd81c3-ee75-40c6-83d9-7f5ae8edfa04) |
=> fix: use includes over contains

src/posthog-core.ts
see https://posthog.sentry.io/issues/5544450836/?query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=2
it's all one customer but we should warn in this scenario
=> feat: warn when distinct id invalid for replay

cypress/e2e/error-tracking.cy.ts, src/extensions/replay/sessionrecording.ts
We currently take a full snapshot when
(in order of increasing frequency)
* rrweb starts
* when the session id or window id changes
* when returning from idle
* on a timer
* when we see a $pageview event
we also infrequently see reports that playback is inconsistent around $pageviews
let's not take that speculative snapshot
=> fix: only take scheduled full snapshots

src/extensions/surveys/components/QuestionTypes.tsx, src/extensions/surveys/surveys-utils.tsx
Closes issues 1,3, and 4 from this ticket https://github.com/PostHog/posthog/issues/20851.
Fixing 4 requires some changes to posthog, too: https://github.com/PostHog/posthog/pull/23460
Issue 2 I wasn't able to reproduce; I need more context from @annikaschmid and/or @jurajmajerik 
Quick note on browser compatibility: I'm using the `:has` pseudo-selector for determining whether to apply margins or not.  Per [caniuse](https://caniuse.com/css-has), this has been supported in all major browsers since 2023, but is this a risky change still?
...
- I manually tested this for each survey type
=> fix(surveys): polishing the popup survey UI

cypress/e2e/error-tracking.cy.ts, cypress/support/e2e.ts, cypress/support/setup.ts
I can't consistently make this happen locally
But I did once notice that I don't always get
```
possible EventEmitter memory leak detected
```
i only noticed after the fact but if we didn't register an event listener then the tests wouldn't pass 
i've checked console logs in prod for our team and don't see this so it's safe to patch in tests (🙈)
=> chore: fix error tests listener registration

src/extensions/surveys/components/ConfirmationMessage.tsx, src/posthog-surveys-types.ts
Ships with https://github.com/PostHog/posthog/pull/23501
Not customizable
Manually tested it, looks solid.  Low-risk (it's an optional field)/easy change, just needed to make sure that the types lined up.
=> feat(surveys): added close button text customization feature

src/__tests__/extensions/replay/config.test.ts, src/types.ts
see https://posthog.com/questions/hiding-specific-query-parameters-in-session-replay-waterfall-beta-view
allows caller to edit the request, properties being readonly was an unintended consequence of inheriting from PerformanceEntry and never mutating it ourselves
=> fix: capture network recording type

src/__tests__/autocapture.test.ts, src/autocapture.ts, src/extensions/surveys/action-matcher.test.ts, src/extensions/surveys/action-matcher.ts, src/posthog-surveys-types.ts
_Broken out of #1292 into its own PR for easier reviewing and merging_
This PR allows us to match user activities performed in the browser to any known actions.
1. Matching person properties in Actions,  when matching surveys. We will not implement this as we don't want to download person properties on the client for surveys.
2. Matching event properties in Actions, when matching surveys. We could do this in a follow-up PR because the event properties are available on the client-side.
Here are the set of changes I needed to make to implement action matching in posthog-js
1. Autocapture can now register a set of html element selectors. 
4. These html selectors, are checked against the target element **that** was captured
5. If there is a match, those element selectors are sent along as …
=> feat(Surveys): Add ActionMatcher to match CaptureResult to any known actions

src/__tests__/autocapture.test.ts, src/__tests__/surveys.test.ts, src/__tests__/utils/survey-event-receiver.test.ts, src/autocapture.ts, src/extensions/surveys/action-matcher.test.ts, src/extensions/surveys/action-matcher.ts, src/extensions/surveys/components/ConfirmationMessage.tsx, src/posthog-surveys-types.ts, src/posthog-surveys.ts, src/utils/survey-event-receiver.ts
_Broken out of #1292 into its own PR for easier reviewing and merging_
This PR allows us to activate surveys if any actions they're configured with are performed in the browser.
1. Instead of maintaining a map of Survey-ID to its actions or events, we maintain a map of Action/Event to the surveys that are activated by it.
1. We now look for, and register any surveys that are activated by events with the `ActionMatcher`.
2. Changed `on` to be `onEvent` and added a new `onAction` event handler.
3. `onAction` listens on the `actionCaptured` event in `ActionMatcher` described below.
``` mermaid
flowchart TD
A[User clicks button] -->|AutoCapture| B(Analyze element)
B --> |Element matches known selector|C(Set $element_selectors property)
C -->D[Capture Action]
B --> |Element does not match …
```
=> feat(Surveys): Activate surveys based on actions

src/entrypoints/array.full.ts
I missed this when adding web vitals
If you have web vitals enabled and used array full we'd still load an external script...
well, not any more
=> fix: add web vitals to array full

src/posthog-core.ts
see https://github.com/PostHog/posthog-js/issues/1193
we can't go back in time to make that right... but we can at least maybe help the future traveller
=> fix: warn when on xhr error used

src/__tests__/autocapture.test.ts, src/autocapture-utils.ts, src/autocapture.ts, src/types.ts
see https://posthog.slack.com/archives/C075D3C5HST/p1720808391615839
and https://posthog.com/questions/url-allowlist-for-exclude
@corywatilo made a totally reasonable assumption about how this works... and it's easy to make it work that way
This PR extends autocapture config so you can pass a url_ignorelist instead of (or as well as) a url_allowlist
=> feat: add url_ignorelist for autocapture config

src/__tests__/extensions/replay/sessionrecording-utils.test.ts, src/extensions/replay/sessionrecording-utils.ts, src/extensions/replay/sessionrecording.ts
when we see very large mesages sometimes they are many megabytes of an array of relatvely small items
we can split those arrays down into multiple captured events we are splitting when over _seven megabytes_ so we're still letting this generate pretty large events
this shouldn't amplify the number of events _too_ much
and anyway we're sending this data to capture already just in one large expensive packet
see https://github.com/PostHog/posthog/issues/23703
=> feat: split large replay buffers before sending

src/__tests__/extensions/web-vitals.test.ts, src/extensions/web-vitals/index.ts, src/types.ts
We see web vitals captured with values many times greater than one hour.
This is 99.999999% definitely a bug in the web vitals library or browsers.
Certainly it's not useful to know you have outliers where someone's FCP was 2 days.
Let's limit ourselves to a max of one hour, but let people override that if they really, really want to
=> fix: ignore ridonculously large web vitals values

src/__tests__/surveys.test.ts, src/entrypoints/surveys.ts, src/posthog-surveys.ts
we need to keep the bundle as small as possible, it's already ~3x bigger than when people first start complaining about the size
https://github.com/PostHog/posthog-js/pull/1281/ is in merge hell because we abandoned it
this is another attempt to avoid everyone downloading preact, it reduces bundle size by 6%
=> fix: don't load preact until you have to

src/__tests__/posthog-core.test.ts, src/posthog-persistence.ts
As part of the personless event changes, we accidentally introduced a bug where the referrer could change mid-session. This shouldn't happen, and led to some annoying situation where e.g. if a payments workflow navigated people to checkout.stripe.com and then back to the original site, the referrer would switch to stripe, which meant that any events after that couldn't be attributed to the original referrer.
This fixes that bug, and adds some tests.
(P.S. I realised how this was broken when working on https://github.com/PostHog/posthog-js/pull/1313, IMO with this fix merged that PR becomes a lot less useful)
=> fix: Fix the referrer changing mid-session

.gitignore, rollup.config.js
When we last changed the rollup bundling - I think - we started writing a bundle file for each entrypoint but all with the same name
I think I'm the only person that uses this but I do use it, so this changes to output a file for every bundle with its own name.
We can use this primarily to see what is causing array.js to grow but can also then dig into each of the bundles if we need to
=> chore: fix the rollup bundle visualiser output

src/extensions/surveys/components/QuestionTypes.tsx, src/posthog-surveys-types.ts
New survey behavior
No backend changes needed, the response is just a number under the hood.  Just needed some UI love to support this.
Closes https://github.com/PostHog/posthog/issues/23922
Ships with associated PostHog app changes here: https://github.com/PostHog/posthog/pull/23956
=> feat(surveys): add support for a 7 point likert scale

functional_tests/feature-flags.test.ts, jest.config.js, package.json, pnpm-lock.yaml, src/__tests__/decide.js, src/__tests__/decide.ts, src/__tests__/featureflags.js, src/__tests__/featureflags.ts, src/__tests__/posthog-core.js, src/__tests__/posthog-core.ts
This moves the final files using given to not using given
Which means they can be converted to typescript
I've refactored a little but tried to keep the changes pretty minimal just to get given removed and the tests moved to TS
=> chore: finally remove given

patches/rrweb@2.0.0-alpha.13.patch, pnpm-lock.yaml
Some frameworks override the second argument of `Array.from`. A customer reported an issue where their stylesheets were not correctly parsed because of this. Changing to use `Array.from` with one argument followed by `.map` with the applied function 
This has been fixed in the `alpha-14` release of rrweb: https://github.com/rrweb-io/rrweb/pull/1464. We're currently on `alpha-13` and are blocked on upgrading to `alpha-16` because of some typing issues.
We could upgrade to `alpha-14` but the effort of reapplying all our old patches probably isn't worth it. It's much easier to just add this one
=> fix: Array.from override

src/__tests__/utils/survey-event-receiver.test.ts, src/utils/survey-event-receiver.ts
This is a bug fix for the scenario where we weren't removing a survey from the activated surveys list once the survey is shown.
=> fix(surveys): Accept eventPayload in onEvent handler

src/posthog-core.ts, src/posthog-persistence.ts
I'm trying to help a customer debug a problem with their setup, and it's hard to do remotely without access to their source code. I figured this might help me.
~Tests for new code (see [advice on the tests we use](https://github.com/PostHog/posthog-js#tiers-of-testing))~ n/a as long as existing tests pass
=> feat: Add debug logic for set_config

src/posthog-persistence.ts, src/storage.ts, src/types.ts
I'm trying to debug an issue with cross-domain cookies, and so thought this would be helpful. It'd help me confirm a theory I have.
=> feat: Add debug messages around storage

src/__tests__/featureflags.ts, src/posthog-featureflags.ts
We've supported manually overriding feature flag values in the client for years (and our toolbar [natively supports it](https://posthog.com/docs/toolbar/override-feature-flags)), but since this override doesn't persist to the backend, we've historically always just treated this feature as a debug feature only.  However, there's been a influx of support requests (on both Twitter and in our support inbox) that are asking about this feature, and one user explicitly mentioned that the feature [would be perfect for his use case if it weren't for the debug warning and logs](https://posthoghelp.zendesk.com/agent/tickets/15724).  I started a [discussion about this in Slack](https://posthog.slack.com/archives/C034XD440RK/p1722281920032039), and if we decide that it's safe to give users the ability …
=> feat(flags): give users the ability to suppress override warning logs, if desired

src/posthog-core.ts, src/posthog-persistence.ts
I'm debugging things for this customer: https://posthog.slack.com/archives/C05LJK1N3CP/p1720719062387739
I've established that the cross domain cookie is being successfully read from on the second site, but that we are ignoring the values. I'm hoping this extra debugging will help
=> feat: Add debug logging for the initial props that posthog was started with

playground/nextjs/.gitignore, playground/nextjs/README.md, playground/nextjs/package.json, playground/nextjs/pages/index.tsx
I'm trying to debug some logic around cross-subdomain tracking, and figure out how to do this while running on localhost. I thought I would add some docs for other people (or my future self) who want to try this
=> chore: Add instructions for cross subdomain development

src/extensions/surveys/surveys-utils.tsx
Issue identified here: https://posthog.slack.com/archives/C074A08LP1B/p1722845257000019?thread_ts=1722508627.577449&cid=C074A08LP1B
This issue came from me trying to fix the textarea size for free response surveys.  My fix made the survey preview rendering work correctly, but it was too wide for the popover rendering (which is more important; that's the thing the end users see!)
Before: 
and
I fixed this to add an explicit border box into the textarea.  In the preview, it was inheriting a border box already, so this wasn't a problem, but since the rendered survey has a different DOM tree, with different stylings, it didn't work for end users.
This fix should work for both.
After (on page):
After (in preview section):
=> fix(surveys): textarea border box was being set in the preview but not in the surveys rendered on user websites

src/extensions/surveys/components/BottomSection.tsx, src/extensions/surveys/surveys-utils.tsx, src/posthog-surveys-types.ts
[Hospitable asked for this](https://posthog.slack.com/archives/C074A08LP1B/p1722508627577449), and it was super easy to do.  Feels worth it.
Ships with the UI controls here: https://github.com/PostHog/posthog/pull/24170
=> feat(surveys): added a customizable submit button text color

src/posthog-core.ts, src/storage.ts
Add the reset logging to help debug things for this customer: https://posthog.slack.com/archives/C05LJK1N3CP/p1722882994008479?thread_ts=1720719062.387739&cid=C05LJK1N3CP
Remove the persistence logging because it's a bit noisy: https://posthog.slack.com/archives/C0113360FFV/p1722615914056199
=> feat: Remove storage logging and add reset logging

src/extensions/surveys/components/PostHogLogo.tsx, src/extensions/surveys/surveys-utils.tsx
We accidentally reverted the link text styling [with this change](https://github.com/PostHog/posthog-js/pull/1324/files#diff-84b57d5feee425d7e792147602981722b4b81e77179589037baa80f219d421daL8-L15), and it led to a link [that looked bad](https://posthog.slack.com/archives/C034XD440RK/p1722876370834339)
this change moves the styling into the CSS itself (rather than as part of a component), and that seemed to fix it
app
popup
=> fix(surveys): style the link button with black text

src/__tests__/page-view.test.ts, src/extensions/segment-integration.ts, src/page-view.ts, src/posthog-core.ts
Add prev pageview duration, for a customer, inspired by this slack thread https://posthog.slack.com/archives/C05LJK1N3CP/p1723144788366199
We already do have some logic for measuring the time between the same event (that gets stored in storage rather than in memory), but that doesn't add e.g. pageview duration to a pageleave event, and doesn't match up with the other prev_pageview props like prev_pageview_pathname, which the paths view on web analytics already uses.
=> feat: Add prev pageview duration

src/posthog-core.ts
this header causes lots of preflight requests so probably isn't worth it in the end. Not in use yet so no risk to remove (just added in https://github.com/PostHog/posthog-js/pull/1347)
=> revert: remove x-posthog-token header

functional_tests/mock-server.ts, src/posthog-core.ts
it's weird that we do our first requests before the decide response with base64 "compression", as
1. we've supported gzip for literally years, so there's basically zero risk of somehow hitting an endpoint that doesn't support it
2. base64 is not compression, it increases the payload size compared to if we did nothing at all
3. rust capture does not support base64
=> feat: default to gzip compression instead of base64

src/extensions/exception-autocapture/index.ts, src/extensions/web-vitals/index.ts
fixes: #1346 
OP correctly identifies that two scripts are passing the fully resolved endpoint into `loadScript` which then calls `endpointFor`
Calling `endpointFor` twice is not (always) safe
=> fix: endpoint for is already called inside loadscript

src/entrypoints/exception-autocapture.ts
We add error functions to window even when it is undefined... let's copy the other entrypoints and check first
(should) fixes #1349
=> fix: only add to window when it exists

src/entrypoints/recorder.ts
When wrapping fetch we take a url, init pair and create a request object
When we pass on and call the original fetch method we pass the request object. this is _technically_ equivalent to the original but not literally equivalent which can cause problems if there are further wrappers on fetch
see: https://github.com/PostHog/posthog-js/issues/1326
We actively don't want to alter the fetch details so it should be 100% safe to use the original args when calling the original fetch 🤷
=> fix: pass original fetch args along

src/entrypoints/recorder.ts
Reverts PostHog/posthog-js#1351
we've seen multiple reports of fetch wrapping causing errors, it would be amazing if it wasn't this change causing it.
it's safe to revert if it's not this change and important to revert if it is...
=> revert: "fix: pass original fetch args along"

src/extensions/replay/sessionrecording.ts
fixes: https://github.com/PostHog/posthog-js/issues/1378
instead of registering these event listeners in the constructor we should register when starting and unregister them when stopping
tested by running locally and validating that i still see browser hidden events
=> fix: event listeners should obey start and stop

pnpm-lock.yaml, src/__tests__/extensions/exception-autocapture/exception-observer.test.ts, src/extensions/exception-autocapture/index.ts, src/extensions/sentry-integration.ts
Fixes https://github.com/PostHog/posthog-js/issues/1389
I'm not sure how best to add tests for the sentry integration, any prior stuff here?
...
=> fix(errors): Build endpoint for sentry integration & exception observer correctly

cypress/e2e/session-recording.cy.ts, playground/cypress/index.html
part of responding to https://github.com/PostHog/posthog/issues/24471 due to the unexpected consequences of https://github.com/PostHog/posthog-js/pull/1351
The Cypress tests already covered the expected behaviour of the wrapper, but it wasn't clear that was what was happening.
This refactors the test and introduces much clearer assertions
I have checked that the test passes even with the change from https://github.com/PostHog/posthog-js/pull/1351
I believe the issue is if another fetch wrapper reads the body of the request (and potentially other interactions with the request) but will follow-up to this PR with a test to cover that scenario
=> chore: clarify that tests are exercising our fetch wrapper

cypress/e2e/session-recording.cy.ts, src/entrypoints/recorder.ts, src/extensions/replay/rrweb-plugins/patch.ts
part of responding to https://github.com/PostHog/posthog/issues/24471 due to the unexpected consequences of https://github.com/PostHog/posthog-js/pull/1351
it is _very_ hard to test for all unexpected consequences of changes to code 🙈 
but we do at least _now_ know for sure that that we cannot rely on request/response objects being readable and that we should not read them and then pass them on
Here's the test failing in CI and showing we would have avoided all of the painful impact for folk
```
1 failing
1) Session recording
network capture - when fetch wrapper is not badly behaved
it sends network payloads:
TypeError: The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.
> Failed to execute 'fetch' on 'Window': Cannot …
```
=> fix: network capture tests should fail if we exhaust the body

src/entrypoints/recorder.ts
v1.160.2 introduced much more robust network capture... too robust because now we can capture requests without their URL. no bueno
let's always capture the URL so that if there is no performance entry we at least have that url
(for the benefit of the future traveller... the requests captured without a URL are requests that we previously couldn't capture at all)
=> fix: captured network requests must always have name property

src/posthog-surveys.ts
relates to #1344
we're checking the presence of a method on something that _could_ be undefined
but we don't correctly type all the lazy load stuff, so TS doesn't complain
this at least safely checks the presence and will warn instead 
we're likely calling the method too early (before it has had a chance to be added to the window) this might even be safe, so we definitely shouldn't throw
=> fix: warn on unavailable lazy load not throw

src/entrypoints/web-vitals.ts
In #1401 we moved the web vitals callbacks onto an object on the window instead of placing them directly on the window... there are more and more extensions being added on to the window - and that is no bueno 
but, existing clients installed with npm may now request web vitals and look for it directly on the window but it isn't there any more - also no bueno
we can't fix this in the main bundle since its only old clients and they won't have that code, so it has to be fixed in the entrypoint file - which is what generates the web vitals file the old clients are lazily loading
=> fix: some clients need web vitals directly on window

cypress/e2e/session-recording.cy.ts, src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/sessionrecording.ts, src/posthog-core.ts
Taking small steps to reorganise this.
First step is to increase the safety of calling start and stop multiple times
I have seen recordings with a surprising number of apparently duplicate custom pageview events
We _always_ register a pageview callback when starting, instead of registering one when we don't have one
So, this:
* changes `_addCaptureHook` to return the unsubscribe function
* calls the unsubscribe when stopping
* and only adds a listener if we don't already have one
=> fix: manage capture pageview hook lifecycle

src/__tests__/request.test.ts, src/request.ts
we set keepalive to true for any request that is a POST
the fetch spec at https://fetch.spec.whatwg.org/#http-network-or-cache-fetch says
> If contentLength is non-null and httpRequest’s [keepalive](https://fetch.spec.whatwg.org/#request-keepalive-flag) is true, then:
> If the sum of contentLength and inflightKeepaliveBytes is greater than 64 kibibytes, then return a [network error](https://fetch.spec.whatwg.org/#concept-network-error).
read more at e.g. https://javascript.info/fetch-api#:~:text=But%20the%20keepalive%20option%20tells,for%20keepalive%20requests%20is%2064KB.
it is likely that a replay payload would be >64kb compressed
not all browsers obey this spec equally (of course) so it won't always fail, so it's not broken consistently enough to stand out.
but locally I can see …
=> fix: no keep alive for large payloads

src/__tests__/web-experiments.test.ts
I came to my PR and couldn't publish locally because there's a test file outside of the __tests__ folder
i'm too lazy to figure out why we can't support test files in `src` and only `in `src/__tests__`
so i moved it
=> chore: move test file into __tests__

src/entrypoints/recorder.ts
In the cases where we capture a network request even though we could not get information from the performance observer, we are not capturing initiator type - even though we know it
=> fix: when capturing without performance entry we can capture manual initiator type

src/__tests__/surveys.test.ts, src/posthog-surveys.ts
A [user reported](https://posthoghelp.zendesk.com/agent/tickets/18314) that our 7-point likert scales didn't support branching logic in the PostHog UI, which is good, because `posthog-js` didn't support them either and would've thrown a runtime error if users tried it.
This change supports handling 7-point scales for our branching logic.  Will ship with the [PostHog UI changes](https://github.com/PostHog/posthog/pull/25059), but this change should go in first so that we don't have users hitting runtime errors.
Demo of it all working: https://www.loom.com/share/e22de74e2bea4b7cb66fe34343e68916
=> fix(surveys): 7-point likert scale didn't work with branching logic

.github/workflows/cd.yml, package.json
We run tests when publishing that assume the lib was built...
So this should fix it
=> chore: build when publishing

src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/sessionrecording.ts, src/types.ts
We want to compress replay payloads since they're sometimes massive and very compressible
We do compress the entire payload when it is travelling over the network and when in storage, but at points in processing it is not compressed and we can leave some data compressed to make life easier on our infra
But blob ingestion needs to read some metadata from some events so we don't want to just compress everything
So, we now support posthog-js partially compressing selected payloads 
This only compresses when it is enabled so we can test this ourselves to see what the what
pairs with https://github.com/PostHog/posthog/pull/25183
=> feat: compress replay data

src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/sessionrecording.ts, src/types.ts
Partial compression of large rrweb events will make them more reliably ingestable
We've had this on for days now, and some users have tested it
Let's default it on
---
Clicked around in PH app and saved ~1MB in 2 minutes of recording
=> feat: default replay partial compression on

patches/rrweb@2.0.0-alpha.13.patch, playground/nextjs/package.json, playground/nextjs/pages/replay-examples/media.tsx, playground/nextjs/pnpm-lock.yaml, pnpm-lock.yaml
Follow on from problem mentioned in https://github.com/PostHog/posthog/pull/25174#issuecomment-2372203360
When testing locally by adding the `hls-src` attribute to an exported recording I hadn't considered that _actual_ data would add a `src` attribute to the video, which is picked up as a mutation.
This local URL (something akin to `blob:http://localhost:3000/4200b9dc-71b1-42f9-a753-486f93222f0a`) then overrides the `src` that we need to write during the plugin playback.
Rather than trying to detect the insertion of the src attribute using the `handler` and skip it (not sure this is possible with plugins) we should be able to ignore `src` attributes on videos that point to local files e.g. HLS videos
=> fix: skip addition of `src` attribute for HLS videos

src/extensions/replay/sessionrecording-utils.ts, src/extensions/replay/sessionrecording.ts
We shouldn't be capturing auto posthog errors unless the integration is on... will remove this from replay for now
=> fix: Remove posthog error capture from replay

playground/nextjs/pages/index.tsx, playground/nextjs/src/posthog.ts, src/__tests__/web-experiments.test.ts, src/web-experiments-types.ts, src/web-experiments.ts
1. Replace references to `className` with `css` which assigns the value of this field to the `style` attribute of an HTML element. 
2. Introduce the ability to `preview` an Experiment variant in the browser without deploying the experiment. 
3. Do not render web experiments if the viewer is a bot. 
4. Emit the $web_experiment_applied event so we know if the visual changes actually got applied to a page.
=> feat(web experiments): Emit web_experiment_applied event and do not render experiments for bots

cypress/e2e/opting-out.cy.ts, cypress/e2e/session-recording.cy.ts, cypress/support/e2e.ts, cypress/support/setup.ts
It always bothered me when I copy-pastied a new script into the cypress setup
well, no more
=> chore: refactor some cypress setup

src/extensions/exception-autocapture/error-conversion.ts, src/extensions/exception-autocapture/stack-trace.ts
Pulled in relevant changes to exception autocapture since we first wrote it 14 months ago. No functional changes on our end, just adding some bug fixes etc
=> chore: improve exception autocapture

src/extensions/replay/sessionrecording.ts
When upgrading rrweb in https://github.com/PostHog/posthog-js/pull/1276 we had some [failing tests on IE11](https://github.com/PostHog/posthog-js/actions/runs/11342401043/job/31542713953?pr=1276):
```
TypeError: Object doesn't support property or method 'from'
```
This is because the `Array.from` method is [not supported on IE11](https://caniuse.com/?search=array%20from) and it seems like rrweb internals have changed such that it is now called as part of our tests when upgrading.
Proposal is to remove it in this PR and then upgrade rrweb in the separate PR linked
=> chore: skip if Array.from is missing

src/__tests__/extensions/web-vitals.test.ts, src/extensions/web-vitals/index.ts, src/types.ts
We delay capturing web vitals metrics to try and avoid charging too much for collection
But this might be leading some sites to missing the metrics
Let's reduce that timeout and make it configurable so we can test it
=> fix: web vitals delayed capture

src/__tests__/personProcessing.test.ts, src/utils/event-utils.ts
Send `null` for all the campaign params that are not set, rather than leaving them unset and potentially overridden later. Fixes https://github.com/PostHog/posthog/issues/7710
I looked at doing this during ingestion, these PRs https://github.com/PostHog/posthog/pull/25132 https://github.com/PostHog/posthog/pull/25135 do this but it seems like we don't want to touch person processing code too much this quarter
=> feat(web-analytics): Store nulls for unset campaign params

src/__tests__/personProcessing.test.ts, src/__tests__/posthog-core.test.ts, src/__tests__/posthog-core.ts, src/posthog-core.ts, src/types.ts
> [!warning]
> This should only be merged after we support the field response from /decide.
We want to make the `person_profiles: identified_only` config the default for everyone. It will save everyone money - even if they don't change their config - and is better for our customers and our pipeline. 
Instead of just pushing out a change to posthog-js for this, we want to be able to control the behavior and roll it out slowly, just in case there are any problems. 
So, this PR changes the default, but also listens to a field from decide that will say if we should be defaulting people into `identified_only`, or using the old default `always`. If someone has set their config manually, then we will continue using that setting.
=> feat: swap the default to identified_only

src/extensions/surveys/components/QuestionHeader.tsx
Resolves https://github.com/PostHog/posthog/issues/25594
The Cancel button on a survey right now attaches the click handler to the tiny `X` in the close button. 
This PR makes the entire Circle and the X inside it clickable.
=> feat(surveys): Make entire cancel button area clickable

src/entrypoints/recorder.ts
i realised that we have some very specific imports for the recorder which TS doesn't like, and in the PR that introduced them (#526) we added eslint comments to swallow them
that seems unnecessary and brittle
and may relate to https://github.com/PostHog/posthog-js/pull/1276
=> fix: no need to swallow import errors

src/__tests__/sessionid.test.ts, src/sessionid.ts
When you check the session id in posthog you get a bunch of useful information but not the last activity timestamp.
While working on an example of solving a problem in https://posthog.com/questions/post-to-slack-on-new-replay-in-playlist I had to reach into persistence manually to make it work.
Let's expose the useful information, since it's useful
=> fix: expose the last activity timestamp in session id check result

src/__tests__/extensions/replay/sessionrecording.test.ts, src/__tests__/utils/number-utils.test.ts, src/extensions/replay/sessionrecording.ts, src/page-view.ts, src/sessionid.ts, src/types.ts, src/utils/index.ts, src/utils/number-utils.ts
A user wants to be able to dynamically configure canvas recording... so, allow local config
=> fix: allow canvas local config

src/extensions/exception-autocapture/stack-trace.ts
We need to know what language an individual frame is so that we can avoid an untagged enum switching as part of the Rust service.
For now this assumes all stacks in the JS SDK are `javascript`
=> chore: set platform on stack frame

src/__tests__/surveys.test.ts, src/extensions/surveys/surveys-utils.tsx, src/posthog-core.ts, src/posthog-surveys.ts
We found through a customer issue that calling `posthog.reset()` doesn't remove the tracking properties added by PostHog Surveys from local storage. This PR adds a `reset` method to posthog surveys and calls it from posthog-core, whenever `posthog.reset()` is called.
=> fix(surveys): Reset Survey storage after posthog.reset is called

src/__tests__/utils/number-utils.test.ts, src/utils/number-utils.ts
immediately after #1496 
i realised that in moving to the utility function i'd missed a little bit of correctness that could creep in over time
using min seems safest if range min and max don't make sense
=> fix: careful now

src/__tests__/utils/external-scripts-loader.test.ts, src/entrypoints/external-scripts-loader.ts
Changed the URL to use `t=<num>` as query param instead of empty/undefined param name (`v=161.1&=<num>`).
We use posthog in a nextjs application and use nextjs's rewrites as a proxy for better tracking. We noticed that the toolbar does not work on our site. when checking the logs we noticed that the rewrites did not work for the toolbar:
```
code: 'ERR_INVALID_URL',
input: 'https__ESC_COLON_//eu-assets.i.posthog.com/static/__ESC_COLON_path*'
```
But the `web-vitals.js` loaded without a problem...
Further investigation lead to the empty query param for the `toolbar.js` rotating token to bust  the cdn cache.
`?v=1.166.1?&=1728316200000`
The current stable version of next.js (`14.2.14`) has a "bug" that can't handle empty query params correctly in rewrites. The most recent canary version of …
=> fix: empty query param when calling external dependency toolbar.js

src/request.ts
follow-up to https://github.com/PostHog/posthog-js/pull/1416
I still sometimes see TypeError: Failed to fetch 
we check if the request is less than 64kb, but maybe we then add overhead and so fetch rejects it
let's reduce the threshold so that we can't possibly trigger this error for fetch
=> fix: reduce keep alive threshold

README.md
When getting `posthog-js` setup locally and testing with the nextjs playground app, it was noticed that there were a few missing steps.  This PR adds those missing steps to the README for thoroughness sake.
...
=> chore: update README to include missing steps for running local nextjs playground

src/utils/event-utils.ts
Add timezone to events (timezone looks like Europe/London).
In older browsers that don't support Intl, this property won't be sent.
This is useful for a couple of things:
* I want to add a time of day query, which shows you how active your site is at different times of day, and it'd be cool to have a toggle to show it by the user's timezone (so you could see that e.g. around the world your app is always popular at 8am)
* I can use this for the cookieless rotating salt, to figure out which day's salt to use
=> feat: Add timezone to events

src/__tests__/autocapture.test.ts, src/autocapture.ts, src/heatmaps.ts, src/utils/element-utils.ts
Lifts a set of refactors out of https://github.com/PostHog/posthog-js/pull/1463/
That PR Introduces dead clicks autocapture but has a consistent failing cypress test for surveys which should not have been impacted
=> chore: refactor towards dead clicks autocapture

src/__tests__/entrypoints/lazy-loaded-dead-clicks-autocapture.test.ts, src/autocapture-utils.ts, src/autocapture.ts, src/entrypoints/dead-clicks-autocapture.ts, src/heatmaps.ts, src/utils/element-utils.ts
turned on dead clicks in prod
watched what we captured realised some things could be improved
=> fix: dead click fixes from watching in prod

src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/sessionrecording.ts, src/types.ts
Client for https://github.com/PostHog/posthog/pull/25845 
Enables pausing the recording when certain urls are visited.
=> feat: add recording url blocklist

src/__tests__/entrypoints/lazy-loaded-dead-clicks-autocapture.test.ts, src/__tests__/extensions/dead-clicks-autocapture.test.ts, src/__tests__/heatmaps.test.ts, src/constants.ts, src/entrypoints/dead-clicks-autocapture.ts, src/extensions/dead-clicks-autocapture.ts, src/heatmaps.ts, src/posthog-core.ts, src/types.ts, src/utils/element-utils.ts, src/utils/globals.ts
we want to allow deadclicks collection in heatmaps
it gives you less information but doesn't cost money, folk that want more information can turn on standalone deadclicks capture
to keep things loose the heatmap starts its own instance of deadclicks capture, deadclicks was altered to receive varying behviour by constructor injection
---
running locally I can capture deadclicks correctly with both deadclicks and heatmaps enabled or either one enabled
=> feat: deadclicks in heatmaps

cypress/e2e/error-tracking.cy.ts, src/extensions/sentry-integration.ts
Sentry exceptions should also have the `type` on stacktraces
=> chore: add type to Sentry exception

src/__tests__/posthog-persistence.test.ts, src/posthog-core.ts
We currently use sessionStorage even when the persistence is set to memory. This is a bug, which this PR fixes and adds some tests for.
=> fix: Don't use session storage in memory mode

react/src/components/PostHogFeature.tsx, react/src/components/__tests__/PostHogFeature.test.jsx, react/src/utils/type-utils.ts
Closes https://github.com/PostHog/posthog/issues/22922
=> fix(flags): support multiple children prop in PostHogFeature

cypress/e2e/session-recording.cy.ts, playground/cypress/index.html, src/entrypoints/recorder.ts, src/extensions/replay/sessionrecording.ts
We were using `req.method` _before_ the request was used and so XHR was always captured as "GET"
=> fix: XHR req method capture

playground/nextjs/pages/_app.tsx
Related documentation updates https://github.com/PostHog/posthog.com/pull/9906
Confirmed that this covers everything needed for the toolbar and the general script loading.
=> chore: Added CSP headers to next app for testing what we document

eslint-rules/no-direct-mutation-observer.js, src/entrypoints/dead-clicks-autocapture.ts, src/utils/globals.ts, src/utils/prototype-utils.ts, src/utils/type-utils.ts
we get periodic reports of performance issues with angular
angular change detection patches browser methods
we do change detection too
so we fight each other
this 
* grabs MutationObserver from an iframe so that we aren't using angular's patched methods
* fixes detection of whether Angular has patched a method
* adds an eslint rule so we don't use MutationObserver directly in future
=> fix: angular change detection mutation observer

src/entrypoints/dead-clicks-autocapture.ts, src/utils/globals.ts, src/utils/type-utils.ts
I'm getting test errors when merging main into https://github.com/PostHog/posthog-js/pull/1515
> TypeError: (0 , _typeUtils.isNativeFunction) is not a function
I can't see why, but I can simplify the implementation to see if a different merge works
I opened https://github.com/PostHog/posthog-js/pull/1534 to check whether any PR would fail now, but that was fine so 🤷
=> fix: refactor native mutation observer implementation

rollup.config.js
IE 11 tests are freezing in https://github.com/PostHog/posthog-js/pull/1525 which shouldn't have changed IE11 bundle at all
This pulls small changes from that PR that are safe to make in an attempt to identify the problem
=> chore: very small change to IE11 bundling

package.json, pnpm-lock.yaml
pulling small changes out of https://github.com/PostHog/posthog-js/pull/1525 because IE 11 tests are freezing in that PR and it's really hard to figure out why
in that PR I added an explicit browserslist version, let's do that separately
=> chore: specify an explicit browserslist version

.github/workflows/testcafe.yml
https://github.com/PostHog/posthog-js/pull/1525 has a problem where the IE 11 tests are freezing
it will run for many hours
that's silly
=> chore: timeout test cafe jobs

patches/@rrweb__record@2.0.0-alpha.17.patch, pnpm-lock.yaml
follow-up to https://github.com/PostHog/posthog-js/pull/1531 which fixed this for dead clicks
patch rrweb to correctly detect angular's change detection
🎉 tested locally by installing patched version in an angular application and seeing it no longer freezes 🎉 
also opened upstream PR here https://github.com/rrweb-io/rrweb/pull/1597
=> fix: patch angular wrap detection in rrweb

.github/workflows/es-check.yml, package.json, rollup.config.js, src/__tests__/posthog-core.test.ts
#1525 - IE 11 tests are freezing in that PR and it's really hard to figure out why
have pulled many small changes out of that PR but the IE 11 tests still freeze
----
* improves detection/bundling of ES6 support for posthog-js by being more specific with the browser targets that are passed to the bundler
* adds a check that the array.full.js is ES6 compliant in CI
Does not update the browserslist value in package.json, since that is the change that appears to make CI freeze
I'd rather get the benefit of the ES6 compliant bundle in prod before fixing that
=> fix: improve ES6 bundling

src/__tests__/surveys.test.ts, src/posthog-surveys-types.ts, src/posthog-surveys.ts
As part of adaptive survey collection, we introduced a new feature flag that the surveys component should use to filter out surveys to be shown to people. 
The common pattern has become : 
1. Add a flag to the API
2. Add the same flag as a check to `getActiveMatchingSurveys`
Instead, this PR now uses the `feature_flag_keys` array to find the names of the feature flags to check in the survey component. 
With this change, one can just add a new flag to the `feature_flag_keys` in the Surveys API in posthog.com and the survey component will automatically pick it up.
=> fix(surveys): Process feature_flag_keys on Survey object

src/extensions/exception-autocapture/stack-trace.ts
=> chore: make platform more specific

src/__tests__/extensions/replay/config.test.ts, src/extensions/replay/config.ts
We check for `/s/`, `/e/`,  and `/i/` in URL's pathname and don't capture network payloads to them
But if you use a reverse proxy then the pathname won't necessarily be `/s/` e.g. some folk use `/ingest/s/` so we need a slightly different check
Otherwise when you visit one of these sites we endlessly send a network payload to ourselves recording that we just sent a network payload to ourselves etc
=> fix: endless capturing /s/

src/extensions/replay/sessionrecording-utils.ts
using `at` in the circular replacer copied from MDN implicitly moves us to safari 15.4+
it's not necessary to use `at` and tbh it's rare enough I can parse this version more easily 
should fix https://github.com/PostHog/posthog-js/issues/1518
=> fix: safari support requires we don't use

src/__tests__/personProcessing.test.ts, src/__tests__/posthog-persistence.test.ts, src/storage.ts, src/utils/event-utils.ts
Fixes https://github.com/PostHog/posthog-js/issues/1524 by moving the initial person info to the cookie
=> feat: Add initial person info to cookie when using localPlusCookieStore

patches/@rrweb__record@2.0.0-alpha.17.patch, pnpm-lock.yaml
see https://github.com/PostHog/posthog-js/issues/1561 which points at an error in using the `:modal` pseudo selector
it does appear that safari started supporting the dialog element in 15.4 and the `:modal ` selector in 15.6
=> fix: catch errors detecting dialog state when recording

patches/@rrweb__record@2.0.0-alpha.17.patch, pnpm-lock.yaml
It's really hard to reproduce the bug, and in the one site where I can reproduce it it's really hard to debug what's happening.
Explanation in-line in the review, but this is an attempt to make this detection safer in Safari
=> fix: patch to angular detection in rrweb

src/__tests__/extensions/replay/sessionrecording.test.ts, src/__tests__/sessionid.test.ts, src/__tests__/utils/number-utils.test.ts, src/posthog-core.ts, src/sessionid.ts, src/utils/number-utils.ts
allow configuring an idle timeout larger than the default
see https://posthog.slack.com/archives/C07RUA1TBT3/p1732619524510359
the motivation for the user here is that their product might be used by someone before they leave for the day, and then once they return, and those two interactions are logically one session. the second might follow-on from the first.
=> feat: different default and max idle period

src/__tests__/utils/event-utils.test.ts, src/utils/event-utils.ts
We've recently launched a new feature on Web Analytics where you can filter views/visitors by timezone/language. Even though that was possible to do already, it is not as fast as it could be. We'll start feeding this information into the database directly from the SDK, this will allow us to, in the future, update our logic to use these properties directly, ditching the slow code.
=> feat: Start tracking timezone offset and language prefix

patches/@rrweb__record@2.0.0-alpha.17.patch, pnpm-lock.yaml, src/utils/prototype-utils.ts, src/utils/type-utils.ts
mutation observer setup is _sometimes_ failing in Safari
I think that the underlying problem is we can't reliably get the mutation observer from an iframe
but we are at least _always_ trying to get it from an iframe instead of only when angular has monkeyed around with it
let's reduce the number of people affected by checking correctly
i've tested locally that this doesn't freeze the test angular app that would freeze if this didn't work
and i've tested locally that i can record safari (as much as i can, it wasn't _always_ failing)
=> fix: zone detection

src/customizations/before-send.ts
Add customization to print all events then drop them.
Fixed https://github.com/PostHog/posthog-js/issues/1320
=> feat: Add customization to print events drop them

src/__tests__/request.test.ts, src/request.ts
Fixes https://github.com/PostHog/posthog-js/issues/1440
I'm a bit wary that there's another root cause we're missing, I would like to hear from those users where the BigInts came from in the first place, but in the mean-time let's not crash
=> fix: Don't crash on bigints

src/__tests__/site-apps.ts, src/site-apps.ts
The existing site apps on cloud expect `__$$ph_site_app_${id}` as the global where they'll find the PostHog-JS library. This changed recently to `__$$ph_site_app_${id}_posthog`. Revert that change.
=> fix: use previous site-app variables

src/__tests__/utils/event-utils.test.ts, src/utils/user-agent-utils.ts
Based on some Googling it seems like the latter value in this user agent (`Chrome/28.0.1500.94 `) is actually the browser.
_Maybe_ we don't want to make this change because it will affect peoples existing browser attribution but I think it's totally reasonable to ship a fix forward here
=> fix: parse Chrome instead of Android as browser

src/__tests__/extensions/surveys/action-matcher.test.ts, src/__tests__/utils/survey-event-receiver.test.ts, src/extensions/surveys/action-matcher.ts, src/posthog-surveys-types.ts
Changes survey action type to match here https://github.com/PostHog/posthog/pull/26759
=> feat: Simplify survey types

src/posthog-core.ts
Remove the call to `_requirePersonProcessing` from `setPersonPropertiesForFlags`, as it doesn't need it
More context at https://posthog.slack.com/archives/C01MGUHFH6G/p1733511049244089
=> feat: Don't create person profile when setting properties for flags

src/posthog-core.ts
This property might be accessed/called before we've properly initialized feature flags, so let's make sure we're not breaking anything (we have broken it already, see https://posthog.slack.com/archives/C02E3BKC78F/p1734111258352399)
- No tests for now, but we should add it eventually, we need to guarantee this doesn't break anymore
=> fix: Make legacy property sturdier

playground/nextjs/package.json, playground/nextjs/pages/_app.tsx, playground/nextjs/pnpm-lock.yaml, playground/nextjs/src/posthog.ts, src/__tests__/cookieless.test.ts, src/constants.ts, src/entrypoints/tracing-headers.ts, src/extensions/replay/sessionrecording.ts, src/extensions/tracing-headers.ts, src/posthog-core.ts, src/sessionid.ts, src/types.ts, src/utils/globals.ts
Part of https://github.com/PostHog/posthog/issues/25117
Main repo PR (currently WIP, this PR can be merged before that one) https://github.com/PostHog/posthog/pull/25915
Everything is behind a config option with a dire warning, so this doesn't need to be final.
=> feat(web-analytics): Add flag to send server hash instead of distinct id

playground/nextjs/package.json, playground/nextjs/pages/_app.tsx, playground/nextjs/pages/api/socket.ts, playground/nextjs/pages/chat.tsx, playground/nextjs/pages/index.tsx, playground/nextjs/pnpm-lock.yaml
taking baby steps to avoid a conflict with someone else's changes to the playground
this adds a chat page using websockets to the playground, next step is to wrap the websocket client so we use network requests over sockets in replay
=> chore: add websockets example to nextjs playground

cypress/support/e2e.ts, src/__tests__/helpers/posthog-instance.ts, src/__tests__/loader.test.ts, src/__tests__/posthog-core.identify.test.ts, src/__tests__/posthog-core.ts, src/__tests__/segment.test.ts, src/remote-config.ts
Part of the rollout testing. Because this is replacing decide we can't use decide to gradually rollout. Instead I'm turning it on for everyone but only using it if the preview flag is enabled. That way I can poke around implementations and see if its working as well as checking backend metrics
=> fix: Load RemoteConfig by default but don't use it

cypress/e2e/session-recording.cy.ts, src/__tests__/featureflags.test.ts, src/__tests__/surveys.test.ts, src/posthog-core.ts, src/posthog-featureflags.ts, src/posthog-surveys.ts, src/request.ts, src/web-experiments.ts
=> fix: Change default transport to fetch

cypress/support/e2e.ts, src/__tests__/helpers/posthog-instance.ts, src/__tests__/loader.test.ts, src/__tests__/posthog-core.identify.test.ts, src/__tests__/posthog-core.ts, src/__tests__/remote-config.test.ts, src/__tests__/segment.test.ts, src/__tests__/site-apps.ts, src/remote-config.ts, src/site-apps.ts, src/utils/globals.ts
Related to https://github.com/PostHog/posthog/pull/26964
Use the scoped version of the config loader
=> feat: Use token scoped remote config

src/__tests__/utils.test.ts, src/autocapture-utils.ts, src/autocapture.ts, src/consent.ts, src/customizations/before-send.ts, src/customizations/setAllPersonProfilePropertiesAsPersonPropertiesForFlags.ts, src/extensions/replay/sessionrecording.ts, src/heatmaps.ts, src/posthog-core.ts, src/posthog-persistence.ts, src/request.ts, src/utils/encode-utils.ts, src/utils/event-utils.ts, src/utils/index.ts, src/utils/string-utils.ts, src/utils/type-utils.ts, src/utils/user-agent-utils.ts
rollup warns about circular dependencies when building...
it doesn't seem to be a problem but we may as well remove a little noise since reorganising is free
=> chore: remove circular dependencies

cypress/e2e/session-recording.cy.ts, src/posthog-core.ts, src/request.ts
Lets reorder our request implementation to use fetch as the default in case someone specifies an unknown method, rather than using XHR
Closes #1487
=> chore: Small tweaks after making `fetch` the default request implementation

src/__tests__/heatmaps.test.ts, src/heatmaps.ts, src/utils/element-utils.ts
We stumbled onto this bug, with rxdb [dispatching mouse events](https://github.com/pubkey/rxdb/blob/e045257ed3bef3e8c01032d5a91e6260ce0b8c2e/src/plugins/replication/replication-helper.ts#L116) without data and thus producing a posthog crash. 
[This typecast](https://github.com/supermar1010/posthog-js/blob/7d11d7f33ecce50367777694172d01d22187314d/src/heatmaps.ts#L180) is why the error wasn't spotted by ts. The type of `e.target` is originally `EventTarget | null`, but looses the `| null` in this cast.
=> fix: type error accessing null object and added test case

src/__tests__/heatmaps.test.ts, src/heatmaps.ts, src/utils/element-utils.ts
https://github.com/PostHog/posthog-js/pull/1620/ reminds us that JS can and will let people do whatever they want so we can't be guaranteed that events that trigger event listeners are really valid events
this filters out any event that doesn't have the `clientX` and `clientY` that we rely on
we safely filter these in ingestion, but we may as well just not send them
=> fix: do not even send heatmap with no x or y

src/posthog-core.ts
CD is failing because lint is failing 🤷 
the change came in with pr https://github.com/PostHog/posthog-js/pull/1610 which also succeeded in all checks :wat:
=> chore: lint a file that needs it

CHANGELOG.md
CD task was broken because of linting which meant we never published 1.202.3 and 1.202.4 is mungled up with 1.202.5
this updates the changelog to represent what is in each release
=> chore: fix changelog after automation error

.github/workflows/minimum-version-ts-check.yaml, README.md
i advised a customer to upgrade and they couldn't because we had an implicit minimum TS version, luckily they could upgrade without a major TS verson upgrade the friday before xmas by applying a minor update
let's test that discovered minimum so we know if we break it in future
we discovered you can't run tsc in a project lower than TS 4.7.2 that imports posthog
(for the benefit of folk coming across this issue - this doesn't affect JS projects or the HTML snippet)
---
this builds the library under different node versions and then imports it into a file and runs tsc on that file
here's that failing using the customer's too low version
=> chore: build against lowest and current version of TS

src/__tests__/extensions/replay/config.test.ts, src/extensions/replay/config.ts
noticed while investigating something else
if you have payload capture on then we're capturing payloads for ms clarity and google analytics. that's silly and unnecessary data load
=> fix: payload host deny list

cypress/e2e/session-recording.cy.ts, src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/sessionrecording.ts
useful when debugging sessions if the customer doesn't have payload capture on
hard to know if a session got the config you'd expect otherwise
=> feat: custom event with remote config

src/__tests__/utils/external-scripts-loader.test.ts, src/entrypoints/external-scripts-loader.ts, src/types.ts
Solves https://posthog.com/questions/how-to-set-nonce-for-recorder-and-surveys-scripts
Adds a new option for modifying scripts before external loading, in this case for adding a nonce
=> feat: Adds option for nonce support

src/extensions/toolbar.ts
see https://us.posthog.com/project/2/error_tracking/295441fc-c916-4257-a1cb-4d896601ad82 and https://bsky.app/profile/victornido.bsky.social/post/3leti5mx6q22j
getting `(de.ph_load_toolbar || de.ph_load_editor) is not a function` error
it's not clear why to me, but we can at least make it fail gracefully
=> fix: safer toolbar function

src/__tests__/page-view.test.ts, src/__tests__/posthog-core.ts, src/page-view.ts, src/posthog-core.ts
* Keep track of the last pagview event id
* Send the pageview event id with every event
This came from a discussion with @orian who wanted to be able to associate all of the query completed events that were triggered by the same pageview
=> feat: Add pageview and prev pageview tracking

src/posthog-core.ts, src/types.ts
We can achieve the exact same outcome we achieve with `sanitize_properties` by using `before_send` which is a much more compreheensive function, with better usability and ergonomics.
We can't remove this function without a major, so let's deprecate it and issue a console warning when it's used.
=> feat: Deprecate `sanitize_properties`

src/__tests__/extensions/surveys.test.ts, src/extensions/surveys.tsx, src/extensions/surveys/components/BottomSection.tsx, src/extensions/surveys/components/QuestionTypes.tsx, src/extensions/surveys/surveys-utils.tsx
Adds a new `onPreviewSubmit` parameter to `renderSurveysPreview`.
The main usage of `renderSurveysPreview` is on posthog internal website to demo surveys.
By adding this callback, it allow us to call arbitrary functions after pressing the submit button in the survey.
It'll be used to fix this issue: https://github.com/PostHog/posthog/issues/23650 and allow us to move to the next question after clicking the submit button.
...
=> feat: Add a onPreviewSubmit callback to preview surveys

src/utils/blocked-uas.ts
added `'better uptime bot'` to `blocked-uas.ts`. The user agent comes from their docs: https://betterstack.com/docs/uptime/frequently-asked-questions/#what-user-agent-does-uptime-use
Let me know if this is the correct way to do this.
=> feat: add Better Uptime string to blocked UA

src/extensions/surveys/surveys-utils.tsx, src/posthog-surveys-types.ts
Adds a new optional property to survey's appearance: `fontFamily`. 
Keeps the current value as default to not break any existing surveys.
...
=> feat: custom webfont selection on surveys

src/__tests__/cookieless.test.ts, src/constants.ts
Renaming some constants, for more obvious naming for somebody reading through some logs.
Not used in production yet, so doesn't affect version compatibility.
=> chore: Rename cklsh constants to cookieless

playground/nextjs/src/Header.tsx, src/extensions/surveys/components/BottomSection.tsx
Closes https://github.com/PostHog/posthog/issues/27499
to prevent this from happening:
also add a Surveys link to our Nextjs playground header
...
=> fix: survey previews should never have the submit button disabled

src/__tests__/web-experiments.test.ts, src/web-experiments.ts
Removes the `$web_experiment_applied`event because it causes many more events than the customer expects.
See https://posthog.slack.com/archives/C07PXH2GTGV/p1736886880767199
Introduced in https://github.com/PostHog/posthog-js/pull/1443
=> chore: Remove '$web_experiment_applied' event

src/__tests__/request-utils.test.ts, src/__tests__/session-props.test.ts, src/__tests__/utils/event-utils.test.ts, src/customizations/setAllPersonProfilePropertiesAsPersonPropertiesForFlags.ts, src/posthog-core.ts, src/posthog-persistence.ts, src/session-props.ts, src/types.ts, src/utils/event-utils.ts, src/utils/index.ts, src/utils/request-utils.ts
Add a config option to mask URL parameters. This will also mask any properties that are derived from them.
Why: We want to add a cookieless mode, allowing users to be tracked before consent is given. To do this, we need to not capture any PII-containing properties (such as ad IDs like `gclid`), as consent would be needed for those.
=> feat: Add the ability to mask some PII-containing URL parameters

src/__tests__/posthog-core.identify.test.ts, src/posthog-core.ts, src/utils/identify-utils.ts
Often duplicate $identify calls are made due to the SDK being incorrectly setup in the app, or due to re-rendering of providers.
The current behaviour is to only deduplicate $identify calls with no properties, but most $identify calls include properties like email, so they are not deduplicated. This PR extends deduplication to calls with properties.
Note: this is my first contribution to js sdk so would appreciate a thorough review.
...
- [x ] Accounted for backwards compatibility of any changes (no breaking changes in posthog-js!)
=> chore: deduplicate subsequent identify calls

patches/@rrweb__record@2.0.0-alpha.18.patch, pnpm-lock.yaml
patches in this PR https://github.com/rrweb-io/rrweb/pull/1615
=> fix: patch for css parsing performance

src/extensions/sentry-integration.ts, src/posthog-core.ts
Cymbal is throwing some errors on exceptions because not all the correct fields are set:
```
serde error: missing field `platform` at line 1 column 14449
```
- Adds the platform field
- Also fixes a bug where additional properties were not being set in the case where an exception was manually captured but `parseErrorAsProperties` didn't exist (e.g. exception auto capture wasn't enabled)
=> fix: sentry integration fields

src/__tests__/posthog-core.identify.test.ts, src/__tests__/posthog-core.reset.test.ts, src/posthog-core.ts
i frequently have to diagnose whether a user called reset at an unexpected time and we just have to infer it
Let's set the last reset time on events so we can be more less confused
=> fix: set last reset date as event super property

patches/@rrweb__record@2.0.0-alpha.18.patch, pnpm-lock.yaml
we're clearly hitting a pathological case in the CSS processing for some folks
my guess is something is repeating the check due to run away mutations or something in a tight loop... or maybe it is just bad at very large strings 🤷 
quoting my old colleague Chris Sewart about peformance
you can do it faster
do it less
or not do it
let's cache our results as we go so that we only run the nested check or the regex replace once per input
you can see the test here https://github.com/PostHog/posthog-rrweb/pull/17
we see results like
```
First execution time: 3.3014169996604323ms
Average execution time for the second execution: 1.8079558699950575ms
```
that second execution will be O(1)
while first execution is O(n)
so where O(n) is large this should be a much bigger improvement
=> fix: cache nested loops

patches/@rrweb__record@2.0.0-alpha.18.patch, playwright/session-recording/session-recording-network-recorder.spec.ts, pnpm-lock.yaml
oops, we mutate the value that I'm using as a cache key, so we never hit the cache 🫠
=> fix: correctly cache split css

.github/workflows/minimum-version-ts-check.yaml
=> fix: Fix CI check name

patches/@rrweb__record@2.0.0-alpha.18.patch, pnpm-lock.yaml
from investigation of how rrweb has done this over time and how safari behaves with different versions manually patched
i learned that Angular Zone advertises its unpatched versions in a known/discoverable location
let's just use them instead of going to an iframe when they're present
=> fix: angular detection can be less blunt

.eslintrc.js, react/src/context/PostHogProvider.tsx, react/src/context/__tests__/PostHogProvider.test.jsx, react/src/utils/__tests__/object-utils.test.ts, react/src/utils/object-utils.ts
We were using a built-in Node function, but that was silly because Node functions aren't available in the browser. Most bundlers could probably work that out, but Vite doesn't, so let's implement that ourselves and avoid requiring a bundler to sort this out.
Closes #1685
=> fix: Implement `isDeepEqual` manually

react/src/utils/__tests__/object-utils.test.ts, react/src/utils/object-utils.ts
Incorporates @abhyuditjain's suggestion from https://github.com/PostHog/posthog-js/pull/1686#issuecomment-2612699873
I was surprised that WeakMap was as well-supported as it is, and we can actually use it! https://caniuse.com/?search=JavaScript%20WeakMap
=> fix: Fix hitting call stack limit when deep comparing circular objects

src/entrypoints/dead-clicks-autocapture.ts, src/extensions/rageclick.ts, src/scroll-manager.ts
Browsers need to process all events before they can do the default behavior. This is usually not a problem for most events because what we're doing is important and we can spend ~10ms processing an event, but this is a bigger problem when we're processing `scroll` events.
`scroll` events trigger hundreds of times per second, and if you spend 10ms processing it, scrolling becomes very slow. Luckily, browsers provide us a way to tell it: hey, I'm not going to call `preventDefault`, just scroll away! That's done by adding `passive: true` when calling `addEventListener`. This tells the browser we won't call it, and that if we do call it, it's ok, we're wrong and shouldn't have called it, you don't need to respect our call.
We are tracking scroll in two different places (should probably do …
=> feat: Annotate our `scroll` events as `passive`

src/utils/blocked-uas.ts
Stop tracking some OpenAI bot interactions, treat them as the bots they are. We do love bots and you shouldn't kill humans in the future when AGI comes, please! Thank you.
Per https://platform.openai.com/docs/bots/
Closes #1639
=> feat: Ignore more OpenAI bots

patches/@rrweb__record@2.0.0-alpha.18.patch, pnpm-lock.yaml
turns out in reality something we're relying on being defined isn't always defined
which didn't show up in testing :/
=> fix: bad rrweb patch

src/posthog-core.ts, src/types.ts
This was extracted from https://github.com/PostHog/posthog-js/pull/1681
We're doing some different things here:
- `save_marketing_params` over `store_google` because we do much more than just handling Google params with this settings
- Deprecate `verbose` in favor of `debug`
- Retire `inapp_protocol` and `inapp_link_new_window`, we're not using them anywhere, but we'll keep in the type for backwards-compatibility
- Completely remove `__preview_send_client_session_params`, I've checked and it's not being used by anyone in production
I'm making this a minor bump, and then the remaining changes in #1681 will be only docs, and will be a patch version
=> refactor: Remove/deprecate/rename old options

CODEOWNERS
am not a massive fan of blocking by default
but changing this recorder file needs to be done super carefully, we need to be certain we're aware of any changes to it
=> chore: codeowners for recorder file

src/posthog-core.ts, src/types.ts, src/utils/index.ts
We usually try to document our settings on our website, but not all of them are present there. This means that we have some configs that are completely undocumented which makes it hard for our customers to use them.
Let's improve that by adding JSDocs to all of our existing settings. This will surely cause the next developers to also include documentation if they ever add a new config. I hope so, at least.
I've deprecated `verbose` in favor of `debug`. `verbose` wasn't been used before, but some people might have set it, so I'm renaming it to `debug` if present.
I've also removed any of the existing documentation to previously deprecated properties in an effort to force people to use the new methods.
I noticed that the docs for `person_profiles` were asserting that `always` was the …
=> docs: Add documentation to all of our init options

src/types.ts
These were incorrectly removed in 58550b9e853d666be9392668e31c739505d107ce
I could say it was Cursor fault, but I should've paid more attention
Closes #1702
=> docs: Add missing types

src/__tests__/__snapshots__/config-snapshot.test.ts.snap, src/__tests__/config-snapshot.test.ts
we accidentally removed some options from a config in another PR
computers should protect us
this is 99% ChatGPT so review accordingly 🙈 
this converts provided types into a dict and snapshots that
this should let us known when we're accidentally breaking types for consumers
=> chore: snapshot types that we want to not accidentally deprecate or remove

src/__tests__/__snapshots__/config-snapshot.test.ts.snap, src/__tests__/request-queue.test.ts, src/__tests__/request.test.ts, src/posthog-core.ts, src/request-queue.ts, src/request.ts, src/retry-queue.ts, src/types.ts
the request queue has a fixed interval where it sends events, this allows us to batch events to reduce load on ingestion and reduce network calls on client devices
but for customers where they may have short page visits or automated page redirects this means relying on the unload mechanism which browsers don't guarantee
let's allow configuring that interval between 250 and 5000ms
=> feat: allow configuring request queue interval

src/extensions/replay/sessionrecording.ts
Need to export some extra types from posthog-js so that I can use them in PostHog
=> chore: some rrweb type changes

src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/sessionrecording.ts
We're checking if status is paused before pausing..
Makes sense, except we have multiple controls and only one status
So, it's possible to be pausable while sampling has determined you shouldn't be recording at all 🤦 . So if `sampling` had determined we should not record this session then we'd init a pause on every rrweb event... which probably causes rrweb events, and down the spiral to madness
Let's check a paused specific flag instead of the top level status
=> fix: checking status is too blunt for paused status

src/posthog-core.ts
In a recent version, we updated the body of this function to always return a `Posthog` instance but we forgot to update the type, let's fix that
This is a slight type-level breaking change at `posthog-core.ts`. This is more serious than the recent changes we did to code that was only present in the React SDK. Should we ship this? I assume you'll have thoughts @pauldambra 
Originally written by https://github.com/thexeos but I couldn't get his PR to pass CI - secrets are not shared with contributors PRs
Closes #1616
Supersedes #1617
=> refactor: Simplify `Posthog.init()` signature

src/posthog-core.ts
We frequently get support tickets where the resolution is that the user called reset at the wrong time
This is not an easy thing to fix... but let's try and make intellisense even more clear
=> chore: better reset comment

react/src/hooks/__tests__/featureFlags.test.jsx, react/src/hooks/useActiveFeatureFlags.ts, react/src/hooks/useFeatureFlagEnabled.ts, react/src/hooks/useFeatureFlagPayload.ts, react/src/hooks/useFeatureFlagVariantKey.ts, src/posthog-persistence.ts, src/types.ts
Context: https://posthog.slack.com/archives/C07F4BF6WLT/p1738270875752869
TLDR:
To suppress a NextJS hydration error, we were previously forgoing default state values in our feature flags hooks. This was necessary because the `posthog` client methods like `isFeatureEnabled` use browser-only APIs like `localStorage` or `document`, which cannot run in SSR. 
Currently, we "fix" this issue by using solution #1 from the [nextjs docs](https://nextjs.org/docs/messages/react-hydration-error#possible-ways-to-fix-it). However, this results in the first render on the client side returning `undefined` from our feature flag hooks, which is both potentially incorrect (if flags are already loaded) and can cause bugs. Further, this hydration error does not actually apply to anyone using our React library …
=> fix(flags): set default state values in feature flag hooks

playwright/error-tracking.spec.ts, src/__tests__/extensions/exception-autocapture/error-conversion.test.ts, src/entrypoints/exception-autocapture.ts, src/extensions/exception-autocapture/error-conversion.ts, src/posthog-core.ts, src/types.ts, src/utils/globals.ts, src/utils/type-utils.ts
Because you could call `captureException()` with a string it is possible that the type and value would be undefined if autocapture was disabled because of:
```
...
type: error.name,
value: error.message,
...
```
Adds a fix to check for an error type and if not just use the provided value. This is best effort given we don't import the full `exception-conversion` file for this case
=> fix: capture when argument is not a string

src/__tests__/__snapshots__/config-snapshot.test.ts.snap, src/__tests__/extensions/exception-autocapture/exception-observer.test.ts, src/extensions/exception-autocapture/index.ts, src/types.ts
Right now there is no way to disable exception autocapture clientside.
Adds a config option that takes precedence over the server value
=> feat: override exception capture clientside

src/extensions/replay/sessionrecording.ts
While investigating something else on a customer site I noticed an error caused by this code
The error is handled and safe, but it turns out unnecessary.
I'd typed stylesheet rules as always having adds and removes, but they can be undefined.
Let's fix that.
=> fix: unexpected undefined should be expected

src/__tests__/heatmaps.test.ts, src/heatmaps.ts
fixes https://github.com/PostHog/posthog-js/issues/1735
we shouldn't be setting up listeners in the constructor anyway since we can init heatmaps and not be enabled
so, moves into the setup method, and binds this
=> fix: heatmaps unload listener

src/posthog-featureflags.ts, src/types.ts
Adds `getRemoteConfigPayload` to feature flags, which re-calls `/decide` and returns the single remote config feature flag payload:
Context: https://posthog.slack.com/archives/C074A08LP1B/p1739376378507109
- Looking into this!
=> feat(flags): Add remote config feature flag method that bypasses cached values

src/__tests__/personProcessing.test.ts, src/__tests__/posthog-core.ts, src/__tests__/session-props.test.ts, src/posthog-core.ts, src/posthog-persistence.ts, src/session-props.ts, src/utils/event-utils.ts
There are a few changes here
Change 1: the biggest one is that we send set_once props for the *latest* props now. Previously, we just sent *initial* props. This means that this user journey now works
* start on subdomain1.example.com
* go to subdomain2.example.com
* call identify()
* check latest props
Previously, they would not necessarily have latest props, which we saw in a ticket here https://posthog.slack.com/archives/C05LJK1N3CP/p1739469826803839. Now we are using the session-scoped props to set these.
Change 2: reduce how often we send set_once properties. Previously we were sending these with every event with person properties, now we only send them with the first one.
Change 3: the set_once properties will now get proper masking of personal data properties in saved URLs.
=> feat(web-analytics): Handle set_once latest props in a cross-subdomain way

src/__tests__/posthog-core.ts, src/posthog-core.ts
it can be tricky to know what is happening when users report errors
let's add more debug signals
needs a follow-up to add these to core definitions
=> feat: add more debug signals

package.json, src/__tests__/__snapshots__/config-snapshot.test.ts.snap, src/__tests__/extensions/replay/mutation-rate-limiter.test.ts, src/__tests__/extensions/replay/sessionrecording-utils.test.ts, src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/mutation-rate-limiter.ts, src/extensions/replay/sessionrecording-utils.ts, src/extensions/replay/sessionrecording.ts, src/extensions/replay/types/rrweb.ts, src/types.ts
Some users aren't willing to turn `skipLibCheck` off which causes errors with us importing types from `@rrweb/types` but making that a developer dependency. In some other cases, namely, those using the Angular compiler, they actually can't turn this off, which is blocking their use of newer posthog-js versions
We can fix that in two ways:
- Let's add `@rrweb/types` as a peer dependency, this way users will know that they need to install the library themselves to get types to work
- Let's stop using `@rrweb/record` types to prevent people from having to install it. This increases our maintenance burden because we need to keep the types ourselves, but it implies they won't need to bundle a heavy library if they don't need it.
---
> How did you check this work?
I checked the new …
=> chore: Make `@rrweb/types` a peer dependency

playground/nextjs/pnpm-lock.yaml, src/__tests__/posthog-core.loaded.test.ts, src/posthog-featureflags.ts
with https://github.com/PostHog/posthog/pull/28564, we now start to respond different with the /decide and /local_evaluation APIs if users have gone over their quota limit. Now we need to change the SDKs to handle these new responses.
=> feat(feature-flags): support quota limiting for feature flags

src/__tests__/posthog-core.ts, src/__tests__/session-props.test.ts, src/posthog-core.ts, src/session-props.ts
See https://posthog.slack.com/archives/C06GG249PR6/p1741000095036129 for the feature request
Adds $session_entry_X properties to events, which includes some properties that are scoped to the lifecycle of the session id
I debated using a `$session` object and putting all the props in there, but I don't know how well materialisation would work on nested properties.
=> feat(web-analytics): Add $session property with an object of props on session_id lifecycle

README.md, src/posthog-featureflags.ts
When setting `advanced_disable_feature_flags_on_first_load`, we do not load feature flags on `posthog.init`. However, we do call `/decide` with `disableFlags: true`. However, when a subsequent `identify` call occurs immediately after, it's supposed to load the feature flags, but wasn't due to a race condition.
This PR fixes that condition.
Closes: #1766
I tested manually and confirmed that it fixed the minimal repro provided in #1766. I hope to follow up with some sort of test automation, but it's tricky.
=> fix(flags): Make sure flags are loaded when identify is called

.github/workflows/bundled-size.yaml, .github/workflows/cd.yml, .github/workflows/es-check.yml, .github/workflows/label-alpha-release.yml, .github/workflows/label-version-bump.yml, .github/workflows/library-ci.yml, .github/workflows/lint-pr.yml, .github/workflows/minimum-version-ts-check.yaml, .github/workflows/new-pr.yml, .github/workflows/react.yml, .github/workflows/stale.yaml, .github/workflows/testcafe.yml
Last few runs have been hit by Ubuntu 20.04 brownout: https://github.com/PostHog/posthog-js/actions/workflows/label-version-bump.yml
=> chore(): set all github actions to run on ubuntu-22.04

src/__tests__/site-apps.ts, src/site-apps.ts, src/types.ts
There were some bugs with site app loading, which this PR fixes
* It was possible to process batched events for a site app before the init call had returned.
* It was possible for one app to init immediately, and clear out the batched events for yet-to-be-initialized apps
I made one existing test fail by asserting that processEvents had been called the right number of times on both apps, and made a new failing test where the init call returns immediately. These changes fix both tests.
See also https://posthog.slack.com/archives/C06GG249PR6/p1741183829699909
=> fix: Fix site app loading

src/posthog-featureflags.ts
Follow up to https://github.com/PostHog/posthog-js/pull/1785, this PR addresses the same case where advanced_disable_feature_flags_on_first_load is set. The second decide call needs $anon_distinct_id to be present in order for authentication persistence to work as intended
=> fix(flags): do not reset $anon_distinct_id after first decide call if advanced_disable_feature_flags_on_first_load is true

src/__tests__/featureflags.test.ts, src/posthog-featureflags.ts, src/types.ts
Supports the changes here: https://github.com/PostHog/posthog/pull/29563
=> chore(flags): support handling optional `requestId`s in `/decide` responses

react/src/context/PostHogProvider.tsx
I believe that this is the wrong way around. The docs says here https://posthog.com/docs/libraries/react#posthog-provider 
> The provider can either take an initialized client instance OR an API key and an optional options object.
=> fix: Reverse error message

react/src/context/PostHogProvider.tsx
This causes errors on NextJS because it will be uninitialized on the server-side. We already make it pretty clear that you should control initializing the client when passing it in as a prop, so let's give up on the error log altogether
Closes #1802
=> fix: Stop logging error when client is uninitialized

src/__tests__/utils/external-scripts-loader.test.ts, src/entrypoints/external-scripts-loader.ts
the external script loader can add a script more than once
while the script might be idempotent it has to be parsed each time and will execute each time
let's add a simple check for the script's presence in the DOM and not add it if it's already there
=> fix: simple loader race protection

.github/workflows/library-ci.yml, .husky/pre-push, package.json, src/__tests__/utils/external-scripts-loader.test.ts
Somehow got a PR all the way to merged and being published before the publish failed because prettier hadn't been run
wat
labelled as patch so that my failed release gets retried
prettier fail here https://github.com/PostHog/posthog-js/actions/runs/13784405731/job/38548993523
🤣 GH actions warns on prettier errors without failing the step 🫠
=> fix: prettier needed running

CHANGELOG.md
the changelog got confused and had a bunch of blank entries
this adds what should have been in those entries
=> fix: blank changelog entries

src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/sessionrecording.ts
the default for mask all inputs is not clearly defined so there are routes through to get false when you're not expecting it. no bueno
=> fix: default mask all inputs must be defined

package.json
bumping minor didn't work either. see https://github.com/PostHog/posthog-js/actions/runs/13833784252?pr=1822
let's force the release 
(i'll separately fix the job, but need to get a fix out)
=> chore: force version in package.json

src/__tests__/posthog-core.ts, src/posthog-core.ts
we've had a few support tickets in replay that boil down to 
if you pass an invalid value to $current_url we accept it, use it, and then our UI explodes
let's add special casing to not allow someone to send e.g. `new URL(window.location.href)` when they think they're being helpful
=> fix: do not allow non string `$current_url`  to be provided

playwright/session-recording/session-recording-network-recorder.spec.ts, src/__tests__/posthog-core.loaded.test.ts, src/__tests__/posthog-core.ts, src/__tests__/utils/request-router.test.ts, src/entrypoints/array.full.es5.ts, src/posthog-featureflags.ts
This is a follow-up to #1837 where we added support for `/decide?v=4` in a backwards compatible fashion, but still made requests to `/decide?v=3`
With this change, we should get more useful debug information in `$feature_flag_called` events.
Changes the library to request `/decide?v=4` instead of `/decide?v=3`. All the substantial changes were made in #1837.
=> feat(flags): Enjoy the benefits of `/decide?v=4`. `$feature_flag_called` events contain more details such as flag version

playwright/session-recording/session-recording-network-recorder.spec.ts, src/__tests__/posthog-core.loaded.test.ts, src/__tests__/posthog-core.ts, src/__tests__/utils/request-router.test.ts, src/entrypoints/array.full.es5.ts, src/posthog-featureflags.ts
Reverts PostHog/posthog-js#1838
Oof, v4 responses from `/decide` were not smart about flags that were just straight disabled, let's roll back to v3
=> fix(flags): Revert "feat(flags): Enjoy the benefits of `/decide?v=4`. `$feature_flag_called` events contain more details such as flag version"

playwright/session-recording/session-recording-network-recorder.spec.ts, src/__tests__/posthog-core.loaded.test.ts, src/__tests__/posthog-core.ts, src/__tests__/utils/request-router.test.ts, src/entrypoints/array.full.es5.ts, src/posthog-featureflags.ts
This reverts commit 502c4c0176c5503a12657d78f442c99b2290b5ea which reverted 4c255123d038f878f1461afa5b7374ac35cd4359. We got ourselves a revert chain!
The purpose of this commit is to re-enable support for `/decide?v=4`. See this PR for more details: https://github.com/PostHog/posthog-js/pull/1838
=> fix(flags): Enjoy the benefits of `/decide?v=4`

src/utils/string-utils.ts
Change from using a regex-based trim to native trim
Also tightened up some types in the same file as I have a problem
=> fix: Switch from regex to trim

src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/sessionrecording.ts
we saw a case where a user had been sampled out (i.e. would not be recorded)
then the sample rate for the project was set back to null (i.e. no sampling)
but the user's browser never made a sampling decision again, so didn't pick up that it should reset the sampling decision
this changes things to clear any sampling decision whenever we see a null sample rate
=> fix: resetting sampling to null should clear sampling for users

playground/nuxtjs/nuxt.config.ts, playground/nuxtjs/package.json, playground/nuxtjs/plugins/posthog.client.js, playground/nuxtjs/pnpm-lock.yaml
A user complained that the nuxt js onboarding didn't work for them, so I made the nuxt playground work, then copied it to posthog.com examples. I fixed:
* it captured the initial pageview twice
* it didn't capture pageleave events 
See https://github.com/PostHog/posthog.com/pull/11174 for where I updated the examples
=> docs: Keep nuxt examples in sync with nuxt playground

src/__tests__/extensions/web-vitals.test.ts, src/extensions/web-vitals/index.ts
Check the protocol when starting up web vitals, and don't enable it if we're not on http or https. (i.e. don't use web vitals on file:// urls)
=> feat: Only capture vitals on http and https

playwright/session-recording/session-recording.spec.ts, src/__tests__/posthog-core.ts, src/extensions/replay/sessionrecording.ts, src/posthog-core.ts
a recording shows as active while still within its minimum duration so we can tell someone there is a recording to watch when e.g. they are three seconds into a ten second minimum
see https://posthog.slack.com/archives/C03PB072FMJ/p1744273599604909
=> chore: even more replay debug signal

react/src/context/PostHogProvider.tsx
Change the useState -> useMemo, and move the actual init call to a useEffect.
This should remove the need to do this in nextjs:
```tsx
export function PHProvider({ children }) {
useEffect(() => {
posthog.init(process.env.NEXT_PUBLIC_POSTHOG_KEY, {
api_host: process.env.NEXT_PUBLIC_POSTHOG_HOST,
person_profiles: 'identified_only',
capture_pageview: false,
capture_pageleave: true // Enable pageleave capture
})
}, []);
return <PostHogProvider client={posthog}>{children}</PostHogProvider>
}
```
and instead, people can just do 
```tsx
export function PHProvider({ children }) {
return <PostHogProvider
apiKey={process.env.NEXT_PUBLIC_POSTHOG_KEY}
options={{
api_host: process.env.NEXT_PUBLIC_POSTHOG_HOST,
person_profiles: 'identified_only',
capture_pageview: false,
capture_pageleave: true // …
```
=> feat: Improve how PostHogProvider works with SSR

.github/pull_request_template.md, .github/workflows/bundled-size.yaml, .github/workflows/library-ci.yml, .gitignore, rollup.config.js
Add a new automatic comment which contains a link to the bundle size visualizer. Try it below!
I also added a line about bundle size to the checklist
=> chore: Generate bundle size viz

src/__tests__/extensions/exception-autocapture/error-conversion.test.ts, src/extensions/exception-autocapture/error-conversion.ts
- Add support for error causes
Related to : https://posthog.com/questions/error-cause-is-lost-when-using-custom-error-types
=> fix(err): add support for error causes

src/__tests__/utils/event-utils.test.ts, src/utils/index.ts
Turns out we were filtering out non-string properties. Let's not do that 😬
=> fix: timezone offset property not being sent

.eslintrc.js, playground/flags/demo.html, playground/flags/package.json, playground/flags/server.js
The `playground/flags` directory had a `demo.html` file in there, but it looked incomplete and there wasn't any clear way to run the demo. So I turned it into a simple node project using express so we have a quick way to test out changes to the client library.
I also excluded the `playground` directory from our eslint checks since it's just a playground.
This doesn't affect the actual library.
=> chore: Make the flags demo runnable

package.json, pnpm-lock.yaml, src/posthog-core.ts, terser-mangled-names.json
Chrome and some frameworks such as Wordpress prerender a page because they want the loading time to be fast. We were, however, including that render (which runs Javascript) as a pageview even though that page might never actually be shown to the user.
We're now being slightly more cautious about it and not triggering the pageview when we can safely detect the page isnt visible. We then attach a listener and only ever trigger the `pageview` in case the page is actually displayed
Inspired by the behavior in https://github.com/plausible/analytics/blob/beb3ae087b7e7310a13cb012d109ab38d31301d5/tracker/src/plausible.js
=> feat: Avoid tracking pageview from prerenders

.eslintrc.js, playground/error-tracking/nuxt-ts/plugins/posthog.client.js, playground/nextjs/pages/_app.tsx, playground/nuxtjs/plugins/posthog.client.js, playground/react-router/app/components/Navigation.tsx, playground/react-router/app/root.tsx, playground/react-router/app/routes/home.tsx, playground/react-router/pnpm-lock.yaml, playground/session-recordings/index.html, src/posthog-core.ts
Just the docs, I started to do that long ago but there was some missing bits which this PR updates.
To recall, this change all SPA playgrounds to use `capture_pageview: 'history_change'` config to track `pageviews`.
If you can test this locally, that would be great. I've tried them all but it could have some edge cases.
=> docs: use history_change option on SPA playgrounds 

playwright/session-recording/session-recording-linked-flags.spec.ts, playwright/utils/posthog-playwright-test-base.ts, playwright/utils/setup.ts, src/__tests__/extensions/replay/sessionrecording.test.ts, src/extensions/replay/triggerMatching.ts
finally a false flag that isn't a conspiracy theory!
it used to be safe to check for the presence of a flag 
but we recently started returning flags that are enabled but false
so, it's not safe any more and replay linked flags was broken as a result
i had seen that we changed that API but wrote this code so long ago I totally missed this consequence
=> fix: false flag should not trigger linked flags

rollup.config.js, src/__tests__/posthog-core.test.ts, src/__tests__/posthog-core.ts, src/extensions/segment-integration.ts, src/posthog-core.ts, terser-mangled-names.json
We hid `_calculate_event_properties` as part of the property mangling work that hid all private methods and methods beginning with `_`.
It turns out that there are some valid uses for this method (see https://posthog.slack.com/archives/C03JJKLEC8L/p1746810877789529?thread_ts=1746572351.320289&cid=C03JJKLEC8L), and we should make it part of the public API.
I did this and added a `readOnly` argument, so it can be used without updating the internal state.
I also unhid `_calculate_event_properties` but added a deprecation warning to it
=> feat: Add calculateEventProperties to public API

src/utils/blocked-uas.ts
Extracted from https://developers.google.com/search/docs/crawling-indexing/google-common-crawlers
=> fix: Block newer google bots

src/__tests__/__snapshots__/config-snapshot.test.ts.snap, src/__tests__/posthog-core.loaded.test.ts, src/posthog-core.ts, src/posthog-featureflags.ts, src/types.ts
Context: https://posthog.slack.com/archives/C075EH38BR8/p1748544593177269?thread_ts=1748335261.479809&cid=C075EH38BR8
Ships with https://github.com/PostHog/posthog/pull/32925.  That change should go first.
=> feat(flags): add `advanced_only_evaluate_survey_feature_flags` config to explicitly only evaluate survey flags on the frontend

src/__tests__/posthog-core.ts, src/posthog-core.ts
We were naively JSON.stringifying the config object, which will throw if there are circular references (or e.g. BigInts).
I remove the call to JSON.stringify as it was only used to change how the debug text appears in the browser console.
Also added a test to protect against future changes
=> fix: Fix crash when config has circular references

.github/workflows/cd.yml
- fix package path in cd workflow
=> fix: fix check-package-version step

eslint-rules/no-external-replay-imports.js
https://github.com/PostHog/posthog-js/pull/1980 is going to be messy to update in the new workspace
let's see if we can chop it up to make life easier
=> chore: improve eslint rule

README.md, packages/browser/playground/nextjs/pages/_app.tsx, packages/browser/playground/nextjs/pages/external_chat.tsx, packages/browser/playground/nextjs/src/Header.tsx, packages/browser/playground/nextjs/src/posthog.ts, packages/browser/src/__tests__/__snapshots__/config-snapshot.test.ts.snap, packages/browser/src/entrypoints/array.full.es5.ts, packages/browser/src/entrypoints/crisp-chat-integration.ts, packages/browser/src/entrypoints/intercom-integration.ts, packages/browser/src/extensions/external-integration.ts, packages/browser/src/posthog-core.ts, packages/browser/src/types.ts, packages/browser/src/utils/globals.ts
replaces https://github.com/PostHog/posthog-js/pull/1980
easier to recreate than fangle the merge
----
if you've got intercom or crisp chat on your site, you might want to auto-link session replay to user interactions
you can do this manually but it might be nice to make it easy for folk
=> feat: push replay and person data to intercom and crisp chat

packages/browser/playground/nextjs/src/posthog.ts
We were using a separate system, but posthog supports cookie consent so why not use that?
Edit: testcafe is having some problems with Safari, but I don't believe there's a real problem with this PR
=> feat: Use posthog consent in next playground

packages/browser/src/__tests__/posthog-core.ts, packages/browser/src/__tests__/posthog-persistence.test.ts, packages/browser/src/posthog-core.ts, packages/browser/src/posthog-persistence.ts, packages/browser/src/storage.ts, packages/browser/terser-mangled-names.json
Otherwise it was possible for us to write the windowId to sessionStorage in `sessionid.ts` despite `opt_out_capturing_by_default` being set.
Added a test to ensure this
Edit: testcafe is having some problems with Safari, but I don't believe there's a real problem with this PR
=> fix: Sync consent with persistence immediately

packages/browser/src/posthog-core.ts, packages/browser/src/posthog-exceptions.ts
- Some users need the event id to easily find an issue
- Return capture results from the captureException method
=> feat(err): return capture results from captureException

.github/workflows/bundled-size.yaml, .github/workflows/library-ci.yml
- Split write mangled property names job
- Build lib only once for bundle size checks
=> chore(ci): optimize ci runs

.changeset/config.json, .github/workflows/label-version-bump.yml, packages/browser/CHANGELOG.md, packages/react/package.json
- Right now releasing a patch or minor version of posthog-js, create a major version bump in @posthog/react.
- Add all files generated by changesets
There is a [PR](https://github.com/changesets/changesets/pull/1132) that is being ignored since 2023 about this issue.
- hardcode peer dependencies in posthog-react, to avoid unecessary releases
=> chore(ci): fix react peer dependencies

packages/browser/README.md
- remove outdate release instructions on posthog-js
=> chore: remove release instruction on posthog-js

.github/workflows/release.yml
Fix: https://github.com/PostHog/posthog-js/actions/runs/16664571740/job/47168280438
- posthog-js is not updated on main repo and posthog.com because of permission issues
- fix workflow dispatch permissions
- make job fail on unsuccessful dispatch
- fix matrix strategy to still release other packages
=> chore(ci): fix workflow permissions

.changeset/proud-hairs-sleep.md, examples/example-nextjs/pnpm-lock.yaml, packages/nextjs-config/jest.config.mjs, packages/nextjs-config/package.json, packages/nextjs-config/rslib.config.mjs, packages/nextjs-config/src/utils.ts, packages/nextjs-config/src/webpack-plugin.ts, packages/nextjs-config/tsconfig.json, pnpm-lock.yaml, pnpm-workspace.yaml
Fix: https://github.com/PostHog/posthog-js/issues/2179
- use rslib to bundle nextjs-config
- provide shim for __dirname when transpiling
=> fix(nextjs-config): support esm config

package.json
We were linting every file multiple times in the pre-commit hook, which takes far longer than it should
This should ensure that
* each file only gets linted once
* we using caching
* we cover more kinds of file in the repo
* we should still get package-specific linting rules applied to file in that package
n/a
n/a
=> chore: Optimize lint-staged

packages/node/src/client.ts, packages/node/src/extensions/feature-flags/feature-flags.ts
This refactors both `compute*Locally` methods into a single one.
Two separate methods for what is essentially the same operation is going to cause headaches down the line.
For example, while working on [local evaluation support for flag dependencies](https://github.com/PostHog/posthog-python/pull/288), I ended up having two code paths for dependency evaluation. First to evaluate the flag value in a dependency-aware manner. Then I had to evaluate flag payloads. This was confusing and brittle.
* Wrote a new `computeFlagAndPayloadLocally` method that computes the flag value and payload
- This method accepts an optional provided `matchValue` and skips flag value evaluation if provided and uses that value to get the payload.
* Update `client.ts` to use the new method.
* Removed …
=> refactor(flags): Unify method to compute flag value and payload

packages/browser/scripts/specs/constants.js, packages/browser/scripts/specs/parser.js, packages/browser/scripts/specs/types.js, packages/browser/src/posthog-core.ts
- No doc types are no longer needed (we figured our a smarter way to display types on the website)
- Marks a method that doesn't look public internal, hiding it from specs
- Fixes a bug with types that joins many literals
Updates spec gen code.
=> fix: Updates to spec generation

packages/browser/playwright/mocked/session-recording/session-recording-network-recorder.spec.ts, packages/browser/playwright/mocked/tracing-headers.spec.ts
i think firefox is being too spec compliant here and not letting me misbehave
let's skip on firefox
=> chore: skip test that fails frequently on firefox

.changeset/old-ideas-yawn.md, .changeset/wise-pants-nail.md, packages/ai/src/langchain/callbacks.ts, packages/ai/src/utils.ts, packages/ai/tests/anthropic.test.ts, packages/ai/tests/callbacks.test.ts, packages/ai/tests/gemini.test.ts, packages/ai/tests/openai.test.ts, packages/ai/tests/vercel.test.ts
In the Python SDK, we can clearly see the SDK version because the LLM Analytics related code is part of the same library as the rest, whereas in the Node SDK it is not. We only see the posthog-node version in the event, which makes it hard to easily see what posthog-ai library version was used to send an event.
This sends two new properties in the LLM Events: `$ai_lib` and `$ai_lib_version`.
=> chore(llma): include ai lib version in event

.changeset/clever-rings-itch.md, packages/browser/rollup.config.mjs
see private slack thread: https://posthog.slack.com/archives/C040PJN7011/p1756503041390999
terser had started mangling one of our variables to `$`
using terser's `reserved` lets us avoid doing that
so lets
=> fix: don't mangle to $

.changeset/slick-spoons-search.md, packages/nextjs-config/package.json, pnpm-lock.yaml
- bump posthog/cli version to include batch processing
=> fix(err): upgrade posthog/cli version

.changeset/stale-taxes-unite.md, packages/browser/src/__tests__/segment.test.ts, packages/browser/src/extensions/replay/external/lazy-loaded-session-recorder.ts
when replay is running and pageview capture is disabled
we have simple url tracking which gets emitted to the replay events table as metadata
we say 
* when emitting an event that is not a meta event
* if rrwebEvent url is not the same as privately tracked `lastUrl`
* then emit a `urlChanged` custom event that holds the url
* and then update the privately tracked `lastUrl`
but if the custom event is emitted before the tracking variable is updated then we'll emit _another_ url 
and that might cause us to...
etc
instead let's update the privately tracked `lastUrl` and then emit the rrweb custom event
=> fix: order of operations when replay does pageview fallback

.changeset/shiny-bushes-stare.md, packages/browser/src/__tests__/featureflags.test.ts, packages/browser/src/posthog-featureflags.ts
`isFeatureEnabled` currently returns `false` in cases where the specified feature flag is disabled or does not exist. This means cases where the feature flag exists but has not matched conditions cannot be differentiated.
`isFeatureEnabled` now correctly returns `undefined` in cases where if the specified feature flag does not exist or is disabled.
Resolves #2247
=> fix(flags): `isFeatureEnabled` discerns missing feature flags in return value

.changeset/thin-hoops-fix.md, packages/nextjs-config/src/utils.ts
https://github.com/PostHog/posthog-js/issues/2333
- add shell option to spawn to support windows execution
=> fix(nextjs-config): fix windows execution

.github/workflows/posthog-com-upgrade.yml
- posthog.com uses node 22
- https://github.com/PostHog/posthog-js/actions/workflows/posthog-com-upgrade.yml
- increase node version for upgrade workflow
=> fix(posthog-js): fix posthog.com upgrade workflow

.changeset/loud-eels-tan.md, packages/browser/src/__tests__/__snapshots__/config-snapshot.test.ts.snap, packages/browser/src/__tests__/autocapture.test.ts, packages/browser/src/autocapture-utils.ts, packages/browser/src/autocapture.ts, packages/browser/src/types.ts
sometimes we want to allow autocapture on an element
but we know we don't want rageclicks
for example "previous" and "next" buttons are often clicked quickly and show up as rageclicks when they shouldn't
let's support a new default of `.ph-no-rageclick` to mirror the existing `.ph-no-capture`
and allow a custom list of selectors - since some sites will have an existing set of selectors that already make sense
when `.ph-no-rageclick` or the configured selector ignorelist is matched we don't capture a rageclick
=> feat: allow ignoring rageclick by css selector

packages/browser/src/__tests__/customizations/getChangeStateKeys.test.ts
the perf limits on the execution time tests for getChangedStateKeys were too close to the wire
let's give it some breathing room
See https://posthog.slack.com/archives/C09ADEV3AJD/p1758709244968169
=> chore: flapping execution time tests

.changeset/chatty-planets-rescue.md, packages/browser/src/extensions/replay/triggerMatching.ts
see https://github.com/PostHog/posthog-js/issues/2361
as we rolled lazy loaded replay out and then had to roll it back a rename has been added to simplify the code that will eventually be released
but folk who are pinned to the original lazy loaded version can end up calling code that doesn't exist any more 🫠
this puts those methods back and just delegates straight through to the renamed "current" methods
=> fix: over eager rename of onRemoteConfig

.changeset/eager-taxes-spend.md, packages/browser/playwright/mocked/session-recording/lazy-session-recording-sampling.spec.ts, packages/browser/playwright/mocked/session-recording/lazy-session-recording.spec.ts, packages/browser/src/__tests__/extensions/replay/lazy-sessionrecording.test.ts, packages/browser/src/extensions/replay/external/lazy-loaded-session-recorder.ts
spotted while testing the lazy loaded recorder
only going to fix in the lazy loaded recorder as i'm trying to switch to it and don't want to muddy the testing waters
* store session id instead of boolean for sampled flag
* take full snapshot only once a minute only if not yet started
* add unit tests for lazy recording since production soak is taking so long
=> fix: 2 small conditional recording fixes

.changeset/wise-fans-mix.md, packages/browser/src/__tests__/extensions/replay/lazy-sessionrecording.test.ts, packages/browser/src/extensions/replay/external/lazy-loaded-session-recorder.ts, packages/browser/src/extensions/replay/sessionrecording.ts, packages/browser/terser-mangled-names.json
since i've been changing this code it's in my head
while i was looking at the meta event playback issue
my subconscious realised this code isn't correct
so even if it's unrelated we should fix it
---
when we're in a trigger pending state (e.g. waiting for a url or event trigger)
we take a full snapshot every minute (to keep the buffer size down)
when we get a fullsnapshot we clear the buffer
but before a fullsnapshot we get a meta event
and we have to keep the meta event for a recording to be playable
so we don't want to clear the buffer we want to clear everything from before the meta event
(this is implemented as if there could be events between the meta and the full snapshot, in practice there won't be but for safety...)
=> fix: buffer rotation while pending

.changeset/beige-corners-camp.md, packages/browser/rollup.config.mjs
we don't want to mangle to $ ever
this updates so that the no external and es5 builds don't do that (previously they simply accepted the mangler defaults)
this won't fix every clash with jquery
since we rely on preact and chrome web vitals and at the time of writing they both mangle something to `$`
follows https://github.com/PostHog/posthog-js/pull/2266
=> fix: don't mangle to dollar in any build

.changeset/khaki-shirts-tell.md, packages/browser/src/extensions/replay/external/network-plugin.ts
trying to see any obvious leaks in this code that could cause a recorder to hold on to data or dom elements
the xhr wrapper registers an event listener but never clears it
_maybe_ this could cause a circular reference, so let's unregister the listener when we're handling it
to make it a one time listener
=> fix: potential memory leak in xhr network plugin

.changeset/four-bushes-fold.md, packages/react/rollup.config.mjs
Reverts PostHog/posthog-js#2374
this breaks the release process by leaving many new files in packages/browser/react/src/ after a build
=> revert: "fix(react): fix react sourcemaps"

.github/workflows/release.yml, packages/browser/CHANGELOG.md
we had a silent npm release failure for three posthog-js releases
let's correct the changelog so folks don't think there are releases that don't exist
and let's send an event to posthog if it happens in future
so we can alert with CDP
=> chore: correct changelog and 'alert' on release failures

.changeset/strong-trams-see.md, packages/browser/.gitignore, packages/react/package.json, packages/react/rollup.config.mjs
https://github.com/PostHog/posthog-js/pull/2374
- copy react/src alongside react/dist
- gitignore react/src
- add src to react package
=> fix(react): fix react sourcemap

packages/browser/playground/README.md, packages/browser/playground/nextjs/README.md, packages/browser/playground/nextjs/package.json, packages/browser/playground/nextjs/pnpm-workspace.yaml, pnpm-workspace.yaml
The nextjs playground doesn't point to the locally built posthog-js by default
* Point to local posthog-js
* Make pnpm-workspace.yaml empty
* Add (very redundant, we already exclude these) exclusion rules to exclude playground and examples directories from pnpm workspace (we don't need this change at all, I'm just paranoid about future refactors)
* Update comment
=> chore: Help getting local dev nextjs example working

.changeset/yellow-jobs-open.md, examples/example-web/pnpm-lock.yaml, packages/web/package.json, packages/web/src/context.ts, pnpm-lock.yaml
- core is not bundled with posthog-js-lite and not referenced as a dependency on posthog-js-lite
- add it as a dependency
- use version file from prebuild step
- include src folder for sourcemap definition
=> fix(web): fix posthog-js-lite deps

.changeset/funny-rocks-pump.md, packages/browser/src/__tests__/extensions/replay/lazy-sessionrecording.test.ts, packages/browser/src/__tests__/extensions/replay/sessionRecording-onRemoteConfig.test.ts, packages/browser/src/extensions/replay/external/lazy-loaded-session-recorder.ts, packages/browser/src/extensions/replay/sessionrecording-wrapper.ts, packages/browser/src/extensions/replay/sessionrecording.ts, packages/browser/src/extensions/replay/triggerMatching.ts, packages/browser/src/types.ts
lifting changes out of https://github.com/PostHog/posthog-js/pull/2404
i want to make as many changes as possible before removing the lazy loaded code so i have a chance to back out of i need to
we're tracking received flag in the lazy loaded code, but not using it
and types are wrong... sessionRecording can be false but we don't represent that
=> fix: lazy replay received flag tracking should be in the wrapper

.changeset/seven-dodos-do.md, packages/browser/src/__tests__/cookieless.test.ts, packages/browser/src/posthog-core.ts
https://github.com/PostHog/posthog-js/issues/2401
Starts the queue immediately when opting in.
Assuming this is the case, as it's a change in posthog-core.
=> fix: start queue after opting in

.changeset/curly-foxes-repeat.md, packages/browser/src/extensions/replay/sessionrecording-wrapper.ts
if we have a lazy recorder we can return its status no matter what
so, it's safer to do that
than risk a state tracking problem with the "received flags" boolean
=> fix: slightly safer replay status reporting
