PostHog/posthog-js

- src/posthog-core.js
https://github.com/PostHog/posthog/issues/509
> Don't reset device id on reset()

- src/autocapture.js
- src/utils.js
I tested locally and it works as far as I can tell.
> Send $host and $pathname with all calls

- .github/pull_request_template.md
> Add tests checkbox to PR template

- src/posthog-core.js
- Closes #66
- Fixes request batching when using via npm
- Starts the batched request sending on '_loaded', not just '_dom_loaded' (restart on _dom_loaded in case that's called after)
- Makes sure only one batching queue is running (so it really restarts)
> Start queue on _loaded

- src/posthog-core.js
I needed a way to sanitize URLs and other properties, so I added a callback.  Not sure if this is at all helpful, feel free to close/merge/request changes as you see fit.
> Add property sanitization callback.

- CHANGELOG.md
- package.json
- src/autocapture.js
Use composedPath() which works on all major browsers.
> Fix shadowroot firefox

- src/posthog-featureflags.js
every time a flag is used we'll create an event. This way we can have aggregate stats on feature flags!
> Add feature_flag_called event

- playground/sentry.html
- src/posthog-core.js
> Fix sentry integration

- src/module.d.ts
> Fix module.d.ts errors

- .github/workflows/unit.yml
- package.json
- src/__tests__/autocapture.js
- src/__tests__/loader.js
- src/autocapture.js
- src/extensions/toolbar.js
- src/lz-string.js
Original goal was to introduce https://github.com/amilajack/eslint-plugin-compat but it doesn't really catch any of the incompatibilities we care about. Still worth fixing these issues.
> Improve linting

- src/__tests__/loader.js
- src/__tests__/posthog-core.js
- src/api-actions.js
- src/autocapture-utils.js
- src/module.d.ts
- src/posthog-core.js
- src/posthog-people.js
- src/posthog-persistence.js
- src/utils.js
Solves #104 
Depends on PR #105, change target branch before merging.
> Kill dead code

- src/__tests__/featureflags.js
- src/module.d.ts
- src/posthog-core.js
- src/posthog-featureflags.js
> Allow toggling of feature_flag_called

- src/utils.js
> Kill some dead utils

- src/extensions/sessionrecording.js
https://github.com/PostHog/posthog/pull/2279 can be merged subsequently to this.
Docs: https://github.com/PostHog/posthog.com/pull/634
> update block class

- .github/workflows/ssr.yml
- package.json
- src/posthog-core.js
- src/utils.js
Also with a github check that should let us know if this breaks.
I'm not actually sure this will fix issue in #114, given that the module can't really be initialized/used while SSR, but it can be required at least assuming it gets re-evaluated at runtime.
> Try to re-add server-side module require support

- src/module.d.ts
Got sick and tired looking at this noise every PR.
> Make module.d.ts lint

- cypress/integration/capture.spec.js
- src/posthog-core.js
> Fix headers issue

- src/__tests__/extensions/sessionrecording.js
- src/__tests__/posthog-core.js
- src/__tests__/request-queue.js
- src/capture-metrics.js
- src/extensions/sessionrecording.js
- src/posthog-core.js
- src/request-queue.js
This hopefully will help us debug issues with events not reaching us
The config value is undocumented, we'll use it only internally for now
> Send metrics on unload

- src/posthog-core.js
- src/posthog-people.js
We're seeing a weird sentry error: https://sentry.io/organizations/posthog/issues/2079528998/?project=1899813
Removing some suspect code (see commits)
> Small fixes around send_request

- .github/workflows/react.yml
- react/src/context/__tests__/PostHogContext.test.jsx
- react/src/context/__tests__/PostHogProvider.test.jsx
- react/src/hooks/__tests__/useFeatureFlags.test.jsx
- Kill dead code, fix a test case
- Use `given2` in rest of the tests.
- Add github action
> Minor tweaks to react tests

- cypress/integration/capture.spec.js
- src/__tests__/extensions/rageclick.js
- src/autocapture.js
- src/extensions/rageclick.js
- src/module.d.ts
- src/posthog-core.js
The plan is to turn it on for us and see whether it's useful. If it is,
we'll autocapture it going forward if session recording is turned on.
https://github.com/PostHog/posthog/issues/2772
...
> Capture $rageclick events

- .github/workflows/auto-new-version.yml
- .github/workflows/label-version-bump.yml
Copied from plugin-server. Auto update version on merge here and create a PR on /posthog
@Twixes Does this look correct? I literally just did `s/plugin-server/posthog-js`
> auto update version

- .github/pull_request_template.md
- .github/workflows/auto-new-version.yml
This adds automatic CHANGELOG.md update to automatic version release.
> Add autochangelog

- .github/workflows/auto-new-version.yml
Small fixes for two issues that remained.
> Fix auto new version

- README.md
Cleaned up a heading in README just because.
> Bump version after sed fix

- .github/workflows/label-version-bump.yml
- CHANGELOG.md
- package.json
Update Yarn lock in version bump comment if needed.
> Add Yarn lock resiliency

- src/module.d.ts
- src/posthog-persistence.js
remove old code that we never used
> Remove old upgrade code (never used)

- src/module.d.ts
- src/posthog-core.js
https://github.com/PostHog/posthog-js/pull/190 added new functionality
but did not update the docs appropriately
> Fix ".identify" docstrings

- package.json
- src/module.d.ts
- src/posthog-core.js
- yarn.lock
> Actually fix SentryIntegration typing

- package.json
- src/__tests__/autocapture.js
- src/autocapture.js
- src/extensions/sessionrecording.js
- src/module.d.ts
- src/posthog-core.js
Submitting this super quickly before a call just so I don't forget.
We might want to consider supporting other rrweb config props as well.
User request.
> Support rrweb mask all inputs

- src/module.d.ts
> Update types, add missing reloadFeatureFlags

- package.json
Bumps version to include latest advanced config. Matching docs, https://github.com/PostHog/posthog.com/pull/1206
> Bump version to 1.10.0

- README.md
> Update outdated releasing instructions

- src/__tests__/retry-queue.js
- src/posthog-core.js
- src/retry-queue.js
- src/send-request.js
- An attempt to simplify the queue from https://github.com/PostHog/posthog-js/pull/226
- Totally WIP. I haven't run the tests yet. 
- Putting it out there as an example of a simpler way to do the same thing.
> A more basic retry queue

- README.md
> Add extra local development instructions

- src/send-request.js
Retrying won't do any good here, it just causes spam. In this case a needless alert.
> Don't retry 500 responses

- package.json
- yarn.lock
Just upgrading Sentry library. Hopefully fixes this problem when also bumped up in the main repo: https://github.com/PostHog/posthog/pull/5622
> Update `@sentry/types` to 6.11

- package.json
- yarn.lock
Resolves https://github.com/PostHog/posthog/issues/4671.
> Update `rrweb` to 1.0.3

- src/posthog-featureflags.js
- Fix for when there are no feature flags
> Fix "undefined is not an object" error

- src/posthog-core.js
> console.warn to error

- src/posthog-core.js
> fix groupKey

- src/__tests__/extensions/toolbar.js
- src/extensions/toolbar.js
Reverts PostHog/posthog-js#264
Closes https://github.com/PostHog/posthog-js/issues/275
Should be fine to do this if it's causing issues
> Revert "Do not load toolbar when disabled"

- src/posthog-core.js
> Trigger onFeatureFlags on reset

- src/posthog-core.js
Reverts PostHog/posthog-js#263
> Revert "Trigger onFeatureFlags on reset"

- README.md
- src/__tests__/capture-metrics.js
- src/capture-metrics.js
- src/compression.js
- src/posthog-core.js
Reverts PostHog/posthog-js#293
> Revert "Speculative logging for PostHog/posthog#4816"

- README.md
Add instructions for developing with Yalc to README
- N/A Tests for new code (if applicable)
- N/A TypeScript definitions (module.d.ts) updated and in sync with library exports (if applicable)
> Add instructions for developing with Yalc

- src/module.d.ts
corrects exported type from #296
> corrects exported type which got out of sync with core.js file

- src/__tests__/posthog-core.js
adds a test for a config setting
> add a test for init-ing and reading the on xhr error handler

- playground/flags/demo.html
- src/__tests__/posthog-people.js
- src/api-actions.js
- src/module.d.ts
- src/posthog-people.js
~~**Still needs types and docstrings**~~
> Add posthog.people.increment

- README.md
This PR has small formatting changes in the readme and the `bump minor` tag to trigger a new release
> Bump build and a readme change

- README.md
Don't mind me. Forgot to put the label on my last PR
> Just bumping the build for a release

- src/posthog-core.js
- src/retry-queue.js
Some handling for https://github.com/PostHog/posthog-js/issues/256
> Try sendbeacon

- .github/pull_request_template.md
Adds more items to the checklist in the pull request template. Follows on from #348
> Add more advice to pull request template

- src/extensions/toolbar.js
- Removes a line that dumps a lot of console logs for users.
- Resolves https://github.com/PostHog/posthog-js/issues/356
> Remove debug line

- src/utils.js
Adds another bot to the traffic blocklist. Requested by a user.
> feat(tracking): add ahrefsbot to list of ignored bots

- src/posthog-persistence.js
Case insensitive persistence setting
> fix(config): Case-insensitive persistence

- README.md
Forgot to put the build label on my last PR
> chore(build): bumping to make release

- .github/workflows/testcafe.yml
- playground/cypress/index.html
- testcafe/e2e.spec.js
- testcafe/helpers.js
Simplifies and fixes E2E tests with testcafe by using PostHog cloud
> fix: Testcafe using Posthog cloud

- package.json
- src/__tests__/extensions/toolbar.js
- src/extensions/toolbar.ts
Accompanying change to https://github.com/PostHog/posthog/pull/11411
> fix(toolbar): Use apiURL from state if set

- playground/session-recordings/index.html
- playground/session-recordings/server.js
- src/sessionid.ts
Was intrigued myself a little at how the browser sessionStorage works.
Related to this comment https://github.com/PostHog/posthog-js/pull/446#pullrequestreview-1114925597
> WindowId Alternative approach

- src/extensions/sentry-integration.ts
Closes https://github.com/PostHog/posthog-js/issues/449
This adds a few new sentry integration specific properties: `$sentry_tags`, `$sentry_exception_message`, `$sentry_exception_type`
> feat: Improve SentryIntegration, include error message, type and tags at top level

- src/__tests__/decide.js
- src/decide.ts
- src/posthog-core.ts
- src/types.ts
Goes together with https://github.com/PostHog/posthog/pull/12179
> feat(apps): rename "inject" to "site apps"

- CHANGELOG.md
- package.json
> chore: Release 1.38.1

- .github/workflows/cd.yml
We still have issues creating the PR as pnpm is not available in the related step
> fix: Install pnpm for usage in PR step

- package.json
> chore: move types dependency from dependencies to devdependencies

- CHANGELOG.md
- package.json
- adds support for JSON payloads
- implements [resilient](https://github.com/PostHog/posthog/issues/13627) feature flag handling
> chore: bump to version 1.41.0

- src/__tests__/decide.js
- src/__tests__/featureflags.js
- src/decide.ts
- src/posthog-featureflags.ts
- status check should not be on the res var
...
> fix: revert status check

- package.json
- react/package.json
- react/yarn.lock
- yarn.lock
Upgrade @sentry/types to @sentry/types@7.37.2
https://posthog.slack.com/archives/C04J1TJ11UZ/p1676552624506259
...
> chore: upgrade @sentry/types

- package.json
- playground/nextjs/utils/posthog.ts
- rollup.config.js
- src/extensions/sessionrecording.ts
- src/loader-recorder-v2.ts
- src/types.ts
- yarn.lock
* Adds `recorder-v2.js` (rrweb2)
* Fixes missing console code from recorder.js import
> feat: Add rrweb2 support (experimental)

- src/loader-recorder-v2.ts
Forgot to add the bump label to the previous PR.
Enables optional loading of rrweb2
> feat: Add optional loading of rrweb2

- src/extensions/sentry-integration.ts
> chore: Remove Sentry types to reduce clashes

- package.json
Bumping version to get this in - https://github.com/PostHog/posthog-js/pull/552
> chore: no-op change to allow version bump

- src/utils.ts
Removes an extra support roundtrip.
> chore: show the real error in case of a random crash

- src/autocapture-utils.ts
@pauldambra doesn't trust typescript and neither should I. See https://github.com/PostHog/posthog-js/pull/563#discussion_r1123745875
...
> fix: tolerate undefined target

- package.json
- src/__tests__/posthog-core.js
- yarn.lock
> chore: Update rrweb to alpha6

- src/__tests__/autocapture-utils.js
- src/autocapture-utils.ts
Maybe there is some child in the tree that isn't an Element node, so we run into problems? Now checking to make sure the element we touch is an Element node.
...
> fix: debug nested span text, part 3

- src/extensions/web-performance.ts
Forgot to add the label on the last PR
> chore: Bump version

- README.md
Previous PR: https://github.com/PostHog/posthog-js/pull/613 I forgot to add the label. So a new one.
...
> chore: release new version

- CHANGELOG.md
- package.json
Release version 1.57.0 of the library.
> chore: bump version to 1.57.0

- src/utils.ts
Added prerender to blocked user agent string
...
> Update utils.ts to add Prerender bot string matching

- src/__tests__/featureflags.js
- src/__tests__/surveys.js
- src/posthog-core.ts
- src/posthog-persistence.ts
- src/posthog-surveys.ts
- src/types.ts
Add `getSurveys` call for JS library
...
> feat: get surveys api

- src/__tests__/surveys.js
- src/types.ts
Lint errors were blocking the release 🙈 
...
> fix(surveys): lint fixes for release

- cypress/e2e/identify.cy.js
- src/__tests__/test-uuid.js
- src/posthog-core.ts
- src/utils.ts
We've been running with this for posthog.com and app.posthog.com for several days and all is well
Switch the default?
> feat: use uuidv7 everywhere

- src/utils.ts
Add GPTBot to blocked user agents, see https://platform.openai.com/docs/gptbot
(quite a minimal and safe change so I didn't do much testing)
> feat: Filter out events from GPTBot

- src/extensions/sessionrecording.ts
Bad merge meant there was a missed `get_config`.
> fix: Fix config access

- src/__tests__/extensions/surveys.js
- src/extensions/surveys.ts
- src/posthog-surveys-types.ts
This PR copied over https://github.com/PostHog/feature-surveys/pull/19
I apologize for all the shoddy type casts
> feat(surveys): popup changes and multiple questions support

- src/__tests__/extensions/replay/config.test.ts
- src/extensions/replay/config.ts
Follow-up to https://github.com/PostHog/posthog-js/pull/889
makes comparison case insensitive
> fix: make header comparison case insensitive

- CHANGELOG.md
merging two PRs close together doesn't update the changelog as expected
...
> chore: correct the CHANGELOG.md

- src/storage.ts
We're using a date to uniqueify a cookie check. Let's uniqueify differently
> chore: uniquify differently

- src/extensions/surveys.ts
Forgot to update the next button scenario!
> fix(surveys): button text field fix

- cypress/e2e/capture.cy.js
A test is flaking (https://github.com/PostHog/posthog-js/actions/runs/6927414130/job/18841241997)
Try to de-flake it
> chore: deflake a test

- src/extensions/replay/sessionrecording.ts
We can listen for network connection status and enrich the session with a custom event when it changes
> feat: send custom event when network status changes

- src/rate-limiter.ts
see: https://posthog.com/questions/identify-not-working-on-a-different-subdomain
the rate limiter error (if our ratelimiter errors) looks scary and uncontrolled
but it's totally safe - we may need to fix something but it shouldn't look like the rate limiter is broken
let's make it look less scary
> chore: make rate limiter error less scary

- .github/pull_request_template.md
Add backwards compatibility warning to checklist
> chore: improve template to account for backwards compatibility

- src/extensions/surveys/components/QuestionTypes.tsx
Copy of https://github.com/PostHog/posthog-js/pull/1035/ with browserstack permissions
...
> fix(surveys): fix emoji scale

- src/__tests__/extensions/replay/config.test.ts
- src/extensions/replay/config.ts
clarifies that a payload was redacted
> fix: clarify redaction message

- src/extensions/replay/config.ts
should be `token` and not `tokenconst` 🙈
> fix: typo in deny list

- playground/nextjs/package.json
- playground/nextjs/pnpm-lock.yaml
V minor change, just something non ideal that got included in my last PR
> fix: nextjs playground version of posthog-js

- src/__tests__/posthog-core.js
- src/extensions/exception-autocapture/index.ts
- src/extensions/sentry-integration.ts
- src/posthog-core.ts
Closes https://github.com/PostHog/posthog/issues/21190
> fix: Include project token in urls 

- src/types.ts
Incorrect type called out in https://github.com/PostHog/posthog/issues/20100#issuecomment-2044539829
> fix: typing of maskTextFn

- src/__tests__/decide.js
- src/__tests__/surveys.test.ts
- src/decide.ts
- src/posthog-core.ts
- src/posthog-surveys.ts
- src/types.ts
Fixes https://github.com/PostHog/posthog-js/issues/932 
...
> feat(surveys): Add disable config option

- CHANGELOG.md
Add changelog to release shuffling questions and options.
> chore: Bump release to 1.131.5

- README.md
Modified the local dev instructions.  More context here: https://posthog.slack.com/archives/C068NGHEUSG/p1715847832547849
> chore: added local dev instructions using local paths intead of pnpm link

- CHANGELOG.md
- package.json
> chore: Bump version to 1.132.3

- src/__tests__/extensions/replay/sessionrecording.test.ts
I was playing around with the lifecycle of the session recording class' session id and broke some tests. It took me a while to realise that the tests look like they're testing that rrweb always starts with a asnapshot and a meta but they're not really. It was just a side effect of the types of event we were testing with
Expanded the test so that they'll maybe warn people more clearly in future
> chore: add a couple of tests

- CHANGELOG.md
- package.json
chore: Bump version to 1.134.0
...
> chore: Bump version to 1.134.0

- CHANGELOG.md
Releases `feat(survey): Event based survey: Show survey popup based on custom event` #1213
> chore: Bump version to 1.137.0

- package.json
- pnpm-lock.yaml
- src/__tests__/extensions/replay/mutation-rate-limiter.test.ts
- src/extensions/replay/mutation-rate-limiter.ts
- src/extensions/replay/sessionrecording-utils.ts
- src/extensions/replay/sessionrecording.ts
supersedes #1207 by clarifying the behaviour was already correct
the actual fix was probably #1225
> chore: add mutation rate limiter tests

- src/extensions/surveys.tsx
> fix(surveys): handle missing getNextSurveyStep

- src/extensions/surveys.tsx
> fix(surveys): fix missing confirmation message state

- src/__tests__/heatmaps.test.ts
so we don't break sanitization of heatmap data
> chore: add sanitization test to heatmaps tests

- src/utils/event-utils.ts
add rdt_cid as a campaign parameter
> feat: add rdt_cid as a campaign parameter

- CHANGELOG.md
> chore: missing changelog entry

- cypress/e2e/capture.cy.ts
- cypress/e2e/opting-out.cy.ts
see https://github.com/PostHog/posthog-js/issues/735
add a test to check behaviour
> chore: add a test

- src/__tests__/utils.test.ts
- src/utils/blocked-uas.ts
see https://posthog.slack.com/archives/C071CAKRFNW/p1720788683025759
adds a new crawler block and a test
> feat: add new google crawler

- src/__tests__/extensions/surveys/action-matcher.test.ts
this was causing things to fail for me locally
i guess we're not setup for having test and not-test files next to each other
(i was too lazy to look into why it was failing :))
> chore: move test file

- src/__tests__/autocapture.test.ts
- src/__tests__/posthog-core.identify.js
- src/__tests__/posthog-core.identify.ts
- src/__tests__/posthog-core.loaded.js
- src/__tests__/posthog-core.loaded.ts
let's remove one more posthog mock from the tests
and remove given from some tests
> chore: one less posthog mock and two fewer given tests

- src/decide.ts
- src/extensions/exception-autocapture/index.ts
- src/extensions/tracing-headers.ts
- src/extensions/web-vitals/index.ts
And tbh a few others too
This smack of copy pasta so i've made sure they all return (even decide where it doesn't really matter)
(I did try to add a test for web vitals but some shared state was tripping me up so the test only passed in isolation, _really_ I should fix that but also ⏲️ )
> fix: web vitals ignored error on init

- src/posthog-core.ts
Make life a bit easier to debug, as we can grab people's config
~~Tests for new code (see [advice on the tests we use](https://github.com/PostHog/posthog-js#tiers-of-testing))~
> feat: add debug startup log message

- src/extensions/surveys/surveys-utils.tsx
> fix(surveys): Center the X

- src/extensions/exception-autocapture/error-conversion.ts
Related to https://github.com/PostHog/posthog/pull/25707/files
Need a type to tag the enum
> chore: add stack type

- src/__tests__/posthog-core.ts
- src/extensions/replay/sessionrecording.ts
- src/posthog-core.ts
Track the state of session recording as a default event property
> feat: add $recording_status property

- src/entrypoints/web-vitals.ts
we want to make a table reporting _why_ web vitals values are poor... so we need to include attribution data too
> feat: include attribution with all web vitals

- patches/@rrweb__record@2.0.0-alpha.18.patch
- pnpm-lock.yaml
follow-up to https://github.com/PostHog/posthog-js/pull/1690
> fix: rrweb patch fix take 2

- src/__tests__/web-experiments.test.ts
- src/web-experiments.ts
- Stop using `textContent`
- Correctly set `current.innerHTML` as opposed to `parent.innerHTML`
- Clean up tests
> fix(no-code experiments): refactor (6)

- src/posthog-featureflags.ts
quick follow up to https://github.com/PostHog/posthog-js/pull/1729
> chore(flags): Fix confusing statement in getRemoteConfigPayload jsdoc comment

- .github/workflows/cd.yml
Update the `posthog-js` version for the frontend repo when making a PR to `PostHog/posthog`
> fix(devex): update frontend/package.json when pushing to main repo

- src/utils/blocked-uas.ts
see: https://posthog.slack.com/archives/C02E3BKC78F/p1741003217685439
https://www.semrush.com/kb/539-configuring-site-audit
looking here semrush also use siteauditbot as a user agent
let's add that
> fix: add semrush audit bot

- src/__tests__/utils.test.ts
- src/utils/blocked-uas.ts
I used metabase and claude (and good ol' open-massive-csv-file-in-ide-and-search) to find more bots to block
> feat: Block more bots

- playground/nextjs/pages/_app.tsx
- playground/nextjs/pages/replay-examples/media.tsx
- playground/nextjs/src/posthog.ts
i wanted an image blocking example so I could check the behavior
> chore: image blocking example

- src/utils/blocked-uas.ts
Block yet another semrush crawler/bot
> feat: Block yet another semrush crawler/bot

- src/extensions/exception-autocapture/chunk-ids.ts
- src/extensions/exception-autocapture/error-conversion.ts
- src/extensions/exception-autocapture/stack-trace.ts
- Read chunk ids from global object
- Add chunk ids to frames
> feat: add chunk_id to stack frames

- src/extensions/sentry-integration.ts
See https://github.com/PostHog/posthog-js/pull/1762 for full context
> fix: stop setting platform on sentry event

- playground/error-tracking/vue-ts-esbuild/.gitignore
- playground/error-tracking/vue-ts-esbuild/README.md
- playground/error-tracking/vue-ts-esbuild/index.html
- playground/error-tracking/vue-ts-esbuild/package.json
- playground/error-tracking/vue-ts-esbuild/pnpm-lock.yaml
- playground/error-tracking/vue-ts-esbuild/src/App.vue
- playground/error-tracking/vue-ts-esbuild/src/components/ErrorButton.vue
- playground/error-tracking/vue-ts-esbuild/src/components/throw-error.ts
- playground/error-tracking/vue-ts-esbuild/src/main.ts
- playground/error-tracking/vue-ts-esbuild/src/shims-vue.d.ts
- playground/error-tracking/vue-ts-esbuild/src/vite-env.d.ts
- playground/error-tracking/vue-ts-esbuild/tsconfig.app.json
- playground/error-tracking/vue-ts-esbuild/tsconfig.json
- playground/error-tracking/vue-ts-esbuild/tsconfig.node.json
- playground/error-tracking/vue-ts-esbuild/vite.config.ts
Add vite ts esbuild plaground for error tracking
> chore(err): add vite ts playground

- package.json
- playwright/web-vitals.spec.ts
- pnpm-lock.yaml
let's update web vitals and add a test to prove that we can emit at least one of the emits
> chore: update web vitals

- .husky/pre-push
was this me yet again being my own worst enemy
> chore: allow push to main in GH actions

- playground/nextjs/pages/toolbar-tests.tsx
- playground/nextjs/src/Header.tsx
- react/package.json
made an example to test an issue
may as well keep it
> chore: add a regression example for toolbar z-index highlighting

- playground/react-router/app/root.tsx
- playground/react-router/app/routes/surveys.tsx
- playground/react-router/package.json
- playground/react-router/pnpm-lock.yaml
We weren't doing pageviews, so I added them just to make sure things worked well, and that we had an example we could point to.
Also made it point to the local posthog-js
> feat: Make react router playground handle pageviews on route change

- src/extensions/exception-autocapture/index.ts
- terser-mangled-names.json
Does what it says on the tin really
> chore: make internal vars private

- playground/csp-violations/.gitignore
- playground/csp-violations/README.md
- playground/csp-violations/package.json
- playground/csp-violations/pnpm-lock.yaml
- playground/csp-violations/rollup.config.mjs
- playground/csp-violations/server.js
- playground/csp-violations/src/main.js
- playground/csp-violations/src/posthog.js
- playground/csp-violations/static/styles.css
Let's merge this, it's pretty useful for validating whether posthog-js cause any CSP violations
> feat: sample violations for easier testing

- playground/csp-violations/server.js
Defaulting to the trailing slash to avoid problems
> fix: csp trailing slash

- playwright/session-recording/session-recording-linked-flags.spec.ts
- src/__tests__/extensions/replay/sessionrecording.test.ts
- src/extensions/replay/triggerMatching.ts
closes https://github.com/PostHog/posthog-js/issues/1970
linked flag matching any variant was broken - presumably in the trigger matching change recently
added better tests
fixed the behaviour
split this code out to specific branches as the compact version was breaking my brain
> fix: linked flag any variant match

- packages/browser/README.md
Updating the readme to to test some things. No functional changes
> chore: update readme instructions

- packages/browser/package.json
Reverts PostHog/posthog-js#2019
> Revert "fix: fix release workflow"

- packages/browser/src/entrypoints/tracing-headers.ts
- packages/browser/src/extensions/tracing-headers.ts
- packages/browser/src/utils/globals.ts
https://github.com/PostHog/posthog-python/pull/263/files#r2152219291
> feat: add distinct id tracing header

- packages/browser/CHANGELOG.md
> chore: fix CHANGELOG.md

- pnpm-lock.yaml
Base PR: https://github.com/PostHog/posthog-js/pull/2042
- add changeset package to manage workspace versions
> chore(migraton): add changeset to manage versions

- .github/workflows/cd.yml
For Context: https://github.com/PostHog/posthog/pull/35213
- Update `posthog-js` at workspace level
- Tested locally
> fix(deps): update posthog-js at workspace level

- .github/actions/release/action.yaml
- .github/workflows/label-version-bump.yml
- .github/workflows/release.yml
- fix github action path
- install pnpm before publishing
Errors: 
- https://github.com/PostHog/posthog-js/actions/runs/16469644045/job/46555400865
- https://github.com/PostHog/posthog-js/actions/runs/16469643730
> fix(ci): fix release workflow

- .github/workflows/label-version-bump.yml
- install packages before calling changeset
error:
https://github.com/PostHog/posthog-js/actions/runs/16493448484/job/46633467862?pr=2089
> chore(ci): install before calling changeset

- .github/actions/is-affected/action.yaml
- .github/workflows/integration.yml
- .github/workflows/library-ci.yml
- .github/workflows/testcafe.yml
- packages/browser/src/autocapture.ts
- run integration, testcafe and playwright tests only when posthog-js is affected
> chore(ci): check if posthog-js is affected

- .github/workflows/posthog-upgrade.yml
For context: https://github.com/PostHog/posthog/pull/35612
- upgrade posthog-js recursively inside posthog repo
> fix: upgrade posthog-js recursively

- CONTRIBUTING.md
- update command orders to make sure tooling dependencies are built before running dev
> fix: update rules

- packages/ai/CHANGELOG.md
- packages/ai/package.json
- packages/node/CHANGELOG.md
- packages/react-native/package.json
- packages/react/package.json
- packages/web/CHANGELOG.md
- packages/web/package.json
- Clean package.json
- Clean changelogs to be compatible with changeset
> chore: clean packages and changelogs

- RELEASING.md
there's info that is only held in the collective consciousness that should be written down
> chore: update RELEASING.md about main repo PRs for browser SDK

- examples/.pnpmfile.cjs
- examples/example-cloudflare/package.json
- examples/example-cloudflare/pnpm-workspace.yaml
- examples/example-expo-53/README.md
- examples/example-expo-53/ios/exampleexpo53.xcodeproj/project.pbxproj
- examples/example-expo-53/package.json
- examples/example-expo-53/pnpm-lock.yaml
- examples/example-expo-53/pnpm-workspace.yaml
- examples/example-gcp-functions/package.json
- examples/example-nextjs/package.json
- examples/example-node/package.json
- examples/example-node/pnpm-lock.yaml
- examples/example-node/pnpm-workspace.yaml
- examples/example-nuxtjs/package.json
- examples/example-nuxtjs/pnpm-lock.yaml
- examples/example-nuxtjs/pnpm-workspace.yaml
- examples/example-web/package.json
- examples/example-web/pnpm-lock.yaml
- examples/example_rn_macos/package.json
- examples/example_rn_macos/pnpm-lock.yaml
- examples/example_rn_macos/pnpm-workspace.yaml
- Create default settings for all examples folder
- Pin package manager version
> fix(examples): fix installation steps

- .changeset/true-rings-doubt.md
- .eslintrc.cjs
- packages/ai/.eslintrc.cjs
- packages/ai/src/anthropic/index.ts
- packages/ai/src/gemini/index.ts
- packages/ai/src/langchain/callbacks.ts
- packages/ai/src/openai/azure.ts
- packages/ai/src/openai/index.ts
- packages/ai/src/utils.ts
- packages/ai/src/vercel/middleware.ts
- packages/ai/tests/azure-openai.test.ts
- packages/ai/tests/openai.test.ts
- packages/ai/tests/vercel.test.ts
Implements embeddings for OpenAI. Solves #2214.
> feat(llma): support-openai-embeddings

- packages/ai/src/utils.ts
Improves error handling and resilience for a truncation function that was raising some issues. Should fix #2237.
> fix(llma): truncation errors

- .changeset/great-horses-stare.md
- packages/ai/src/gemini/index.ts
- packages/ai/src/openai/azure.ts
- packages/ai/src/openai/index.ts
- packages/ai/src/utils.ts
- packages/ai/tests/azure-openai.test.ts
- packages/ai/tests/gemini.test.ts
- packages/ai/tests/openai.test.ts
- packages/ai/tests/system-prompts-utils.test.ts
Solves #2290, implements equivalent behaviour to [this PR for the Python SDK](https://github.com/PostHog/posthog-python/pull/326).
> fix: ensure consistent system prompts

- .github/dependabot.yml
Opens a PR when there are updates to the AI SDKs. Runs daily.
> feat: auto update llm sdks
